import type { PlantillaProtegidaRow } from "@/hooks/usePlantillasProtegidas";
import { legalListBlockFor } from "./legal-template-normalizer";

const CREATED_AT = "2026-04-28T00:00:00.000Z";
const TENANT_ID = "local-legal-fixture";

type FixturePatch = Pick<
  PlantillaProtegidaRow,
  "id" | "tipo" | "capa1_inmutable" | "capa2_variables" | "capa3_editables"
> &
  Partial<PlantillaProtegidaRow>;

function fixture(patch: FixturePatch): PlantillaProtegidaRow {
  return {
    id: patch.id,
    tenant_id: patch.tenant_id ?? TENANT_ID,
    tipo: patch.tipo,
    materia: patch.materia ?? null,
    jurisdiccion: patch.jurisdiccion ?? "ES",
    version: patch.version ?? "LEGAL-FIXTURE-2026-04-28",
    estado: patch.estado ?? "ACTIVA",
    aprobada_por: null,
    fecha_aprobacion: null,
    contenido_template: patch.contenido_template ?? null,
    capa1_inmutable: patch.capa1_inmutable,
    capa2_variables: patch.capa2_variables,
    capa3_editables: patch.capa3_editables,
    referencia_legal: patch.referencia_legal ?? "Equipo legal - cuadro de plantillas Word",
    notas_legal:
      patch.notas_legal ??
      "Fixture local no persistido. Usar solo durante freeze Supabase hasta cargar plantilla aprobada.",
    variables: patch.variables ?? [],
    protecciones: patch.protecciones ?? { source: "legal-team-fixture", persisted: false },
    snapshot_rule_pack_required: patch.snapshot_rule_pack_required ?? true,
    adoption_mode: patch.adoption_mode ?? null,
    organo_tipo: patch.organo_tipo ?? null,
    contrato_variables_version: patch.contrato_variables_version ?? "variables-plantillas-v1.1",
    created_at: patch.created_at ?? CREATED_AT,
    materia_acuerdo: patch.materia_acuerdo ?? null,
    approval_checklist: patch.approval_checklist ?? [
      { check: "Validacion legal antes de carga en Supabase", passed: false },
    ],
    version_history: patch.version_history ?? [],
  };
}

const commonEntityVariables = [
  { variable: "denominacion_social", fuente: "ENTIDAD", condicion: "OBLIGATORIO" },
  { variable: "cif", fuente: "ENTIDAD", condicion: "RECOMENDADO" },
  { variable: "domicilio_social", fuente: "ENTIDAD", condicion: "RECOMENDADO" },
  { variable: "registro_mercantil", fuente: "ENTIDAD", condicion: "RECOMENDADO" },
];

const convocatoriaFields = [
  { campo: "lugar", obligatoriedad: "OBLIGATORIO", descripcion: "Lugar de celebracion de la reunion o junta." },
  { campo: "fecha_primera_convocatoria", obligatoriedad: "OBLIGATORIO", descripcion: "Fecha de primera convocatoria." },
  { campo: "hora_primera_convocatoria", obligatoriedad: "OBLIGATORIO", descripcion: "Hora de primera convocatoria." },
  { campo: "fecha_segunda_convocatoria", obligatoriedad: "RECOMENDADO", descripcion: "Fecha de segunda convocatoria, si procede." },
  { campo: "orden_dia_texto", obligatoriedad: "OBLIGATORIO", descripcion: "Orden del dia, un punto por linea." },
  { campo: "firma_organo_administracion", obligatoriedad: "RECOMENDADO", descripcion: "Firmante o cargo convocante." },
];

const actaFields = [
  { campo: "ciudad_emision", obligatoriedad: "OBLIGATORIO", descripcion: "Ciudad de emision del acta." },
  { campo: "lugar", obligatoriedad: "OBLIGATORIO", descripcion: "Lugar de celebracion." },
  { campo: "hora_inicio", obligatoriedad: "OBLIGATORIO", descripcion: "Hora de inicio." },
  { campo: "hora_fin", obligatoriedad: "RECOMENDADO", descripcion: "Hora de cierre." },
  { campo: "orden_dia_texto", obligatoriedad: "OBLIGATORIO", descripcion: "Orden del dia tratado, un punto por linea." },
  { campo: "acuerdos_texto", obligatoriedad: "OBLIGATORIO", descripcion: "Acuerdos adoptados, uno por linea." },
];

const unipersonalFields = [
  { campo: "ciudad_emision", obligatoriedad: "OBLIGATORIO", descripcion: "Ciudad de emision de la decision." },
  { campo: "fecha", obligatoriedad: "OBLIGATORIO", descripcion: "Fecha de adopcion de la decision." },
  { campo: "identidad_decisor", obligatoriedad: "OBLIGATORIO", descripcion: "Nombre del socio unico o administrador unico." },
  { campo: "nif_decisor", obligatoriedad: "RECOMENDADO", descripcion: "NIF/NIE del decisor, si debe constar." },
  { campo: "texto_decision", obligatoriedad: "OBLIGATORIO", descripcion: "Texto literal de la decision adoptada." },
  { campo: "firma_qes_ref", obligatoriedad: "RECOMENDADO", descripcion: "Referencia de firma QES o firma manuscrita." },
];

const adminJointFields = [
  { campo: "ciudad_emision", obligatoriedad: "OBLIGATORIO", descripcion: "Ciudad de cierre del acuerdo." },
  { campo: "fecha_cierre", obligatoriedad: "OBLIGATORIO", descripcion: "Fecha de cierre del expediente de decision conjunta." },
  { campo: "administradores_intervinientes_texto", obligatoriedad: "OBLIGATORIO", descripcion: "Administradores que intervienen, uno por linea, con cargo y sentido de decision." },
  { campo: "regla_actuacion", obligatoriedad: "OBLIGATORIO", descripcion: "Regla estatutaria o pactada de actuacion mancomunada." },
  { campo: "condicion_adopcion", obligatoriedad: "OBLIGATORIO", descripcion: "Condicion evaluada por el motor para considerar adoptada la decision." },
  { campo: "texto_decision", obligatoriedad: "OBLIGATORIO", descripcion: "Texto literal de la decision adoptada." },
  { campo: "conflictos_texto", obligatoriedad: "RECOMENDADO", descripcion: "Conflictos declarados, abstenciones o manifestacion de inexistencia." },
  { campo: "expediente_hash", obligatoriedad: "RECOMENDADO", descripcion: "Hash o identificador de integridad del expediente electronico." },
  { campo: "firma_qes_ref", obligatoriedad: "RECOMENDADO", descripcion: "Referencia QES/TSQ del expediente." },
];

const adminSolidaryFields = [
  { campo: "ciudad_emision", obligatoriedad: "OBLIGATORIO", descripcion: "Ciudad de emision de la decision." },
  { campo: "fecha", obligatoriedad: "OBLIGATORIO", descripcion: "Fecha de adopcion de la decision." },
  { campo: "administrador_actuante", obligatoriedad: "OBLIGATORIO", descripcion: "Administrador solidario que adopta o ejecuta la decision." },
  { campo: "facultad_actuacion", obligatoriedad: "OBLIGATORIO", descripcion: "Facultad estatutaria, delegada o legal que habilita la actuacion." },
  { campo: "texto_decision", obligatoriedad: "OBLIGATORIO", descripcion: "Texto literal de la decision o actuacion documentada." },
  { campo: "comunicaciones_texto", obligatoriedad: "RECOMENDADO", descripcion: "Comunicaciones al resto de administradores o manifestacion de no exigibilidad." },
  { campo: "conflictos_texto", obligatoriedad: "RECOMENDADO", descripcion: "Conflictos declarados, abstenciones o manifestacion de inexistencia." },
  { campo: "expediente_hash", obligatoriedad: "RECOMENDADO", descripcion: "Hash o identificador de integridad del expediente electronico." },
  { campo: "firma_qes_ref", obligatoriedad: "RECOMENDADO", descripcion: "Referencia QES/TSQ del expediente." },
];

const informePreFields = [
  { campo: "materia_acuerdo", obligatoriedad: "OBLIGATORIO", descripcion: "Materia o acuerdo al que se refiere el informe." },
  { campo: "objeto_informe", obligatoriedad: "OBLIGATORIO", descripcion: "Objeto y alcance del informe preceptivo." },
  { campo: "fundamento_legal", obligatoriedad: "OBLIGATORIO", descripcion: "Base legal, estatutaria o pactada aplicable." },
  { campo: "comprobaciones_texto", obligatoriedad: "OBLIGATORIO", descripcion: "Comprobaciones realizadas, una por linea." },
  { campo: "conclusion_informe", obligatoriedad: "OBLIGATORIO", descripcion: "Conclusion del informe y advertencias." },
];

const registralFields = [
  { campo: "certificacion_id", obligatoriedad: "RECOMENDADO", descripcion: "Identificador de certificacion base, si existe." },
  { campo: "documentacion_texto", obligatoriedad: "OBLIGATORIO", descripcion: "Documentos que se aportan o subsanan, uno por linea." },
  { campo: "datos_presentacion", obligatoriedad: "RECOMENDADO", descripcion: "Datos de presentacion registral, asiento o referencia." },
  { campo: "observaciones_registrales", obligatoriedad: "RECOMENDADO", descripcion: "Observaciones para notaria, registro o publicacion." },
];

export const LEGAL_TEAM_TEMPLATE_FIXTURES: PlantillaProtegidaRow[] = [
  fixture({
    id: "legal-fixture-convocatoria-junta-es",
    tipo: "CONVOCATORIA",
    organo_tipo: "JUNTA",
    capa1_inmutable: [
      "CONVOCATORIA DE JUNTA GENERAL",
      "",
      "Por la presente se convoca a los socios de {{denominacion_social}} a la Junta General {{tipo_junta}} que se celebrara en {{lugar}}, el dia {{fecha_primera_convocatoria}} a las {{hora_primera_convocatoria}}{{#if fecha_segunda_convocatoria}}, y, en su caso, en segunda convocatoria el dia {{fecha_segunda_convocatoria}} a la misma hora y lugar{{/if}}, con el siguiente orden del dia:",
      "",
      legalListBlockFor("orden_dia"),
      "",
      "{{#if derecho_informacion}}Derecho de informacion: {{derecho_informacion}}{{/if}}",
      "",
      "{{firma_organo_administracion}}",
    ].join("\n"),
    capa2_variables: [
      ...commonEntityVariables,
      { variable: "tipo_junta", fuente: "USUARIO", condicion: "OBLIGATORIO" },
      { variable: "lugar", fuente: "USUARIO", condicion: "OBLIGATORIO" },
      { variable: "fecha_primera_convocatoria", fuente: "USUARIO", condicion: "OBLIGATORIO" },
      { variable: "hora_primera_convocatoria", fuente: "USUARIO", condicion: "OBLIGATORIO" },
      { variable: "orden_dia", fuente: "USUARIO", condicion: "OBLIGATORIO" },
    ],
    capa3_editables: [
      { campo: "tipo_junta", obligatoriedad: "OBLIGATORIO", descripcion: "Tipo de Junta: ordinaria, extraordinaria o mixta." },
      ...convocatoriaFields,
      { campo: "derecho_informacion", obligatoriedad: "RECOMENDADO", descripcion: "Texto de derecho de informacion si la materia lo exige." },
    ],
  }),
  fixture({
    id: "legal-fixture-convocatoria-consejo-es",
    tipo: "CONVOCATORIA",
    organo_tipo: "CONSEJO",
    capa1_inmutable: [
      "CONVOCATORIA DEL CONSEJO DE ADMINISTRACION",
      "",
      "Por la presente se convoca a los miembros del Consejo de Administracion de {{denominacion_social}} a la reunion que se celebrara en {{lugar}}, el dia {{fecha_primera_convocatoria}} a las {{hora_primera_convocatoria}}, con el siguiente orden del dia:",
      "",
      legalListBlockFor("orden_dia"),
      "",
      "{{firma_organo_administracion}}",
    ].join("\n"),
    capa2_variables: [
      ...commonEntityVariables,
      { variable: "lugar", fuente: "USUARIO", condicion: "OBLIGATORIO" },
      { variable: "fecha_primera_convocatoria", fuente: "USUARIO", condicion: "OBLIGATORIO" },
      { variable: "hora_primera_convocatoria", fuente: "USUARIO", condicion: "OBLIGATORIO" },
      { variable: "orden_dia", fuente: "USUARIO", condicion: "OBLIGATORIO" },
    ],
    capa3_editables: convocatoriaFields,
  }),
  fixture({
    id: "legal-fixture-acta-junta-es",
    tipo: "ACTA_SESION",
    organo_tipo: "JUNTA",
    capa1_inmutable: [
      "ACTA DE JUNTA GENERAL",
      "",
      "En {{ciudad_emision}}, a {{fecha_junta}}, siendo las {{hora_inicio}}, se reune la Junta General {{tipo_junta}} de {{denominacion_social}}, en {{lugar}}, bajo la presidencia de {{presidente}} y actuando como secretario {{secretario}}.",
      "",
      "Porcentaje de capital presente o representado: {{porcentaje_capital_presente}}.",
      "",
      "ORDEN DEL DIA",
      legalListBlockFor("orden_dia"),
      "",
      "ACUERDOS",
      legalListBlockFor("acuerdos"),
      "",
      "{{#if hora_fin}}Sin mas asuntos que tratar, se levanta la sesion a las {{hora_fin}}.{{/if}}",
    ].join("\n"),
    capa2_variables: [
      ...commonEntityVariables,
      { variable: "fecha_junta", fuente: "REUNION", condicion: "OBLIGATORIO" },
      { variable: "presidente", fuente: "ORGANO", condicion: "OBLIGATORIO" },
      { variable: "secretario", fuente: "ORGANO", condicion: "OBLIGATORIO" },
      { variable: "porcentaje_capital_presente", fuente: "REUNION", condicion: "OBLIGATORIO" },
    ],
    capa3_editables: [
      { campo: "tipo_junta", obligatoriedad: "OBLIGATORIO", descripcion: "Tipo de Junta celebrada." },
      ...actaFields,
      { campo: "porcentaje_capital_presente", obligatoriedad: "OBLIGATORIO", descripcion: "Porcentaje de capital presente o representado." },
    ],
  }),
  fixture({
    id: "legal-fixture-acta-consejo-es",
    tipo: "ACTA_SESION",
    organo_tipo: "CONSEJO",
    capa1_inmutable: [
      "ACTA DEL CONSEJO DE ADMINISTRACION",
      "",
      "En {{ciudad_emision}}, a {{fecha}}, siendo las {{hora_inicio}}, se reune el Consejo de Administracion de {{denominacion_social}}, en {{lugar}}, bajo la presidencia de {{presidente}} y actuando como secretario {{secretario}}.",
      "",
      "Asisten los siguientes consejeros:",
      legalListBlockFor("miembros_presentes"),
      "",
      "ORDEN DEL DIA",
      legalListBlockFor("orden_dia"),
      "",
      "ACUERDOS",
      legalListBlockFor("acuerdos"),
      "",
      "{{#if hora_fin}}Sin mas asuntos que tratar, se levanta la sesion a las {{hora_fin}}.{{/if}}",
    ].join("\n"),
    capa2_variables: [
      ...commonEntityVariables,
      { variable: "fecha", fuente: "REUNION", condicion: "OBLIGATORIO" },
      { variable: "presidente", fuente: "ORGANO", condicion: "OBLIGATORIO" },
      { variable: "secretario", fuente: "ORGANO", condicion: "OBLIGATORIO" },
    ],
    capa3_editables: [
      ...actaFields,
      { campo: "miembros_presentes_texto", obligatoriedad: "OBLIGATORIO", descripcion: "Consejeros asistentes, uno por linea." },
    ],
  }),
  fixture({
    id: "legal-fixture-acta-consignacion-socio-unico-es",
    tipo: "ACTA_CONSIGNACION",
    adoption_mode: "UNIPERSONAL_SOCIO",
    referencia_legal: "Art. 15 LSC",
    capa1_inmutable: [
      "DECISION DEL SOCIO UNICO",
      "",
      "En {{ciudad_emision}}, a {{fecha}}, D./D.a {{identidad_decisor}}{{#if nif_decisor}}, con NIF {{nif_decisor}}{{/if}}, como socio unico de {{denominacion_social}}, en ejercicio de las competencias que le atribuye el articulo 15 de la Ley de Sociedades de Capital, adopta la siguiente decision:",
      "",
      "{{texto_decision}}",
      "",
      "La decision se consignara en el Libro de Actas de la sociedad, sin perjuicio de su elevacion a publico o inscripcion cuando proceda.",
      "",
      "{{#if firma_qes_ref}}Referencia de firma: {{firma_qes_ref}}{{/if}}",
    ].join("\n"),
    capa2_variables: [
      ...commonEntityVariables,
      { variable: "fecha", fuente: "EXPEDIENTE", condicion: "OBLIGATORIO" },
      { variable: "texto_decision", fuente: "USUARIO", condicion: "OBLIGATORIO" },
    ],
    capa3_editables: unipersonalFields,
  }),
  fixture({
    id: "legal-fixture-acta-consignacion-admin-unico-es",
    tipo: "ACTA_CONSIGNACION",
    adoption_mode: "UNIPERSONAL_ADMIN",
    referencia_legal: "Organo de administracion unipersonal",
    capa1_inmutable: [
      "DECISION DEL ADMINISTRADOR UNICO",
      "",
      "En {{ciudad_emision}}, a {{fecha}}, D./D.a {{identidad_decisor}}{{#if nif_decisor}}, con NIF {{nif_decisor}}{{/if}}, como administrador unico de {{denominacion_social}}, adopta en materias de su competencia la siguiente decision:",
      "",
      "{{texto_decision}}",
      "",
      "La decision se incorpora al expediente societario y, cuando proceda, se consignara en el Libro de Actas o se elevara a publico para producir sus efectos.",
      "",
      "{{#if firma_qes_ref}}Referencia de firma: {{firma_qes_ref}}{{/if}}",
    ].join("\n"),
    capa2_variables: [
      ...commonEntityVariables,
      { variable: "fecha", fuente: "EXPEDIENTE", condicion: "OBLIGATORIO" },
      { variable: "texto_decision", fuente: "USUARIO", condicion: "OBLIGATORIO" },
    ],
    capa3_editables: unipersonalFields,
  }),
  fixture({
    id: "legal-fixture-acta-acuerdo-escrito-sin-sesion-es",
    tipo: "ACTA_ACUERDO_ESCRITO",
    adoption_mode: "NO_SESSION",
    referencia_legal: "Art. 100 RRM / art. 248.2 LSC",
    capa1_inmutable: [
      "ACTA DE ACUERDO ESCRITO SIN SESION",
      "",
      "En {{ciudad_emision}}, a {{fecha_cierre}}, se deja constancia de que el expediente de adopcion de acuerdo sin celebracion de sesion se ha tramitado bajo la modalidad {{tipo_proceso}}.",
      "",
      "PROPUESTA",
      "{{propuesta_texto}}",
      "",
      "RELACION DE RESPUESTAS",
      legalListBlockFor("relacion_respuestas"),
      "",
      "CONDICION DE ADOPCION",
      "{{condicion_adopcion}}",
      "",
      "ACUERDO",
      "{{texto_decision}}",
      "",
      "{{#if expediente_hash}}Hash del expediente electronico: {{expediente_hash}}{{/if}}",
      "{{#if firma_qes_ref}}Referencia de firma: {{firma_qes_ref}}{{/if}}",
    ].join("\n"),
    capa2_variables: [
      ...commonEntityVariables,
      { variable: "tipo_proceso", fuente: "EXPEDIENTE", condicion: "OBLIGATORIO" },
      { variable: "relacion_respuestas", fuente: "EXPEDIENTE", condicion: "OBLIGATORIO" },
      { variable: "condicion_adopcion", fuente: "MOTOR", condicion: "OBLIGATORIO" },
    ],
    capa3_editables: [
      { campo: "ciudad_emision", obligatoriedad: "OBLIGATORIO", descripcion: "Ciudad de cierre del expediente escrito." },
      { campo: "fecha_cierre", obligatoriedad: "OBLIGATORIO", descripcion: "Fecha de cierre del expediente sin sesion." },
      { campo: "tipo_proceso", obligatoriedad: "OBLIGATORIO", descripcion: "UNANIMIDAD_CAPITAL_SL, CIRCULACION_CONSEJO u otra modalidad aplicable." },
      { campo: "propuesta_texto", obligatoriedad: "OBLIGATORIO", descripcion: "Texto de la propuesta circulada." },
      { campo: "relacion_respuestas_texto", obligatoriedad: "OBLIGATORIO", descripcion: "Respuestas recibidas, una por linea, con sentido y fecha si procede." },
      { campo: "condicion_adopcion", obligatoriedad: "OBLIGATORIO", descripcion: "Condicion evaluada por el motor para considerar adoptado el acuerdo." },
      { campo: "texto_decision", obligatoriedad: "OBLIGATORIO", descripcion: "Texto literal del acuerdo adoptado." },
      { campo: "expediente_hash", obligatoriedad: "RECOMENDADO", descripcion: "Hash o identificador de integridad del expediente electronico." },
      { campo: "firma_qes_ref", obligatoriedad: "RECOMENDADO", descripcion: "Referencia QES/TSQ del expediente." },
    ],
  }),
  fixture({
    id: "legal-fixture-acta-decision-conjunta-es",
    tipo: "ACTA_DECISION_CONJUNTA",
    adoption_mode: "CO_APROBACION",
    organo_tipo: "ADMIN",
    referencia_legal: "Regimen de administracion mancomunada; LSC, estatutos y pactos aplicables",
    capa1_inmutable: [
      "ACTA DE DECISION CONJUNTA DEL ORGANO DE ADMINISTRACION",
      "",
      "En {{ciudad_emision}}, a {{fecha_cierre}}, se deja constancia de la decision conjunta adoptada por los administradores de {{denominacion_social}} bajo el modo de actuacion {{modo_adopcion}}.",
      "",
      "ADMINISTRADORES INTERVINIENTES",
      legalListBlockFor("administradores_intervinientes"),
      "",
      "REGLA DE ACTUACION",
      "{{regla_actuacion}}",
      "",
      "CONDICION DE ADOPCION",
      "{{condicion_adopcion}}",
      "",
      "DECISION",
      "{{texto_decision}}",
      "",
      "{{#if conflictos_texto}}CONFLICTOS Y ABSTENCIONES\n{{conflictos_texto}}{{/if}}",
      "{{#if expediente_hash}}Hash del expediente electronico: {{expediente_hash}}{{/if}}",
      "{{#if firma_qes_ref}}Referencia de firma: {{firma_qes_ref}}{{/if}}",
    ].join("\n"),
    capa2_variables: [
      ...commonEntityVariables,
      { variable: "agreement_id", fuente: "EXPEDIENTE", condicion: "OBLIGATORIO" },
      { variable: "modo_adopcion", fuente: "EXPEDIENTE", condicion: "OBLIGATORIO" },
      { variable: "administradores_intervinientes", fuente: "EXPEDIENTE", condicion: "OBLIGATORIO" },
      { variable: "regla_actuacion", fuente: "MOTOR", condicion: "OBLIGATORIO" },
      { variable: "condicion_adopcion", fuente: "MOTOR", condicion: "OBLIGATORIO" },
      { variable: "texto_decision", fuente: "USUARIO", condicion: "OBLIGATORIO" },
    ],
    capa3_editables: [
      { campo: "agreement_id", obligatoriedad: "OBLIGATORIO", descripcion: "Identificador canonico Agreement 360." },
      { campo: "modo_adopcion", obligatoriedad: "OBLIGATORIO", descripcion: "Modo esperado: CO_APROBACION." },
      ...adminJointFields,
    ],
  }),
  fixture({
    id: "legal-fixture-acta-organo-admin-solidario-es",
    tipo: "ACTA_ORGANO_ADMIN",
    adoption_mode: "SOLIDARIO",
    organo_tipo: "ADMIN",
    referencia_legal: "Regimen de administracion solidaria; LSC, estatutos y pactos aplicables",
    capa1_inmutable: [
      "ACTA DE DECISION DE ADMINISTRADOR SOLIDARIO",
      "",
      "En {{ciudad_emision}}, a {{fecha}}, D./D.a {{administrador_actuante}}, en su condicion de administrador solidario de {{denominacion_social}}, documenta la siguiente decision o actuacion dentro del ambito de sus facultades.",
      "",
      "FACULTAD DE ACTUACION",
      "{{facultad_actuacion}}",
      "",
      "DECISION",
      "{{texto_decision}}",
      "",
      "{{#if comunicaciones_texto}}COMUNICACIONES\n{{comunicaciones_texto}}{{/if}}",
      "{{#if conflictos_texto}}CONFLICTOS\n{{conflictos_texto}}{{/if}}",
      "{{#if expediente_hash}}Hash del expediente electronico: {{expediente_hash}}{{/if}}",
      "{{#if firma_qes_ref}}Referencia de firma: {{firma_qes_ref}}{{/if}}",
    ].join("\n"),
    capa2_variables: [
      ...commonEntityVariables,
      { variable: "agreement_id", fuente: "EXPEDIENTE", condicion: "OBLIGATORIO" },
      { variable: "modo_adopcion", fuente: "EXPEDIENTE", condicion: "OBLIGATORIO" },
      { variable: "administrador_actuante", fuente: "EXPEDIENTE", condicion: "OBLIGATORIO" },
      { variable: "facultad_actuacion", fuente: "MOTOR", condicion: "OBLIGATORIO" },
      { variable: "texto_decision", fuente: "USUARIO", condicion: "OBLIGATORIO" },
    ],
    capa3_editables: [
      { campo: "agreement_id", obligatoriedad: "OBLIGATORIO", descripcion: "Identificador canonico Agreement 360." },
      { campo: "modo_adopcion", obligatoriedad: "OBLIGATORIO", descripcion: "Modo esperado: SOLIDARIO." },
      ...adminSolidaryFields,
    ],
  }),
  fixture({
    id: "legal-fixture-certificacion-es",
    tipo: "CERTIFICACION",
    capa1_inmutable: [
      "CERTIFICACION DE ACUERDOS",
      "",
      "D./D.a {{nombre_certificante}}, en calidad de {{cargo_certificante}} del organo de administracion de {{denominacion_social}}, certifica:",
      "",
      "Que en la reunion celebrada el dia {{fecha}} se adoptaron los siguientes acuerdos:",
      "",
      "{{transcripcion_acuerdos}}",
      "",
      "Y para que asi conste, se expide la presente certificacion en {{ciudad_emision}}, a {{fecha_emision}}.",
    ].join("\n"),
    capa2_variables: [
      ...commonEntityVariables,
      { variable: "nombre_certificante", fuente: "ORGANO", condicion: "OBLIGATORIO" },
      { variable: "cargo_certificante", fuente: "ORGANO", condicion: "OBLIGATORIO" },
      { variable: "fecha", fuente: "REUNION", condicion: "OBLIGATORIO" },
      { variable: "transcripcion_acuerdos", fuente: "EXPEDIENTE", condicion: "OBLIGATORIO" },
    ],
    capa3_editables: [
      { campo: "nombre_certificante", obligatoriedad: "OBLIGATORIO", descripcion: "Nombre de quien expide la certificacion." },
      { campo: "cargo_certificante", obligatoriedad: "OBLIGATORIO", descripcion: "Cargo con el que certifica." },
      { campo: "ciudad_emision", obligatoriedad: "OBLIGATORIO", descripcion: "Ciudad de emision de la certificacion." },
      { campo: "fecha_emision", obligatoriedad: "OBLIGATORIO", descripcion: "Fecha de emision de la certificacion." },
      { campo: "transcripcion_acuerdos", obligatoriedad: "OBLIGATORIO", descripcion: "Transcripcion literal de los acuerdos certificados." },
    ],
  }),
  fixture({
    id: "legal-fixture-informe-preceptivo-es",
    tipo: "INFORME_PRECEPTIVO",
    referencia_legal: "Informe PRE segun materia, ley, estatutos y pactos aplicables",
    capa1_inmutable: [
      "INFORME PRECEPTIVO",
      "",
      "Sociedad: {{denominacion_social}}",
      "Organo: {{organo_nombre}}",
      "Materia: {{materia_acuerdo}}",
      "Fecha: {{fecha}}",
      "",
      "ALCANCE",
      "{{objeto_informe}}",
      "",
      "FUNDAMENTO",
      "{{fundamento_legal}}",
      "",
      "COMPROBACIONES",
      legalListBlockFor("comprobaciones"),
      "",
      "CONCLUSION",
      "{{conclusion_informe}}",
      "",
      "--- TRAZA PRE ---",
      "Resultado motor: {{resultado_gate}}",
      "Resumen evaluacion: {{resultado_evaluacion}}",
      "Snapshot reglas: {{snapshot_hash}}",
      "--- FIN TRAZA PRE ---",
    ].join("\n"),
    capa2_variables: [
      ...commonEntityVariables,
      { variable: "resultado_gate", fuente: "MOTOR", condicion: "RECOMENDADO" },
      { variable: "resultado_evaluacion", fuente: "MOTOR", condicion: "RECOMENDADO" },
      { variable: "snapshot_hash", fuente: "MOTOR", condicion: "RECOMENDADO" },
    ],
    capa3_editables: informePreFields,
  }),
  fixture({
    id: "legal-fixture-informe-documental-pre-es",
    tipo: "INFORME_DOCUMENTAL_PRE",
    referencia_legal: "Checklist documental PRE",
    capa1_inmutable: [
      "INFORME DOCUMENTAL PRE",
      "",
      "Sociedad: {{denominacion_social}}",
      "Expediente: {{expediente_ref}}",
      "Organo: {{organo_nombre}}",
      "Materia: {{materia_acuerdo}}",
      "Fecha de preparacion: {{fecha}}",
      "",
      "DOCUMENTACION REVISADA O DISPONIBLE",
      legalListBlockFor("documentacion"),
      "",
      "CONCLUSION DOCUMENTAL",
      "{{conclusion_documental}}",
      "",
      "{{#if canal_notificacion}}Canal previsto: {{canal_notificacion}}{{/if}}",
      "{{#if erds_delivery_ref}}Referencia ERDS: {{erds_delivery_ref}}{{/if}}",
      "",
      "--- TRAZA PRE ---",
      "Resultado motor: {{resultado_gate}}",
      "Snapshot reglas: {{snapshot_hash}}",
      "--- FIN TRAZA PRE ---",
    ].join("\n"),
    capa2_variables: [
      ...commonEntityVariables,
      { variable: "resultado_gate", fuente: "MOTOR", condicion: "RECOMENDADO" },
      { variable: "snapshot_hash", fuente: "MOTOR", condicion: "RECOMENDADO" },
    ],
    capa3_editables: [
      { campo: "expediente_ref", obligatoriedad: "OBLIGATORIO", descripcion: "Referencia del expediente PRE." },
      { campo: "organo_nombre", obligatoriedad: "RECOMENDADO", descripcion: "Organo societario competente o convocante." },
      { campo: "materia_acuerdo", obligatoriedad: "OBLIGATORIO", descripcion: "Materia o acuerdo al que se refiere el checklist." },
      { campo: "fecha", obligatoriedad: "OBLIGATORIO", descripcion: "Fecha de preparacion del informe documental." },
      { campo: "documentacion_texto", obligatoriedad: "OBLIGATORIO", descripcion: "Documentos revisados, disponibles o pendientes, uno por linea." },
      { campo: "conclusion_documental", obligatoriedad: "OBLIGATORIO", descripcion: "Conclusion documental PRE." },
      { campo: "canal_notificacion", obligatoriedad: "RECOMENDADO", descripcion: "Canal previsto de notificacion o publicacion." },
      { campo: "erds_delivery_ref", obligatoriedad: "RECOMENDADO", descripcion: "Referencia ERDS si existe." },
    ],
  }),
  fixture({
    id: "legal-fixture-documento-registral-es",
    tipo: "DOCUMENTO_REGISTRAL",
    referencia_legal: "Documento de tramitacion registral posterior al acuerdo",
    capa1_inmutable: [
      "DOCUMENTO REGISTRAL",
      "",
      "Sociedad: {{denominacion_social}}",
      "Acuerdo: {{materia_acuerdo}}",
      "Modo de adopcion: {{modo_adopcion}}",
      "Estado del acuerdo: {{estado_acuerdo}}",
      "",
      "INSTRUMENTO",
      "Instrumento requerido: {{instrumento_requerido}}",
      "Tipo de presentacion: {{tipo_presentacion}}",
      "{{#if datos_presentacion}}Datos de presentacion: {{datos_presentacion}}{{/if}}",
      "",
      "ACUERDO OBJETO DE TRAMITACION",
      "{{texto_decision}}",
      "",
      "DOCUMENTACION APORTADA",
      legalListBlockFor("documentacion"),
      "",
      "{{#if observaciones_registrales}}Observaciones registrales: {{observaciones_registrales}}{{/if}}",
      "",
      "--- TRAZA REGISTRAL ---",
      "Agreement ID: {{agreement_id}}",
      "Certificacion ID: {{certificacion_id}}",
      "Snapshot reglas: {{snapshot_hash}}",
      "--- FIN TRAZA REGISTRAL ---",
    ].join("\n"),
    capa2_variables: [
      ...commonEntityVariables,
      { variable: "agreement_id", fuente: "EXPEDIENTE", condicion: "OBLIGATORIO" },
      { variable: "snapshot_hash", fuente: "MOTOR", condicion: "RECOMENDADO" },
    ],
    capa3_editables: [
      { campo: "agreement_id", obligatoriedad: "OBLIGATORIO", descripcion: "Identificador canonico Agreement 360." },
      { campo: "materia_acuerdo", obligatoriedad: "OBLIGATORIO", descripcion: "Materia del acuerdo registrable." },
      { campo: "modo_adopcion", obligatoriedad: "OBLIGATORIO", descripcion: "Modo de adopcion del acuerdo." },
      { campo: "estado_acuerdo", obligatoriedad: "OBLIGATORIO", descripcion: "Estado operativo del acuerdo." },
      { campo: "instrumento_requerido", obligatoriedad: "OBLIGATORIO", descripcion: "Instrumento o documento requerido para el Registro." },
      { campo: "tipo_presentacion", obligatoriedad: "OBLIGATORIO", descripcion: "Tipo/canal de presentacion registral." },
      { campo: "texto_decision", obligatoriedad: "OBLIGATORIO", descripcion: "Texto del acuerdo objeto de tramitacion." },
      ...registralFields,
    ],
  }),
  fixture({
    id: "legal-fixture-subsanacion-registral-es",
    tipo: "SUBSANACION_REGISTRAL",
    referencia_legal: "Respuesta limitada a defecto o requerimiento registral",
    capa1_inmutable: [
      "RESPUESTA DE SUBSANACION REGISTRAL",
      "",
      "Sociedad: {{denominacion_social}}",
      "Acuerdo: {{materia_acuerdo}}",
      "Expediente registral: {{expediente_registral_ref}}",
      "",
      "ANTECEDENTES",
      "Con fecha {{fecha_requerimiento}}, el Registro solicito subsanacion en relacion con el expediente indicado.",
      "",
      "MOTIVO DE LA SUBSANACION",
      "{{motivo_subsanacion}}",
      "",
      "RESPUESTA",
      "{{respuesta_subsanacion}}",
      "",
      "DOCUMENTOS APORTADOS",
      legalListBlockFor("documentacion"),
      "",
      "La presente respuesta se limita a aclarar, completar o subsanar los extremos requeridos por el Registro, sin alterar el contenido esencial del acuerdo adoptado salvo que conste nuevo acuerdo societario habilitante.",
      "",
      "--- TRAZA REGISTRAL ---",
      "Agreement ID: {{agreement_id}}",
      "Documento registral previo: {{documento_registral_ref}}",
      "Estado tramite: {{estado_tramite}}",
      "{{#if tsq_token}}Sello de tiempo: {{tsq_token}}{{/if}}",
      "--- FIN TRAZA REGISTRAL ---",
    ].join("\n"),
    capa2_variables: [
      ...commonEntityVariables,
      { variable: "agreement_id", fuente: "EXPEDIENTE", condicion: "OBLIGATORIO" },
      { variable: "estado_tramite", fuente: "EXPEDIENTE", condicion: "RECOMENDADO" },
    ],
    capa3_editables: [
      { campo: "agreement_id", obligatoriedad: "OBLIGATORIO", descripcion: "Identificador canonico Agreement 360." },
      { campo: "materia_acuerdo", obligatoriedad: "OBLIGATORIO", descripcion: "Materia del acuerdo subsanado." },
      { campo: "expediente_registral_ref", obligatoriedad: "OBLIGATORIO", descripcion: "Referencia del expediente o asiento registral." },
      { campo: "fecha_requerimiento", obligatoriedad: "OBLIGATORIO", descripcion: "Fecha del requerimiento registral." },
      { campo: "motivo_subsanacion", obligatoriedad: "OBLIGATORIO", descripcion: "Defecto o motivo de la subsanacion." },
      { campo: "respuesta_subsanacion", obligatoriedad: "OBLIGATORIO", descripcion: "Respuesta o aclaracion que se presenta." },
      ...registralFields,
      { campo: "documento_registral_ref", obligatoriedad: "RECOMENDADO", descripcion: "Documento registral previo que se subsana." },
      { campo: "estado_tramite", obligatoriedad: "RECOMENDADO", descripcion: "Estado del tramite tras la subsanacion." },
    ],
  }),
];

export function withLegalTeamTemplateFixtures(plantillas: PlantillaProtegidaRow[]) {
  const existingIds = new Set(plantillas.map((plantilla) => plantilla.id));
  return [
    ...plantillas,
    ...LEGAL_TEAM_TEMPLATE_FIXTURES.filter((fixtureRow) => !existingIds.has(fixtureRow.id)),
  ];
}
