import type { PlantillaProtegidaRow } from "@/hooks/usePlantillasProtegidas";
import { legalListBlockFor } from "./legal-template-normalizer";

const CREATED_AT = "2026-04-28T00:00:00.000Z";
const TENANT_ID = "local-legal-fixture";

type FixturePatch = Pick<
  PlantillaProtegidaRow,
  "id" | "tipo" | "capa1_inmutable" | "capa2_variables" | "capa3_editables"
> &
  Partial<PlantillaProtegidaRow>;

function fixture(patch: FixturePatch): PlantillaProtegidaRow {
  return {
    id: patch.id,
    tenant_id: patch.tenant_id ?? TENANT_ID,
    tipo: patch.tipo,
    materia: patch.materia ?? null,
    jurisdiccion: patch.jurisdiccion ?? "ES",
    version: patch.version ?? "LEGAL-FIXTURE-2026-04-28",
    estado: patch.estado ?? "ACTIVA",
    aprobada_por: null,
    fecha_aprobacion: null,
    contenido_template: patch.contenido_template ?? null,
    capa1_inmutable: patch.capa1_inmutable,
    capa2_variables: patch.capa2_variables,
    capa3_editables: patch.capa3_editables,
    referencia_legal: patch.referencia_legal ?? "Equipo legal - cuadro de plantillas Word",
    notas_legal:
      patch.notas_legal ??
      "Fixture local no persistido. Usar solo durante freeze Supabase hasta cargar plantilla aprobada.", // ITEM-073
    variables: patch.variables ?? [],
    protecciones: patch.protecciones ?? { source: "legal-team-fixture", persisted: false },
    snapshot_rule_pack_required: patch.snapshot_rule_pack_required ?? true,
    adoption_mode: patch.adoption_mode ?? null,
    organo_tipo: patch.organo_tipo ?? null,
    contrato_variables_version: patch.contrato_variables_version ?? "variables-plantillas-v1.1",
    created_at: patch.created_at ?? CREATED_AT,
    materia_acuerdo: patch.materia_acuerdo ?? null,
    approval_checklist: patch.approval_checklist ?? [
      { check: "Validación legal antes de carga en Supabase", passed: false }, // ITEM-073
    ],
    version_history: patch.version_history ?? [],
  };
}

const commonEntityVariables = [
  { variable: "denominacion_social", fuente: "ENTIDAD", condicion: "OBLIGATORIO" },
  { variable: "cif", fuente: "ENTIDAD", condicion: "RECOMENDADO" },
  { variable: "domicilio_social", fuente: "ENTIDAD", condicion: "RECOMENDADO" },
  { variable: "registro_mercantil", fuente: "ENTIDAD", condicion: "RECOMENDADO" },
];

// ITEM-073: ortografía española correcta restituida en descripciones (UTF-8).
const convocatoriaFields = [
  { campo: "lugar", obligatoriedad: "OBLIGATORIO", descripcion: "Lugar de celebración de la reunión o junta." },
  { campo: "fecha_primera_convocatoria", obligatoriedad: "OBLIGATORIO", descripcion: "Fecha de primera convocatoria." },
  { campo: "hora_primera_convocatoria", obligatoriedad: "OBLIGATORIO", descripcion: "Hora de primera convocatoria." },
  { campo: "fecha_segunda_convocatoria", obligatoriedad: "RECOMENDADO", descripcion: "Fecha de segunda convocatoria, si procede." },
  { campo: "orden_dia_texto", obligatoriedad: "OBLIGATORIO", descripcion: "Orden del día, un punto por línea." },
  { campo: "firma_organo_administracion", obligatoriedad: "RECOMENDADO", descripcion: "Firmante o cargo convocante." },
];

// ITEM-073: ortografía española correcta restituida en descripciones (UTF-8).
const actaFields = [
  { campo: "ciudad_emision", obligatoriedad: "OBLIGATORIO", descripcion: "Ciudad de emisión del acta." },
  { campo: "lugar", obligatoriedad: "OBLIGATORIO", descripcion: "Lugar de celebración." },
  { campo: "hora_inicio", obligatoriedad: "OBLIGATORIO", descripcion: "Hora de inicio." },
  { campo: "hora_fin", obligatoriedad: "RECOMENDADO", descripcion: "Hora de cierre." },
  { campo: "orden_dia_texto", obligatoriedad: "OBLIGATORIO", descripcion: "Orden del día tratado, un punto por línea." },
  { campo: "acuerdos_texto", obligatoriedad: "OBLIGATORIO", descripcion: "Acuerdos adoptados, uno por línea." },
];

// ITEM-073: ortografía española correcta restituida en descripciones (UTF-8).
const unipersonalFields = [
  { campo: "ciudad_emision", obligatoriedad: "OBLIGATORIO", descripcion: "Ciudad de emisión de la decisión." },
  { campo: "fecha", obligatoriedad: "OBLIGATORIO", descripcion: "Fecha de adopción de la decisión." },
  { campo: "identidad_decisor", obligatoriedad: "OBLIGATORIO", descripcion: "Nombre del socio único o administrador único." },
  { campo: "nif_decisor", obligatoriedad: "RECOMENDADO", descripcion: "NIF/NIE del decisor, si debe constar." },
  { campo: "texto_decision", obligatoriedad: "OBLIGATORIO", descripcion: "Texto literal de la decisión adoptada." },
  { campo: "firma_qes_ref", obligatoriedad: "RECOMENDADO", descripcion: "Referencia de firma QES o firma manuscrita." },
];

// ITEM-073: ortografía española correcta restituida en descripciones (UTF-8).
const adminJointFields = [
  { campo: "ciudad_emision", obligatoriedad: "OBLIGATORIO", descripcion: "Ciudad de cierre del acuerdo." },
  { campo: "fecha_cierre", obligatoriedad: "OBLIGATORIO", descripcion: "Fecha de cierre del expediente de decisión conjunta." },
  { campo: "administradores_intervinientes_texto", obligatoriedad: "OBLIGATORIO", descripcion: "Administradores que intervienen, uno por línea, con cargo y sentido de decisión." },
  { campo: "regla_actuacion", obligatoriedad: "OBLIGATORIO", descripcion: "Regla estatutaria o pactada de actuación mancomunada." },
  { campo: "condicion_adopcion", obligatoriedad: "OBLIGATORIO", descripcion: "Condición evaluada por el motor para considerar adoptada la decisión." },
  { campo: "texto_decision", obligatoriedad: "OBLIGATORIO", descripcion: "Texto literal de la decisión adoptada." },
  { campo: "conflictos_texto", obligatoriedad: "RECOMENDADO", descripcion: "Conflictos declarados, abstenciones o manifestación de inexistencia." },
  { campo: "expediente_hash", obligatoriedad: "RECOMENDADO", descripcion: "Hash o identificador de integridad del expediente electrónico." },
  { campo: "firma_qes_ref", obligatoriedad: "RECOMENDADO", descripcion: "Referencia QES/TSQ del expediente." },
];

// ITEM-073: ortografía española correcta restituida en descripciones (UTF-8).
const adminSolidaryFields = [
  { campo: "ciudad_emision", obligatoriedad: "OBLIGATORIO", descripcion: "Ciudad de emisión de la decisión." },
  { campo: "fecha", obligatoriedad: "OBLIGATORIO", descripcion: "Fecha de adopción de la decisión." },
  { campo: "administrador_actuante", obligatoriedad: "OBLIGATORIO", descripcion: "Administrador solidario que adopta o ejecuta la decisión." },
  { campo: "facultad_actuacion", obligatoriedad: "OBLIGATORIO", descripcion: "Facultad estatutaria, delegada o legal que habilita la actuación." },
  { campo: "texto_decision", obligatoriedad: "OBLIGATORIO", descripcion: "Texto literal de la decisión o actuación documentada." },
  { campo: "comunicaciones_texto", obligatoriedad: "RECOMENDADO", descripcion: "Comunicaciones al resto de administradores o manifestación de no exigibilidad." },
  { campo: "conflictos_texto", obligatoriedad: "RECOMENDADO", descripcion: "Conflictos declarados, abstenciones o manifestación de inexistencia." },
  { campo: "expediente_hash", obligatoriedad: "RECOMENDADO", descripcion: "Hash o identificador de integridad del expediente electrónico." },
  { campo: "firma_qes_ref", obligatoriedad: "RECOMENDADO", descripcion: "Referencia QES/TSQ del expediente." },
];

// ITEM-073: ortografía española correcta restituida en descripciones (UTF-8).
const informePreFields = [
  { campo: "materia_acuerdo", obligatoriedad: "OBLIGATORIO", descripcion: "Materia o acuerdo al que se refiere el informe." },
  { campo: "objeto_informe", obligatoriedad: "OBLIGATORIO", descripcion: "Objeto y alcance del informe preceptivo." },
  { campo: "fundamento_legal", obligatoriedad: "OBLIGATORIO", descripcion: "Base legal, estatutaria o pactada aplicable." },
  { campo: "comprobaciones_texto", obligatoriedad: "OBLIGATORIO", descripcion: "Comprobaciones realizadas, una por línea." },
  { campo: "conclusion_informe", obligatoriedad: "OBLIGATORIO", descripcion: "Conclusión del informe y advertencias." },
];

// ITEM-073: ortografía española correcta restituida en descripciones (UTF-8).
const registralFields = [
  { campo: "certificacion_id", obligatoriedad: "RECOMENDADO", descripcion: "Identificador de certificación base, si existe." },
  { campo: "documentacion_texto", obligatoriedad: "OBLIGATORIO", descripcion: "Documentos que se aportan o subsanan, uno por línea." },
  { campo: "datos_presentacion", obligatoriedad: "RECOMENDADO", descripcion: "Datos de presentación registral, asiento o referencia." },
  { campo: "observaciones_registrales", obligatoriedad: "RECOMENDADO", descripcion: "Observaciones para notaría, registro o publicación." },
];

export const LEGAL_TEAM_TEMPLATE_FIXTURES: PlantillaProtegidaRow[] = [
  fixture({
    id: "legal-fixture-convocatoria-junta-es",
    tipo: "CONVOCATORIA",
    organo_tipo: "JUNTA",
    capa1_inmutable: [
      "CONVOCATORIA DE JUNTA GENERAL",
      "",
      "Por la presente se convoca a los socios de {{denominacion_social}} a la Junta General {{tipo_junta}} que se celebrará en {{lugar}}, el día {{fecha_primera_convocatoria}} a las {{hora_primera_convocatoria}}{{#if fecha_segunda_convocatoria}}, y, en su caso, en segunda convocatoria el día {{fecha_segunda_convocatoria}} a la misma hora y lugar{{/if}}, con el siguiente orden del día:",
      "",
      legalListBlockFor("orden_dia"),
      "",
      "{{#if derecho_informacion}}Derecho de información: {{derecho_informacion}}{{/if}}",
      "",
      "{{firma_organo_administracion}}",
    ].join("\n"),
    capa2_variables: [
      ...commonEntityVariables,
      { variable: "tipo_junta", fuente: "USUARIO", condicion: "OBLIGATORIO" },
      { variable: "lugar", fuente: "USUARIO", condicion: "OBLIGATORIO" },
      { variable: "fecha_primera_convocatoria", fuente: "USUARIO", condicion: "OBLIGATORIO" },
      { variable: "hora_primera_convocatoria", fuente: "USUARIO", condicion: "OBLIGATORIO" },
      { variable: "orden_dia", fuente: "USUARIO", condicion: "OBLIGATORIO" },
    ],
    capa3_editables: [
      { campo: "tipo_junta", obligatoriedad: "OBLIGATORIO", descripcion: "Tipo de Junta: ordinaria, extraordinaria o mixta." },
      ...convocatoriaFields,
      { campo: "derecho_informacion", obligatoriedad: "RECOMENDADO", descripcion: "Texto de derecho de información si la materia lo exige." },
    ],
  }),
  fixture({
    id: "legal-fixture-convocatoria-consejo-es",
    tipo: "CONVOCATORIA",
    organo_tipo: "CONSEJO",
    capa1_inmutable: [
      "CONVOCATORIA DEL CONSEJO DE ADMINISTRACIÓN",
      "",
      "Por la presente se convoca a los miembros del Consejo de Administración de {{denominacion_social}} a la reunión que se celebrará en {{lugar}}, el día {{fecha_primera_convocatoria}} a las {{hora_primera_convocatoria}}, con el siguiente orden del día:",
      "",
      legalListBlockFor("orden_dia"),
      "",
      "{{firma_organo_administracion}}",
    ].join("\n"),
    capa2_variables: [
      ...commonEntityVariables,
      { variable: "lugar", fuente: "USUARIO", condicion: "OBLIGATORIO" },
      { variable: "fecha_primera_convocatoria", fuente: "USUARIO", condicion: "OBLIGATORIO" },
      { variable: "hora_primera_convocatoria", fuente: "USUARIO", condicion: "OBLIGATORIO" },
      { variable: "orden_dia", fuente: "USUARIO", condicion: "OBLIGATORIO" },
    ],
    capa3_editables: convocatoriaFields,
  }),
  fixture({
    id: "legal-fixture-acta-junta-es",
    tipo: "ACTA_SESION",
    organo_tipo: "JUNTA",
    capa1_inmutable: [
      "{{#if acta_rrm_texto_completo}}",
      "{{acta_rrm_texto_completo}}",
      "",
      "HASH CANÓNICO DEL ACTA",
      "{{canonical_minutes_hash}}",
      "{{else}}",
      "ACTA DE JUNTA GENERAL",
      "",
      "En {{ciudad_emision}}, a {{fecha_junta}}, siendo las {{hora_inicio}}, se reúne la Junta General {{tipo_junta}} de {{denominacion_social}}, en {{lugar}}, bajo la presidencia de {{presidente}} y actuando como secretario {{secretario}}.",
      "",
      "Porcentaje de capital presente o representado: {{porcentaje_capital_presente}}.",
      "",
      "ORDEN DEL DÍA",
      legalListBlockFor("orden_dia"),
      "",
      "ACUERDOS",
      legalListBlockFor("acuerdos"),
      "",
      "{{#if hora_fin}}Sin más asuntos que tratar, se levanta la sesión a las {{hora_fin}}.{{/if}}",
      "{{/if}}",
    ].join("\n"),
    capa2_variables: [
      ...commonEntityVariables,
      { variable: "fecha_junta", fuente: "REUNION", condicion: "OBLIGATORIO" },
      { variable: "presidente", fuente: "ORGANO", condicion: "OBLIGATORIO" },
      { variable: "secretario", fuente: "ORGANO", condicion: "OBLIGATORIO" },
      { variable: "porcentaje_capital_presente", fuente: "REUNION", condicion: "OBLIGATORIO" },
    ],
    capa3_editables: [
      { campo: "tipo_junta", obligatoriedad: "OBLIGATORIO", descripcion: "Tipo de Junta celebrada." },
      ...actaFields,
      { campo: "porcentaje_capital_presente", obligatoriedad: "OBLIGATORIO", descripcion: "Porcentaje de capital presente o representado." },
    ],
  }),
  fixture({
    id: "legal-fixture-acta-consejo-es",
    tipo: "ACTA_SESION",
    organo_tipo: "CONSEJO",
    capa1_inmutable: [
      "{{#if acta_rrm_texto_completo}}",
      "{{acta_rrm_texto_completo}}",
      "",
      "HASH CANÓNICO DEL ACTA",
      "{{canonical_minutes_hash}}",
      "{{else}}",
      "ACTA DEL CONSEJO DE ADMINISTRACIÓN",
      "",
      "En {{ciudad_emision}}, a {{fecha}}, siendo las {{hora_inicio}}, se reúne el Consejo de Administración de {{denominacion_social}}, en {{lugar}}, bajo la presidencia de {{presidente}} y actuando como secretario {{secretario}}.",
      "",
      "Asisten los siguientes consejeros:",
      legalListBlockFor("miembros_presentes"),
      "",
      "ORDEN DEL DÍA",
      legalListBlockFor("orden_dia"),
      "",
      "ACUERDOS",
      legalListBlockFor("acuerdos"),
      "",
      "{{#if hora_fin}}Sin más asuntos que tratar, se levanta la sesión a las {{hora_fin}}.{{/if}}",
      "{{/if}}",
    ].join("\n"),
    capa2_variables: [
      ...commonEntityVariables,
      { variable: "fecha", fuente: "REUNION", condicion: "OBLIGATORIO" },
      { variable: "presidente", fuente: "ORGANO", condicion: "OBLIGATORIO" },
      { variable: "secretario", fuente: "ORGANO", condicion: "OBLIGATORIO" },
    ],
    capa3_editables: [
      ...actaFields,
      { campo: "miembros_presentes_texto", obligatoriedad: "OBLIGATORIO", descripcion: "Consejeros asistentes, uno por línea." },
    ],
  }),
  fixture({
    id: "legal-fixture-acta-consignacion-socio-unico-es",
    tipo: "ACTA_CONSIGNACION",
    adoption_mode: "UNIPERSONAL_SOCIO",
    referencia_legal: "Art. 15 LSC",
    capa1_inmutable: [
      "DECISIÓN DEL SOCIO ÚNICO",
      "",
      "En {{ciudad_emision}}, a {{fecha}}, D./D.ª {{identidad_decisor}}{{#if nif_decisor}}, con NIF {{nif_decisor}}{{/if}}, como socio único de {{denominacion_social}}, en ejercicio de las competencias que le atribuye el artículo 15 de la Ley de Sociedades de Capital, adopta la siguiente decisión:",
      "",
      "{{texto_decision}}",
      "",
      "La decisión se consignará en el Libro de Actas de la sociedad, sin perjuicio de su elevación a público o inscripción cuando proceda.",
      "",
      "{{#if firma_qes_ref}}Referencia de firma: {{firma_qes_ref}}{{/if}}",
    ].join("\n"),
    capa2_variables: [
      ...commonEntityVariables,
      { variable: "fecha", fuente: "EXPEDIENTE", condicion: "OBLIGATORIO" },
      { variable: "texto_decision", fuente: "USUARIO", condicion: "OBLIGATORIO" },
    ],
    capa3_editables: unipersonalFields,
  }),
  fixture({
    id: "legal-fixture-acta-consignacion-admin-unico-es",
    tipo: "ACTA_CONSIGNACION",
    adoption_mode: "UNIPERSONAL_ADMIN",
    referencia_legal: "Órgano de administración unipersonal",
    capa1_inmutable: [
      "DECISIÓN DEL ADMINISTRADOR ÚNICO",
      "",
      "En {{ciudad_emision}}, a {{fecha}}, D./D.ª {{identidad_decisor}}{{#if nif_decisor}}, con NIF {{nif_decisor}}{{/if}}, como administrador único de {{denominacion_social}}, adopta en materias de su competencia la siguiente decisión:",
      "",
      "{{texto_decision}}",
      "",
      "La decisión se incorpora al expediente societario y, cuando proceda, se consignará en el Libro de Actas o se elevará a público para producir sus efectos.",
      "",
      "{{#if firma_qes_ref}}Referencia de firma: {{firma_qes_ref}}{{/if}}",
    ].join("\n"),
    capa2_variables: [
      ...commonEntityVariables,
      { variable: "fecha", fuente: "EXPEDIENTE", condicion: "OBLIGATORIO" },
      { variable: "texto_decision", fuente: "USUARIO", condicion: "OBLIGATORIO" },
    ],
    capa3_editables: unipersonalFields,
  }),
  fixture({
    id: "legal-fixture-acta-acuerdo-escrito-sin-sesion-es",
    tipo: "ACTA_ACUERDO_ESCRITO",
    adoption_mode: "NO_SESSION",
    referencia_legal: "Art. 100 RRM / art. 248.2 LSC",
    capa1_inmutable: [
      "ACTA DE ACUERDO ESCRITO SIN SESIÓN",
      "",
      "En {{ciudad_emision}}, a {{fecha_cierre}}, se deja constancia de que el expediente de adopción de acuerdo sin celebración de sesión se ha tramitado bajo la modalidad {{tipo_proceso}}.",
      "",
      "PROPUESTA",
      "{{propuesta_texto}}",
      "",
      "RELACIÓN DE RESPUESTAS",
      legalListBlockFor("relacion_respuestas"),
      "",
      "CONDICIÓN DE ADOPCIÓN",
      "{{condicion_adopcion}}",
      "",
      "ACUERDO",
      "{{texto_decision}}",
      "",
      "{{#if expediente_hash}}Hash del expediente electrónico: {{expediente_hash}}{{/if}}",
      "{{#if firma_qes_ref}}Referencia de firma: {{firma_qes_ref}}{{/if}}",
    ].join("\n"),
    capa2_variables: [
      ...commonEntityVariables,
      { variable: "tipo_proceso", fuente: "EXPEDIENTE", condicion: "OBLIGATORIO" },
      { variable: "relacion_respuestas", fuente: "EXPEDIENTE", condicion: "OBLIGATORIO" },
      { variable: "condicion_adopcion", fuente: "MOTOR", condicion: "OBLIGATORIO" },
    ],
    capa3_editables: [
      { campo: "ciudad_emision", obligatoriedad: "OBLIGATORIO", descripcion: "Ciudad de cierre del expediente escrito." },
      { campo: "fecha_cierre", obligatoriedad: "OBLIGATORIO", descripcion: "Fecha de cierre del expediente sin sesión." },
      { campo: "tipo_proceso", obligatoriedad: "OBLIGATORIO", descripcion: "UNANIMIDAD_CAPITAL_SL, CIRCULACION_CONSEJO u otra modalidad aplicable." },
      { campo: "propuesta_texto", obligatoriedad: "OBLIGATORIO", descripcion: "Texto de la propuesta circulada." },
      { campo: "relacion_respuestas_texto", obligatoriedad: "OBLIGATORIO", descripcion: "Respuestas recibidas, una por línea, con sentido y fecha si procede." },
      { campo: "condicion_adopcion", obligatoriedad: "OBLIGATORIO", descripcion: "Condición evaluada por el motor para considerar adoptado el acuerdo." },
      { campo: "texto_decision", obligatoriedad: "OBLIGATORIO", descripcion: "Texto literal del acuerdo adoptado." },
      { campo: "expediente_hash", obligatoriedad: "RECOMENDADO", descripcion: "Hash o identificador de integridad del expediente electrónico." },
      { campo: "firma_qes_ref", obligatoriedad: "RECOMENDADO", descripcion: "Referencia QES/TSQ del expediente." },
    ],
  }),
  fixture({
    id: "legal-fixture-acta-decision-conjunta-es",
    tipo: "ACTA_DECISION_CONJUNTA",
    adoption_mode: "CO_APROBACION",
    organo_tipo: "ADMIN",
    referencia_legal: "Régimen de administración mancomunada; LSC, estatutos y pactos aplicables",
    capa1_inmutable: [
      "ACTA DE DECISIÓN CONJUNTA DEL ÓRGANO DE ADMINISTRACIÓN",
      "",
      "En {{ciudad_emision}}, a {{fecha_cierre}}, se deja constancia de la decisión conjunta adoptada por los administradores de {{denominacion_social}} bajo el modo de actuación {{modo_adopcion}}.",
      "",
      "ADMINISTRADORES INTERVINIENTES",
      legalListBlockFor("administradores_intervinientes"),
      "",
      "REGLA DE ACTUACIÓN",
      "{{regla_actuacion}}",
      "",
      "CONDICIÓN DE ADOPCIÓN",
      "{{condicion_adopcion}}",
      "",
      "DECISIÓN",
      "{{texto_decision}}",
      "",
      "{{#if conflictos_texto}}CONFLICTOS Y ABSTENCIONES\n{{conflictos_texto}}{{/if}}",
      "{{#if expediente_hash}}Hash del expediente electrónico: {{expediente_hash}}{{/if}}",
      "{{#if firma_qes_ref}}Referencia de firma: {{firma_qes_ref}}{{/if}}",
    ].join("\n"),
    capa2_variables: [
      ...commonEntityVariables,
      { variable: "agreement_id", fuente: "EXPEDIENTE", condicion: "OBLIGATORIO" },
      { variable: "modo_adopcion", fuente: "EXPEDIENTE", condicion: "OBLIGATORIO" },
      { variable: "administradores_intervinientes", fuente: "EXPEDIENTE", condicion: "OBLIGATORIO" },
      { variable: "regla_actuacion", fuente: "MOTOR", condicion: "OBLIGATORIO" },
      { variable: "condicion_adopcion", fuente: "MOTOR", condicion: "OBLIGATORIO" },
      { variable: "texto_decision", fuente: "USUARIO", condicion: "OBLIGATORIO" },
    ],
    capa3_editables: [
      { campo: "agreement_id", obligatoriedad: "OBLIGATORIO", descripcion: "Identificador canónico Agreement 360." },
      { campo: "modo_adopcion", obligatoriedad: "OBLIGATORIO", descripcion: "Modo esperado: CO_APROBACION." },
      ...adminJointFields,
    ],
  }),
  fixture({
    id: "legal-fixture-acta-organo-admin-solidario-es",
    tipo: "ACTA_ORGANO_ADMIN",
    adoption_mode: "SOLIDARIO",
    organo_tipo: "ADMIN",
    referencia_legal: "Régimen de administración solidaria; LSC, estatutos y pactos aplicables",
    capa1_inmutable: [
      "ACTA DE DECISIÓN DE ADMINISTRADOR SOLIDARIO",
      "",
      "En {{ciudad_emision}}, a {{fecha}}, D./D.ª {{administrador_actuante}}, en su condición de administrador solidario de {{denominacion_social}}, documenta la siguiente decisión o actuación dentro del ámbito de sus facultades.",
      "",
      "FACULTAD DE ACTUACIÓN",
      "{{facultad_actuacion}}",
      "",
      "DECISIÓN",
      "{{texto_decision}}",
      "",
      "{{#if comunicaciones_texto}}COMUNICACIONES\n{{comunicaciones_texto}}{{/if}}",
      "{{#if conflictos_texto}}CONFLICTOS\n{{conflictos_texto}}{{/if}}",
      "{{#if expediente_hash}}Hash del expediente electrónico: {{expediente_hash}}{{/if}}",
      "{{#if firma_qes_ref}}Referencia de firma: {{firma_qes_ref}}{{/if}}",
    ].join("\n"),
    capa2_variables: [
      ...commonEntityVariables,
      { variable: "agreement_id", fuente: "EXPEDIENTE", condicion: "OBLIGATORIO" },
      { variable: "modo_adopcion", fuente: "EXPEDIENTE", condicion: "OBLIGATORIO" },
      { variable: "administrador_actuante", fuente: "EXPEDIENTE", condicion: "OBLIGATORIO" },
      { variable: "facultad_actuacion", fuente: "MOTOR", condicion: "OBLIGATORIO" },
      { variable: "texto_decision", fuente: "USUARIO", condicion: "OBLIGATORIO" },
    ],
    capa3_editables: [
      { campo: "agreement_id", obligatoriedad: "OBLIGATORIO", descripcion: "Identificador canónico Agreement 360." },
      { campo: "modo_adopcion", obligatoriedad: "OBLIGATORIO", descripcion: "Modo esperado: SOLIDARIO." },
      ...adminSolidaryFields,
    ],
  }),
  fixture({
    id: "legal-fixture-certificacion-es",
    tipo: "CERTIFICACION",
    capa1_inmutable: [
      "CERTIFICACIÓN DE ACUERDOS",
      "",
      "D./D.ª {{nombre_certificante}}, en calidad de {{cargo_certificante}} del órgano de administración de {{denominacion_social}}, certifica:",
      "",
      "Que en la reunión celebrada el día {{fecha}} se adoptaron los siguientes acuerdos:",
      "",
      "{{transcripcion_acuerdos}}",
      "",
      "Y para que así conste, se expide la presente certificación en {{ciudad_emision}}, a {{fecha_emision}}.",
    ].join("\n"),
    capa2_variables: [
      ...commonEntityVariables,
      { variable: "nombre_certificante", fuente: "ORGANO", condicion: "OBLIGATORIO" },
      { variable: "cargo_certificante", fuente: "ORGANO", condicion: "OBLIGATORIO" },
      { variable: "fecha", fuente: "REUNION", condicion: "OBLIGATORIO" },
      { variable: "transcripcion_acuerdos", fuente: "EXPEDIENTE", condicion: "OBLIGATORIO" },
    ],
    capa3_editables: [
      { campo: "nombre_certificante", obligatoriedad: "OBLIGATORIO", descripcion: "Nombre de quien expide la certificación." },
      { campo: "cargo_certificante", obligatoriedad: "OBLIGATORIO", descripcion: "Cargo con el que certifica." },
      { campo: "ciudad_emision", obligatoriedad: "OBLIGATORIO", descripcion: "Ciudad de emisión de la certificación." },
      { campo: "fecha_emision", obligatoriedad: "OBLIGATORIO", descripcion: "Fecha de emisión de la certificación." },
      { campo: "transcripcion_acuerdos", obligatoriedad: "OBLIGATORIO", descripcion: "Transcripción literal de los acuerdos certificados." },
    ],
  }),
  fixture({
    id: "legal-fixture-informe-preceptivo-es",
    tipo: "INFORME_PRECEPTIVO",
    referencia_legal: "Informe PRE según materia, ley, estatutos y pactos aplicables",
    capa1_inmutable: [
      "INFORME PRECEPTIVO",
      "",
      "Sociedad: {{denominacion_social}}",
      "Órgano: {{organo_nombre}}",
      "Materia: {{materia_acuerdo}}",
      "Fecha: {{fecha}}",
      "",
      "ALCANCE",
      "{{objeto_informe}}",
      "",
      "FUNDAMENTO",
      "{{fundamento_legal}}",
      "",
      "COMPROBACIONES",
      legalListBlockFor("comprobaciones"),
      "",
      "CONCLUSIÓN",
      "{{conclusion_informe}}",
      "",
      "--- TRAZA PRE ---",
      "Resultado motor: {{resultado_gate}}",
      "Resumen evaluación: {{resultado_evaluacion}}",
      "Snapshot reglas: {{snapshot_hash}}",
      "--- FIN TRAZA PRE ---",
    ].join("\n"),
    capa2_variables: [
      ...commonEntityVariables,
      { variable: "resultado_gate", fuente: "MOTOR", condicion: "RECOMENDADO" },
      { variable: "resultado_evaluacion", fuente: "MOTOR", condicion: "RECOMENDADO" },
      { variable: "snapshot_hash", fuente: "MOTOR", condicion: "RECOMENDADO" },
    ],
    capa3_editables: informePreFields,
  }),
  fixture({
    id: "legal-fixture-informe-documental-pre-es",
    tipo: "INFORME_DOCUMENTAL_PRE",
    referencia_legal: "Checklist documental PRE",
    capa1_inmutable: [
      "INFORME DOCUMENTAL PRE",
      "",
      "Sociedad: {{denominacion_social}}",
      "Expediente: {{expediente_ref}}",
      "Órgano: {{organo_nombre}}",
      "Materia: {{materia_acuerdo}}",
      "Fecha de preparación: {{fecha}}",
      "",
      "DOCUMENTACIÓN REVISADA O DISPONIBLE",
      legalListBlockFor("documentacion"),
      "",
      "CONCLUSIÓN DOCUMENTAL",
      "{{conclusion_documental}}",
      "",
      "{{#if canal_notificacion}}Canal previsto: {{canal_notificacion}}{{/if}}",
      "{{#if erds_delivery_ref}}Referencia ERDS: {{erds_delivery_ref}}{{/if}}",
      "",
      "--- TRAZA PRE ---",
      "Resultado motor: {{resultado_gate}}",
      "Snapshot reglas: {{snapshot_hash}}",
      "--- FIN TRAZA PRE ---",
    ].join("\n"),
    capa2_variables: [
      ...commonEntityVariables,
      { variable: "resultado_gate", fuente: "MOTOR", condicion: "RECOMENDADO" },
      { variable: "snapshot_hash", fuente: "MOTOR", condicion: "RECOMENDADO" },
    ],
    capa3_editables: [
      { campo: "expediente_ref", obligatoriedad: "OBLIGATORIO", descripcion: "Referencia del expediente PRE." },
      { campo: "organo_nombre", obligatoriedad: "RECOMENDADO", descripcion: "Órgano societario competente o convocante." },
      { campo: "materia_acuerdo", obligatoriedad: "OBLIGATORIO", descripcion: "Materia o acuerdo al que se refiere el checklist." },
      { campo: "fecha", obligatoriedad: "OBLIGATORIO", descripcion: "Fecha de preparación del informe documental." },
      { campo: "documentacion_texto", obligatoriedad: "OBLIGATORIO", descripcion: "Documentos revisados, disponibles o pendientes, uno por línea." },
      { campo: "conclusion_documental", obligatoriedad: "OBLIGATORIO", descripcion: "Conclusión documental PRE." },
      { campo: "canal_notificacion", obligatoriedad: "RECOMENDADO", descripcion: "Canal previsto de notificación o publicación." },
      { campo: "erds_delivery_ref", obligatoriedad: "RECOMENDADO", descripcion: "Referencia ERDS si existe." },
    ],
  }),
  fixture({
    id: "legal-fixture-documento-registral-es",
    tipo: "DOCUMENTO_REGISTRAL",
    referencia_legal: "Documento de tramitación registral posterior al acuerdo",
    capa1_inmutable: [
      "DOCUMENTO REGISTRAL",
      "",
      "Sociedad: {{denominacion_social}}",
      "Acuerdo: {{materia_acuerdo}}",
      "Modo de adopción: {{modo_adopcion}}",
      "Estado del acuerdo: {{estado_acuerdo}}",
      "",
      "INSTRUMENTO",
      "Instrumento requerido: {{instrumento_requerido}}",
      "Tipo de presentación: {{tipo_presentacion}}",
      "{{#if datos_presentacion}}Datos de presentación: {{datos_presentacion}}{{/if}}",
      "",
      "ACUERDO OBJETO DE TRAMITACIÓN",
      "{{texto_decision}}",
      "",
      "DOCUMENTACIÓN APORTADA",
      legalListBlockFor("documentacion"),
      "",
      "{{#if observaciones_registrales}}Observaciones registrales: {{observaciones_registrales}}{{/if}}",
      "",
      "--- TRAZA REGISTRAL ---",
      "Agreement ID: {{agreement_id}}",
      "Certificación ID: {{certificacion_id}}",
      "Snapshot reglas: {{snapshot_hash}}",
      "--- FIN TRAZA REGISTRAL ---",
    ].join("\n"),
    capa2_variables: [
      ...commonEntityVariables,
      { variable: "agreement_id", fuente: "EXPEDIENTE", condicion: "OBLIGATORIO" },
      { variable: "snapshot_hash", fuente: "MOTOR", condicion: "RECOMENDADO" },
    ],
    capa3_editables: [
      { campo: "agreement_id", obligatoriedad: "OBLIGATORIO", descripcion: "Identificador canónico Agreement 360." },
      { campo: "materia_acuerdo", obligatoriedad: "OBLIGATORIO", descripcion: "Materia del acuerdo registrable." },
      { campo: "modo_adopcion", obligatoriedad: "OBLIGATORIO", descripcion: "Modo de adopción del acuerdo." },
      { campo: "estado_acuerdo", obligatoriedad: "OBLIGATORIO", descripcion: "Estado operativo del acuerdo." },
      { campo: "instrumento_requerido", obligatoriedad: "OBLIGATORIO", descripcion: "Instrumento o documento requerido para el Registro." },
      { campo: "tipo_presentacion", obligatoriedad: "OBLIGATORIO", descripcion: "Tipo/canal de presentación registral." },
      { campo: "texto_decision", obligatoriedad: "OBLIGATORIO", descripcion: "Texto del acuerdo objeto de tramitación." },
      ...registralFields,
    ],
  }),
  fixture({
    id: "legal-fixture-subsanacion-registral-es",
    tipo: "SUBSANACION_REGISTRAL",
    referencia_legal: "Respuesta limitada a defecto o requerimiento registral",
    capa1_inmutable: [
      "RESPUESTA DE SUBSANACIÓN REGISTRAL",
      "",
      "Sociedad: {{denominacion_social}}",
      "Acuerdo: {{materia_acuerdo}}",
      "Expediente registral: {{expediente_registral_ref}}",
      "",
      "ANTECEDENTES",
      "Con fecha {{fecha_requerimiento}}, el Registro Mercantil solicitó subsanación en relación con el expediente indicado.",
      "",
      "MOTIVO DE LA SUBSANACIÓN",
      "{{motivo_subsanacion}}",
      "",
      "RESPUESTA",
      "{{respuesta_subsanacion}}",
      "",
      "DOCUMENTOS APORTADOS",
      legalListBlockFor("documentacion"),
      "",
      "La presente respuesta se limita a aclarar, completar o subsanar los extremos requeridos por el Registro Mercantil, sin alterar el contenido esencial del acuerdo adoptado salvo que conste nuevo acuerdo societario habilitante.",
      "",
      "--- TRAZA REGISTRAL ---",
      "Agreement ID: {{agreement_id}}",
      "Documento registral previo: {{documento_registral_ref}}",
      "Estado trámite: {{estado_tramite}}",
      "{{#if tsq_token}}Sello de tiempo: {{tsq_token}}{{/if}}",
      "--- FIN TRAZA REGISTRAL ---",
    ].join("\n"),
    capa2_variables: [
      ...commonEntityVariables,
      { variable: "agreement_id", fuente: "EXPEDIENTE", condicion: "OBLIGATORIO" },
      { variable: "estado_tramite", fuente: "EXPEDIENTE", condicion: "RECOMENDADO" },
    ],
    capa3_editables: [
      { campo: "agreement_id", obligatoriedad: "OBLIGATORIO", descripcion: "Identificador canónico Agreement 360." },
      { campo: "materia_acuerdo", obligatoriedad: "OBLIGATORIO", descripcion: "Materia del acuerdo subsanado." },
      { campo: "expediente_registral_ref", obligatoriedad: "OBLIGATORIO", descripcion: "Referencia del expediente o asiento registral." },
      { campo: "fecha_requerimiento", obligatoriedad: "OBLIGATORIO", descripcion: "Fecha del requerimiento registral." },
      { campo: "motivo_subsanacion", obligatoriedad: "OBLIGATORIO", descripcion: "Defecto o motivo de la subsanación." },
      { campo: "respuesta_subsanacion", obligatoriedad: "OBLIGATORIO", descripcion: "Respuesta o aclaración que se presenta." },
      ...registralFields,
      { campo: "documento_registral_ref", obligatoriedad: "RECOMENDADO", descripcion: "Documento registral previo que se subsana." },
      { campo: "estado_tramite", obligatoriedad: "RECOMENDADO", descripcion: "Estado del trámite tras la subsanación." },
    ],
  }),
];

export function withLegalTeamTemplateFixtures(plantillas: PlantillaProtegidaRow[]) {
  const existingIds = new Set(plantillas.map((plantilla) => plantilla.id));
  return [
    ...plantillas,
    ...LEGAL_TEAM_TEMPLATE_FIXTURES.filter((fixtureRow) => !existingIds.has(fixtureRow.id)),
  ];
}
