// GENERADO por scripts/garrigues/normativo/extract-catalogo.ts — NO EDITAR A MANO.
// Fuente: PDF del sistema normativo interno de Garrigues (material no versionado).
// Regenerar: bun run scripts/garrigues/normativo/extract-catalogo.ts --write

export type NormativoEntry = {
  policy_code: string;
  title: string;
  normative_tier: "POLITICA" | "NORMA" | "PROCEDIMIENTO" | "DOCUMENTO";
  edicion: string | null;
  effective_date: string | null;
  current_version: number;
  summary: string | null;
  content_outline: string[];
  source_file: string | null;
  provenance: "PDF_EXTRAIDO" | "CITADO_NO_INCORPORADO";
};

export const NORMATIVO_CATALOG: NormativoEntry[] = [
  {
    "policy_code": "PI-01",
    "title": "Política sobre aceptación de nuevos clientes y asuntos",
    "normative_tier": "POLITICA",
    "edicion": "Edición 1, octubre 2013",
    "effective_date": "2013-10-01",
    "current_version": 1,
    "summary": "Esta Política tiene como objeto desarrollar, a nivel de principios, los aspectos básicos que deben considerarse a la hora de decidir la aceptación o rechazo de todo nuevo cliente o de cualesquiera nuevos asuntos solicitados por clientes a los que el Despacho ya viene prestando servicios. Más concretamente, en esta Política se reproducen los principios básicos establecidos a tal efecto en el apartado 7.2 del “Manual de prevención del blanqueo de capitales y de la financiación del terrorismo del Grupo Garrigues”.",
    "content_outline": [
      "1. Objeto",
      "2. Normas para la aceptación de nuevos clientes y asuntos de aplicación general a todos los profesionales y encargos de Garrigues"
    ],
    "source_file": "PI-01. Política sobre aceptación de nuevos clientes y asuntos.pdf",
    "provenance": "PDF_EXTRAIDO"
  },
  {
    "policy_code": "PI-02",
    "title": "Política sobre conflicto de intereses, chequeo y resolución de los mismos",
    "normative_tier": "POLITICA",
    "edicion": "Edición 3, febrero 2024",
    "effective_date": "2024-02-01",
    "current_version": 3,
    "summary": "Esta Política tiene como objeto establecer los criterios aplicables y el procedimiento a seguir para asegurar que se realiza una adecuada identificación, chequeo y resolución de potenciales conflictos de intereses. El cumplimiento, por todos, de esta Política resulta esencial en un Despacho como el nuestro, dado que, por el gran número de clientes y la diversidad de profesionales responsables de los mismos, es muy probable la concurrencia de encargos que plantee un potencial conflicto de intereses, que debe ser detectado y solucionado con anterioridad a aceptar el trabajo profesional. Es muy importante que se efectúe la oportuna comprobación en todo caso, y que se haga de forma correcta, para evitar incurrir en la infracción de las normas legales, deontológicas y profesionales que amparan el secreto profesional, y asegurar la objetividad, ética y transparencia en el proceso de contratación de servicios entre el Despacho y los clientes, proveedores, Administración Pública y demás terceros.",
    "content_outline": [
      "1. Objeto",
      "2. Definición de las posibles situaciones de conflicto de intereses",
      "2.1. Conflictos de intereses en sentido estricto",
      "2.2. Conflictos de carácter comercial o de negocio",
      "3. Responsable del chequeo",
      "4. Fuentes de información para el chequeo",
      "5. Resolución de los conflictos",
      "6. Histórico de versiones",
      "7. Anexos"
    ],
    "source_file": "PI-02. Política sobre conflicto de intereses, chequeo y resolución de los mismos.pdf",
    "provenance": "PDF_EXTRAIDO"
  },
  {
    "policy_code": "PI-03",
    "title": "Política sobre honorarios profesionales y facturación",
    "normative_tier": "POLITICA",
    "edicion": "Edición 2, julio 2017",
    "effective_date": "2017-07-01",
    "current_version": 2,
    "summary": "Esta política tiene como objeto establecer los criterios y pautas de actuación aplicables en el despacho en materia de honorarios por la prestación de servicios profesionales a nuestros clientes, así como en relación con su facturación. En los asuntos de naturaleza litigiosa/procesal en los que se produzca una condena en costas a favor de nuestro cliente, se estará a lo establecido en la Política Interna PI-06, sobre facturación en la tasación de costas.",
    "content_outline": [
      "1. Objeto",
      "2. Libertad de fijación de honorarios",
      "2.1. Regla general",
      "2.2. 'Success fee'",
      "2.3. 'Cuota litis'",
      "2.4. Criterios orientativos de honorarios elaborados por los Colegios de abogados",
      "3. 'Billing rates' y desglose de trabajos efectuados y horas incurridas",
      "4. Facturación y cobro de honorarios",
      "4.1. Destinatario de la factura",
      "4.2. Contenido de la factura",
      "4.3. Cobro de honorarios"
    ],
    "source_file": "PI-03. Política sobre honorarios profesionales y facturación.pdf",
    "provenance": "PDF_EXTRAIDO"
  },
  {
    "policy_code": "PI-04",
    "title": "Política sobre provisiones de fondos (depósitos y anticipos) de clientes",
    "normative_tier": "POLITICA",
    "edicion": "Edición 1, octubre 2013",
    "effective_date": "2013-10-01",
    "current_version": 1,
    "summary": "Esta Política tiene como objeto analizar las distintas situaciones que pueden plantearse en relación con las provisiones de fondos recibidas de clientes y establecer los criterios de actuación que han de seguirse en cada caso en relación con la gestión de las mismas (a través de la información que proporciona SAP a los Socios, Counsels y Asociados Seniors/Principales del Despacho).",
    "content_outline": [
      "1. Objeto",
      "2. Depósitos de clientes",
      "2.1. Concepto e información disponible en SAP",
      "2.2. Criterios de actuación aplicables en relación con los depósitos de clientes",
      "3. Anticipos de clientes",
      "3.1. Concepto e información disponible en SAP",
      "3.2. Criterios de actuación aplicables en relación con los anticipos de clientes",
      "4. Ingresos pendientes de identificar",
      "4.1. Concepto e información disponible en SAP",
      "4.2. Criterios de actuación aplicables en relación con los ingresos pendientes de identificar",
      "5. Anexos"
    ],
    "source_file": "PI-04. Política sobre provisiones de fondos (depósitos y anticipos) de clientes.pdf",
    "provenance": "PDF_EXTRAIDO"
  },
  {
    "policy_code": "PI-05",
    "title": "Política sobre prohibición de aceptar cobros en efectivo",
    "normative_tier": "POLITICA",
    "edicion": "Edición 1, octubre 2013",
    "effective_date": "2013-10-01",
    "current_version": 1,
    "summary": "El 19 de noviembre de 2012, entró en vigor la Ley 7/2012, de 29 de octubre, de modificación de la normativa tributaria y presupuestaria y de adecuación de la normativa financiera para la intensificación de las actuaciones en la prevención y lucha contra el fraude. Dicha Ley ha establecido una limitación al uso de efectivo en el pago de operaciones, aunque éstas hayan sido concertadas con anterioridad a su entrada en vigor. En cumplimiento de la citada Ley, el Despacho ha decidido prohibir la aceptación de cualquier tipo de cobro en metálico y emitir esta Política, que tiene por objeto formalizar esa prohibición y definir las pautas de conducta y/o procedimientos que deben observarse a este respecto.",
    "content_outline": [
      "1. Objeto",
      "2. Prohibición de aceptar cobros en efectivo"
    ],
    "source_file": "PI-05. Política sobre prohibición de aceptar cobros en efectivo.pdf",
    "provenance": "PDF_EXTRAIDO"
  },
  {
    "policy_code": "PI-06",
    "title": "Política sobre facturación en la tasación de costas",
    "normative_tier": "POLITICA",
    "edicion": "Edición 01, octubre 2013",
    "effective_date": "2013-10-01",
    "current_version": 1,
    "summary": "El pago de las costas es una indemnización que percibe un litigante de su contrario, en la que se comprende una parte o la totalidad de los gastos efectivamente satisfechos por el primero con ocasión del proceso judicial en el que ha tenido lugar la condena en costas a dicho contrario. A fin de obtener el referido pago, es bastante habitual que haya de seguirse un procedimiento de tasación de costas, en el que será necesario aportar la factura correspondiente a la intervención del Letrado (siempre que ésta sea preceptiva en el proceso judicial), lo que suscita diversas cuestiones: (a) necesidad de que exista, por un lado, un pago del cliente al Despacho por servicios profesionales (contra la presentación de la oportuna factura, con su correspondiente IVA) y, por otro, un pago indemnizatorio que realiza el litigante vencido a nuestro cliente (cuyo título es la sentencia y que no está sujeto a IVA); (b) cuando se emite la factura se desconoce si la misma, en el procedimiento de tasación, su importe será finalmente aprobado o se verá reducido; y (c) posibilidad de que nuestros honorarios no estuviesen facturados o de que el importe de la factura remitida al cliente (en su momento) sea igual, inferior o superior, a la presentada para la tasación de las costas. Esta Política tiene como objeto analizar esas distintas situaciones que pueden plantearse y establecer cuáles son los criterios aplicables en cada caso.",
    "content_outline": [
      "1. Objeto",
      "2. La cuestión del IVA",
      "3. La incertidumbre sobre la aprobación de la minuta sujeta a tasación",
      "4. Distintos supuestos",
      "4.1. Nuestros honorarios están facturados, nuestra factura está pagada y consideramos que sus conceptos y cuantías se ajustan estrictamente a las costas a presentar a tasación",
      "4.2. Nuestros honorarios están facturados, nuestra factura está pagada, pero es menor que la que consideramos que se aprobará en una tasación de costas",
      "4.3. Nuestros honorarios están facturados, nuestra factura está pagada, pero ésta es mayor que la que se ha de presentar para tasación de costas",
      "4.4. Si nuestros honorarios no estuviesen facturados, y la factura de la tasación de costas comprendiese todos los honorarios que debemos percibir",
      "4.5. Si nuestros honorarios no estuviesen facturados y el total de los mismos, cualquiera que sea la causa, fuese mayor que la cantidad a incluir en la tasación de costas",
      "4.6. Si nuestros honorarios no estuviesen facturados y se pacta con el cliente que los mismos ascenderán al importe exacto resultante de la tasación de costas",
      "5. Otros temas",
      "5.1. Emisión de facturas por pleitos",
      "5.2. Cheques de los procuradores",
      "5.3. Emisión de la factura de tasación de costas y remisión de la misma al procurador",
      "5.4. Autorización del cliente para la compensación de la cuenta a pagar",
      "5.5. Tasaciones de costas en el caso de pleitos de reclamación de honorarios contra nuestros clientes",
      "6. Anexos"
    ],
    "source_file": "PI-06. Política sobre facturación en la tasación de costas.pdf",
    "provenance": "PDF_EXTRAIDO"
  },
  {
    "policy_code": "PI-07",
    "title": "Política sobre contestación de cartas de auditoría",
    "normative_tier": "POLITICA",
    "edicion": "Edición 4, marzo 2020",
    "effective_date": "2020-03-01",
    "current_version": 4,
    "summary": "Esta Política tiene como objeto establecer cuál es el procedimiento formal que debe seguirse para dar contestación a las cartas de auditoría, así como cuáles son los criterios aplicables en relación con el contenido y el alcance de la respuesta que ha de darse a esas cartas.",
    "content_outline": [
      "1. Objeto",
      "2. Procedimiento de contestación a las cartas de auditoría",
      "3. Contenido y alcance de la respuesta que ha de darse a las cartas de auditoría",
      "4. Anexos",
      "5. Histórico de versiones"
    ],
    "source_file": "PI-07. Política sobre contestación de cartas de auditoría.pdf",
    "provenance": "PDF_EXTRAIDO"
  },
  {
    "policy_code": "PI-08",
    "title": "Política sobre cobertura de responsabilidad en Due Diligences y Legal opinions",
    "normative_tier": "POLITICA",
    "edicion": "Edición 2, octubre 2018",
    "effective_date": "2018-10-01",
    "current_version": 2,
    "summary": "Esta Política tiene como objeto definir los términos mínimos bajo los que, en lo que atañe a la cobertura de nuestra responsabilidad profesional, debe emitirse por parte de GARRIGUES todo Informe de Auditoría Legal (Due-Diligence) u Opinión Legal (Legal Opinion). Con esta Política no se persigue el establecimiento de estándares monolíticos de uso obligatorio, sino la definición de una base de cobertura mínima de responsabilidad profesional que, a partir de modelos de referencia, ofrezcan un instrumento de trabajo ágil y una base de partida de consideración necesaria por parte de los Socios, Counsels y Asociados Seniors/Principales de GARRIGUES.",
    "content_outline": [
      "1. Objeto",
      "2. Informes de auditoría legal (due-diligences)",
      "2.1. Modelo de referencia",
      "2.2. Contratos, con clientes, de encargados del tratamiento de datos de carácter personal",
      "3. Opiniones legales (legal opinions)",
      "3.1. Procedimiento interno de documentación y revisión",
      "3.2. Modelo de referencia"
    ],
    "source_file": "PI-08. Política sobre cobertura de responsabilidad en Due Diligences y Legal opinions.pdf",
    "provenance": "PDF_EXTRAIDO"
  },
  {
    "policy_code": "PI-09",
    "title": "Política sobre actuación como representante fiscal de clientes",
    "normative_tier": "POLITICA",
    "edicion": "Edición 1, octubre 2013",
    "effective_date": "2013-10-01",
    "current_version": 1,
    "summary": "En ocasiones, nuestros clientes nos solicitan que actuemos como sus representantes fiscales ante la Administración tributaria. Estas representaciones pueden ser, en principio, de dos tipos: (a) por un lado, representaciones de personas o entidades que, a efectos fiscales, tienen el carácter de no residentes en España, y, (b) por otro lado, las representaciones otorgadas por un cliente (sea, o no, residente en España) con el fin de realizar determinadas actuaciones o trámites (inspección fiscal, reclamaciones, recursos, etc.) ante órganos administrativos o jurisdiccionales. Esta Política tiene como objeto establecer cuáles son los criterios y pautas de actuación aplicables en el Despacho en relación con uno y otro tipo de representación, así como los procedimientos a seguir para su aceptación. No es objeto de esta Política el análisis técnico de cuáles son las posibles responsabilidades en las que puede incurrir un representante fiscal. Éste es un análisis que, necesaria e ineludiblemente, habrá de llevarse a cabo a la vista de las circunstancias específicas de cada caso concreto y de la normativa vigente en cada momento.",
    "content_outline": [
      "1. Objeto",
      "2. Representación de no residentes",
      "3. Realización, como representantes o como gestores, de determinadas actuaciones o trámites por cuenta del cliente",
      "4. Otras cuestiones a considerar"
    ],
    "source_file": "PI-09. Política sobre actuación como representante fiscal de clientes.pdf",
    "provenance": "PDF_EXTRAIDO"
  },
  {
    "policy_code": "PI-10",
    "title": "Política sobre contratación de servicios con administraciones públicas, entes públicos y sector público",
    "normative_tier": "POLITICA",
    "edicion": "Edición 2, abril 2016",
    "effective_date": "2016-04-01",
    "current_version": 2,
    "summary": "Esta Política tiene como objeto el establecimiento de criterios y procedimientos específicos para la contratación de servicios con clientes que formen parte del Sector Público –en adelante, los “Clientes del Sector Público”–. A estos efectos, se considera que forman parte del Sector Público los siguientes entes, organismos y entidades: (a) La Administración General del Estado, las Administraciones de las Comunidades Autónomas y las Entidades que integran la Administración Local. (b) Las entidades gestoras y los servicios comunes de la Seguridad Social. (c) Los organismos autónomos, las entidades públicas empresariales, las Universidades Públicas, las Agencias Estatales y cualesquiera entidades de derecho público con personalidad jurídica propia vinculadas a un sujeto que pertenezca al Sector Público o dependientes del mismo, incluyendo aquellas que, con independencia funcional o con una especial autonomía reconocida por la Ley, tengan atribuidas funciones de regulación o control de carácter externo sobre un determinado sector o actividad. (d) Las sociedades mercantiles en cuyo capital social la participación, directa o indirecta, de entidades de las mencionadas en las letras (a) a (f) del presente apartado sea superior al 50 por 100. (e) Los consorcios dotados de personalidad jurídica propia a los que se refieren el artículo 6.5 de la Ley 30/1992, de 26 de noviembre, de Régimen Jurídico de las Administraciones Públicas y del Procedimiento Administrativo Común, y la legislación de régimen local. (f) Las fundaciones que se constituyan con una aportación mayoritaria, directa o indirecta, de una o varias entidades integradas en el Sector Público, o cuyo patrimonio fundacional, con un carácter de permanencia, esté formado en más de un 50 por 100 por bienes o derechos aportados o cedidos por las referidas entidades. (g) Las Mutuas de Accidentes de Trabajo y Enfermedades Profesionales de la Seguridad Social. (h) Cualesquiera entes, organismos o entidades con personalidad jurídica propia, que hayan sido creados específicamente para satisfacer necesidades de interés general que no tengan carácter industrial o mercantil, siempre que uno o varios sujetos pertenecientes al Sector Público financien mayoritariamente su actividad, controlen su gestión, o nombren a más de la mitad de los miembros de su órgano de administración, dirección o vigilancia. (i) Las asociaciones constituidas por los entes, organismos y entidades mencionados en las letras anteriores. Asimismo, esta Política resulta de aplicación a la contratación de servicios que estén subvencionados por Clientes del Sector Público. Los criterios y procedimientos específicos establecidos en esta Política se entienden sin perjuicio de la aplicación de los criterios y procedimientos generales establecidos en la Política Interna PI-01, sobre aceptación de nuevos clientes y asuntos.",
    "content_outline": [
      "1. Introducción",
      "2. Objeto",
      "3. Criterios y procedimientos específicos aplicables",
      "4. Anexos"
    ],
    "source_file": "PI-10. Política sobre contratación de servicios con administraciones públicas, entes públicos y sector público.pdf",
    "provenance": "PDF_EXTRAIDO"
  },
  {
    "policy_code": "PI-11",
    "title": "Política sobre la utilización de recursos informáticos de Garrigues y derecho a la desconexión digital",
    "normative_tier": "POLITICA",
    "edicion": "Edición 20, junio 2025",
    "effective_date": "2025-06-01",
    "current_version": 20,
    "summary": "Las específicas características de la actividad profesional de Garrigues requieren el más estricto cumplimiento de los principios de seguridad, confidencialidad y protección de los intereses de los clientes y, en general, de los terceros relacionados con el Despacho. Por tal razón, el personal y los profesionales de Garrigues deben utilizar, de forma adecuada, y conforme a lo establecido en esta Política, tanto los recursos informáticos del Despacho, como los datos y la información puestos a su disposición a través de los mismos, sin incurrir en actividades o formas de uso que puedan ser consideradas ilícitas, que infrinjan los derechos de Garrigues o de terceros, o que puedan atentar contra la buena práctica profesional o contra las normas establecidas respecto del buen uso de los sistemas y recursos informáticos.",
    "content_outline": [
      "1. Objeto",
      "2. Supuestos que constituyen una mala utilización de los sistemas y recursos informáticos del despacho",
      "3. Control físico de dispositivos informáticos",
      "4. Confidencialidad de la información",
      "5. Identificación y contraseñas",
      "6. Uso del correo electrónico",
      "7. Acceso a internet",
      "8. Utilización del Sistema de Gestión Documental (DMS)",
      "8.1 Reglas generales de uso del DMS",
      "8.2 Estadísticas de uso y monitorización del Sistema",
      "8.3 Política de Seguridad aplicable al archivo en DMS",
      "9. Uso de Garrigues Share - Big files y Contract Express",
      "9.1 Uso de Garrigues Share",
      "9.2 Acceso y uso de Contract Express",
      "10. Control de las herramientas y recursos informáticos",
      "11. Derecho a la desconexión digital",
      "12. Terminación de la relación (laboral o profesional) del usuario con Garrigues",
      "13. Formación en las herramientas y aplicaciones informáticas"
    ],
    "source_file": "PI-11 Política sobre la utilización de recursos informáticos de Garrigues y derecho a la desconexión digital.pdf",
    "provenance": "PDF_EXTRAIDO"
  },
  {
    "policy_code": "PI-12",
    "title": "Política sobre firma corporativa en los correos electrónicos y emisión de tarjetas de visita",
    "normative_tier": "POLITICA",
    "edicion": "Edición 05, julio 2022",
    "effective_date": "2022-07-01",
    "current_version": 5,
    "summary": "Esta política tiene como objeto reforzar la imagen corporativa del despacho, estableciendo, por un lado, cuáles son los datos que deben figurar en la firma corporativa incluida en los correos electrónicos, así como el formato de los mismos y, por otro, cuáles son las menciones que deben o pueden incluirse en nuestras tarjetas de visita.",
    "content_outline": [
      "1. Objeto",
      "2. Firma corporativa en los correos electrónicos",
      "3. Menciones que deben o pueden incluirse en las tarjetas de visita",
      "4. Anexo",
      "5. Histórico de versiones"
    ],
    "source_file": "PI-12. Política sobre firma corporativa en los correos electrónicos y emisión de tarjetas de visita.pdf",
    "provenance": "PDF_EXTRAIDO"
  },
  {
    "policy_code": "PI-13",
    "title": "Política sobre redes sociales, blogs y otros medios de comunicación sociales",
    "normative_tier": "POLITICA",
    "edicion": "Edición 01, octubre 2013",
    "effective_date": "2013-10-01",
    "current_version": 1,
    "summary": "La utilización de redes sociales, blogs y otros medios de comunicación sociales (2.0) se ha convertido en algo normal y cada vez más habitual, tanto en el ámbito estrictamente personal (particular y privado), como en el de las relaciones profesionales y empresariales. Garrigues concibe su uso como una herramienta de comunicación institucional que, en línea con la estrategia y objetivos del Despacho, puede contribuir a potenciar la identidad y la cultura corporativa de la Firma. Esta Política tiene como objeto establecer las reglas y principios que los miembros de Garrigues han de tener en cuenta, y aplicar, en relación con estas redes y canales de comunicación sociales.",
    "content_outline": [
      "1. Objeto",
      "2. Reglas y principios aplicables"
    ],
    "source_file": "PI-13. Política sobre redes sociales, blogs y otros medios de comunicación sociales.pdf",
    "provenance": "PDF_EXTRAIDO"
  },
  {
    "policy_code": "PI-14",
    "title": "Política sobre aprobación de contenidos con fines divulgativos y envío de comunicaciones comerciales",
    "normative_tier": "POLITICA",
    "edicion": "Edición 04, marzo 2020",
    "effective_date": "2020-03-01",
    "current_version": 4,
    "summary": "Esta política tiene como objeto establecer, por un lado, el procedimiento a seguir para la aprobación de los contenidos que se elaboren por profesionales de GARRIGUES con fines divulgativos y/o comerciales, y, por otro, los criterios y procedimientos aplicables en el despacho para el envío de comunicaciones comerciales y promocionales. Es esencial que todos observemos esta política para evitar riesgos que, de otro modo, podrían ser relevantes, no solo en términos económicos sino, también, en cuanto a imagen reputacional del despacho.",
    "content_outline": [
      "1. Objeto",
      "2. Procedimiento de aprobación de contenidos con fines divulgativos y/o comerciales",
      "3. Necesaria utilización de la base de datos de marketing (BDM)",
      "3.1. Finalidad de la BDM y responsables de la misma",
      "3.2. Uso obligatorio de la BDM y razones que lo justifican",
      "4. Tipos de comunicaciones y procedimiento aplicable en cada caso",
      "4.1. Comunicaciones comerciales y promocionales de carácter periódico",
      "4.2. Comunicaciones comerciales y promocionales de carácter puntual",
      "5. Histórico de versiones",
      "6. Anexos"
    ],
    "source_file": "PI-14. Política sobre aprobación de contenidos con fines divulgativos y envío de comunicaciones comerciales.pdf",
    "provenance": "PDF_EXTRAIDO"
  },
  {
    "policy_code": "PI-15",
    "title": "Política sobre telefonía fija y móvil",
    "normative_tier": "POLITICA",
    "edicion": "Edición 05, febrero 2025",
    "effective_date": "2025-02-01",
    "current_version": 5,
    "summary": "Esta Política tiene por objeto establecer las reglas y principios aplicables en el Despacho en relación con el uso de la telefonía fija y móvil y los dispositivos móviles personales.",
    "content_outline": [
      "1. Objeto",
      "2. Telefonía fija",
      "3. Telefonía móvil",
      "3.1 Altas de dispositivos móviles",
      "3.2 Características de los terminales móviles y líneas facilitados por el Despacho",
      "3.3 Renovación de los terminales móviles",
      "3.4 Reparación de terminales",
      "3.5 Peticiones/Incidencias",
      "3.6 Punto Wifi",
      "3.7 Bajas",
      "3.8 BYOD - Dispositivos personales",
      "3.9 Facturación y cargabilidad de la telefonía móvil",
      "3.10 Uso de los terminales móviles en el extranjero",
      "4. Histórico de versiones"
    ],
    "source_file": "PI-15. Política sobre telefonía fija y móvil.pdf",
    "provenance": "PDF_EXTRAIDO"
  },
  {
    "policy_code": "PI-16",
    "title": "Política sobre grabaciones de sesiones técnicas y otros actos",
    "normative_tier": "POLITICA",
    "edicion": "Edición 03, marzo 2023",
    "effective_date": "2023-03-01",
    "current_version": 3,
    "summary": "Cada vez son más frecuentes las peticiones de grabación de sesiones técnicas y de otros eventos que se organizan desde las distintas oficinas del Despacho, bien sea con fines de formación interna o para su difusión externa en foros y por canales de distinta naturaleza. Como a nadie se le escapa, la grabación de la imagen y/o de la voz de los participantes en este tipo de actos afecta, directamente, a sus derechos de imagen, propiedad intelectual y protección de datos de carácter personal, derechos a los que la ley concede una especial protección y cuya salvaguarda ha de ser garantizada en todo caso. De igual modo, la difusión de las grabaciones pudiera afectar, asimismo y en su caso, al deber de secreto y confidencialidad al que estamos obligados en relación con nuestros clientes y sus asuntos, cuya vulneración podría acarrear importantes responsabilidades para el Despacho. Por ello, resulta fundamental garantizar -en todo momento- una correcta realización de tales grabaciones, así como asegurar el adecuado control de los soportes de las mismas. Esta Política tiene como objeto establecer los criterios y pautas de actuación aplicables en materia de grabación de sesiones técnicas y otros actos, con el fin de cubrir y evitar cualquier riesgo de índole legal que pudiera derivarse de la realización de estas grabaciones..",
    "content_outline": [
      "1. Objeto",
      "2. Actos con difusión y ponentes exclusivamente Internos",
      "3. Actos con participación de ponentes y/o asistentes externos",
      "4. Solicitud de las grabaciones"
    ],
    "source_file": "PI-16. Política sobre grabaciones de sesiones técnicas y otros actos.pdf",
    "provenance": "PDF_EXTRAIDO"
  },
  {
    "policy_code": "PI-17",
    "title": "Política sobre gastos profesionales, viajes, desplazamientos y otros",
    "normative_tier": "POLITICA",
    "edicion": "Edición 2, septiembre 2022",
    "effective_date": "2022-09-01",
    "current_version": 2,
    "summary": "Esta Política tiene como objeto establecer los criterios aplicables en el Despacho en materia de gastos profesionales incurridos por el personal, así como las pautas de actuación a seguir en relación con su autorización, liquidación y reintegro por el Despacho.",
    "content_outline": [
      "1. Objeto",
      "2. Criterios generales de los gastos profesionales",
      "2.1. Documento soporte del gasto",
      "2.2. Imputación contable del gasto",
      "3. Medios de transporte",
      "3.1. Opción de transporte a elegir",
      "3.2. Agencia de viajes a utilizar",
      "3.3. Tipo de billete a utilizar (avión y tren)",
      "3.4. Taxis",
      "3.5. Utilización de vehículos (costes y kilometraje)",
      "4. \"Parkings\" y peajes",
      "5. Dietas de viaje",
      "6. Hoteles",
      "7. Lavandería",
      "8. Teléfono móvil",
      "9. Comidas con clientes",
      "10. Comidas \"promoción\"-\"práctica profesional\"",
      "11. Otros gastos",
      "11.1. Mensajería",
      "11.2. Reprografía",
      "11.3. Traducción",
      "11.4. Alquiler de salas y organización de eventos",
      "11.5. Medios audiovisuales",
      "11.6. Servicio de \"catering\"",
      "12. Aprobación de gastos",
      "13. Histórico de versiones",
      "14. Anexos"
    ],
    "source_file": "PI-17. Política sobre gastos profesionales, viajes, desplazamientos y otros.pdf",
    "provenance": "PDF_EXTRAIDO"
  },
  {
    "policy_code": "PI-18",
    "title": "Política sobre formación externa",
    "normative_tier": "POLITICA",
    "edicion": "Edición 01, octubre 2013",
    "effective_date": "2013-10-01",
    "current_version": 1,
    "summary": "Esta Política tiene como objeto establecer los criterios aplicables en el Despacho en materia de asistencia a cursos técnicos y de especialización externos (que no se imparten en Garrigues o por nuestros profesionales) de corta duración (ej.: jornadas, seminarios, conferencias, etc.).",
    "content_outline": [
      "1. Objeto",
      "2. Criterios aplicables en materia de formación externa"
    ],
    "source_file": "PI-18. Política sobre formación externa.pdf",
    "provenance": "PDF_EXTRAIDO"
  },
  {
    "policy_code": "PI-19",
    "title": "Política sobre compra, préstamo y utilización de libros",
    "normative_tier": "POLITICA",
    "edicion": "Edición 04, septiembre 2022",
    "effective_date": "2022-09-01",
    "current_version": 4,
    "summary": "Esta Política tiene como objeto establecer cuáles son los criterios y procedimientos del Despacho aplicables en materia de compra, préstamo y utilización de libros.",
    "content_outline": [
      "1. Objeto",
      "2. Compra de libros",
      "3. Préstamo y devolución de libros",
      "3.1. Libros en papel",
      "3.2. Libros en formato electrónico",
      "4. Utilización de libros electrónicos en dispositivos personales",
      "5. Propiedad intelectual",
      "6. Anexo"
    ],
    "source_file": "PI-19. Política sobre compra, préstamo y utilización de libros.pdf",
    "provenance": "PDF_EXTRAIDO"
  },
  {
    "policy_code": "PI-20",
    "title": "Política sobre notificaciones de órganos administrativos, judiciales o de otra índole recibidas",
    "normative_tier": "POLITICA",
    "edicion": "Edición 01, octubre 2013",
    "effective_date": "2013-10-01",
    "current_version": 1,
    "summary": "Con cierta frecuencia, se reciben en el Despacho notificaciones remitidas por órganos administrativos, judiciales o de otra índole cuyos destinatarios son, bien el propio Despacho (entendiendo por tal a cualquiera de las sociedades del Grupo Garrigues), bien alguno de sus empleados o profesionales en particular. En ocasiones, esas notificaciones conllevan la apertura de plazos perentorios para formular alegaciones, presentar prueba o, en general, llevar a cabo una concreta actuación, por lo que resulta esencial que sean recibidas por sus destinatarios, de forma correcta y a la mayor brevedad. Por esa razón, se ha considerado conveniente establecer esta Política, que tiene como objeto especificar los procedimientos aplicables en relación con esas notificaciones de órganos administrativos, judiciales o de otra índole.",
    "content_outline": [
      "1. Objeto",
      "2. Criterios de aplicación general",
      "3. Notificaciones recibidas en el despacho, cuyo destinatario es un empleado o profesional concreto",
      "4. Notificaciones recibidas en el despacho, cuyo destinatario es el propio despacho"
    ],
    "source_file": "PI-20. Política sobre notificaciones de órganos administrativos, judiciales o de otra índole recibidas.pdf",
    "provenance": "PDF_EXTRAIDO"
  },
  {
    "policy_code": "PI-21",
    "title": "Política sobre expurgo y destrucción de documentos por transcurso del tiempo",
    "normative_tier": "POLITICA",
    "edicion": "Edición 01, octubre 2013",
    "effective_date": "2013-10-01",
    "current_version": 1,
    "summary": "El Despacho cuenta con un Sistema de Gestión Documental (DMS), en el que deben archivarse todos los documentos relativos a clientes y/o que, de cualquier manera, estén relacionados con (o se refieran a) la actividad profesional de los miembros de Garrigues. No obstante, gran parte de esos documentos se archivan también en papel, generando carpetas que, en ocasiones, se conservan indefinidamente sin que ello sea en realidad necesario, con el consiguiente coste para el Despacho. Por ello, se ha considerado conveniente publicar esta Política, que tiene como objeto establecer los criterios y procedimientos aplicables en el Despacho en materia de expurgo y destrucción por transcurso del tiempo de los documentos en soporte papel, generados por los miembros de Garrigues en el desarrollo de su actividad profesional. Esta Política resulta aplicable, tanto a los documentos que se generen a partir de su publicación, como a los generados con anterioridad.",
    "content_outline": [
      "1. Objeto",
      "2. Criterios y procedimientos aplicables"
    ],
    "source_file": "PI-21. Política sobre expurgo y destrucción de documentos por transcurso del tiempo.pdf",
    "provenance": "PDF_EXTRAIDO"
  },
  {
    "policy_code": "PI-22",
    "title": "Política sobre calidad, prevención de riesgos laborales, medio ambiente y Responsabilidad social corporativa",
    "normative_tier": "POLITICA",
    "edicion": null,
    "effective_date": null,
    "current_version": 1,
    "summary": "Este documento tiene como objeto recoger la Política de calidad, prevención de riesgos laborales, medio ambiente y responsabilidad social corporativa de J&A Garrigues, S.L.P. y todas las sociedades del Grupo (en adelante, “Garrigues”, el “Despacho”, o el “Grupo”), en la que se especifican los compromisos adquiridos al respecto de estas materias por el Despacho, y que todos sus miembros deberán respetar en el desarrollo de sus respectivas actividades, sin perjuicio de otra normativa interna del Despacho que resulte de aplicación. Se considerarán miembros de Garrigues los Socios, empleados, colaboradores (Counsel y similares) y becarios de todas las sociedades y entidades que integran el Grupo.",
    "content_outline": [
      "1. Objeto",
      "2. Política de calidad, prevención de riesgos laborales, medio ambiente y responsabilidad social corporativa",
      "3. Cumplimiento de esta política",
      "3.1. Calidad",
      "3.2. Prevención de riesgos laborales",
      "3.3. Medio Ambiente",
      "3.4. Responsabilidad Social Corporativa",
      "4. Histórico de versiones"
    ],
    "source_file": "PI-22. Política sobre calidad, prevención de riesgos laborales, medioambiente y responsabilidad social ......pdf",
    "provenance": "PDF_EXTRAIDO"
  },
  {
    "policy_code": "PI-23",
    "title": "Política sobre medidas contra la corrupción, el cohecho y el tráfico de influencias",
    "normative_tier": "POLITICA",
    "edicion": "Edición 03, marzo 2020",
    "effective_date": "2020-03-01",
    "current_version": 3,
    "summary": "El Despacho está firmemente comprometido con el estricto cumplimiento de la legalidad y la actuación ética en la prestación de sus servicios, así como con la transparencia en todos sus ámbitos de actuación. Garrigues rechaza, por tanto, cualquier comportamiento reprobable o cuestionable, tanto desde la perspectiva legal, como desde la ética o deontológica. En particular, y entre otras conductas, Garrigues rechaza cualquier forma de corrupción, cohecho o tráfico de influencias, y defiende la necesidad de proteger la competencia libre y leal dentro del mercado, así como de garantizar que los servicios públicos funcionen con el máximo nivel de objetividad e imparcialidad. Por ello, y en desarrollo de los valores, principios y pautas de actuación recogidos al respecto en el Código Ético de Garrigues, se ha considerado oportuno publicar esta Política, que tiene como objeto establecer determinadas medidas específicas dirigidas a prevenir y, en su caso, detectar y reaccionar, ante cualquier forma de corrupción, cohecho o tráfico de influencias. Esas medidas constituyen el modelo ético de conducta que debe inspirar y presidir, en todo momento, la actuación de los miembros de Garrigues, dirigido a impulsar el comportamiento ético, íntegro y responsable de todos ellos. Resulta esencial que todos los miembros de Garrigues (entendiendo por tales a los Socios, empleados, colaboradores -Counsels y similares- y becarios de todas las sociedades y entidades que integran el Grupo Garrigues) cumplan con lo establecido en esta Política, así como con el resto del Sistema Normativo Interno del Despacho, y las disposiciones de carácter nacional e internacional aplicables en la materia.",
    "content_outline": [
      "1. Objeto",
      "2. Definiciones",
      "3. Prohibiciones absolutas",
      "4. Pautas de actuación aplicables en las relaciones con los grupos de interés",
      "4.1. La administración pública",
      "4.2. Los clientes",
      "4.3. Los proveedores",
      "5. Regalos, atenciones comerciales y promocionales y muestras de hospitalidad o cortesía",
      "6. Histórico de versiones"
    ],
    "source_file": "PI-23. Política sobre medidas contra la corrupción, el cohecho y el tráfico de influencias.pdf",
    "provenance": "PDF_EXTRAIDO"
  },
  {
    "policy_code": "PI-24",
    "title": "Política sobre herramientas colaborativas - Plataformas Garrigues Collaborate y Microsoft Teams",
    "normative_tier": "POLITICA",
    "edicion": "Edición 06, marzo 2023",
    "effective_date": "2023-03-01",
    "current_version": 6,
    "summary": "El objeto de esta Política es establecer cuáles son los criterios y procedimientos aplicables a la creación, funcionamiento y cierre de los “espacios” colaborativos disponibles en el Despacho, como herramientas de colaboración entre Garrigues y sus clientes y entre los profesionales de Garrigues. En esta Política la expresión “espacios” hará referencia tanto a los sitios en Collaborate como a los equipos de Teams. El uso de estas herramientas ha de hacerse con el más estricto cumplimiento de los principios de seguridad, confidencialidad e integridad de la información y protección de los intereses de los clientes, consagrados en la Política interna PI-11 sobre la utilización de los recursos informáticos de Garrigues, de la que esta Política es complementaria.",
    "content_outline": [
      "1. Introducción",
      "2. Objeto y alcance de esta política",
      "3. Principios generales",
      "4. Teams",
      "4.1 Solicitud de apertura del sitio",
      "4.2 Aprobación y creación de equipos de Teams",
      "4.3 Usuarios y responsabilidades",
      "4.4 Condiciones de uso de los equipos de Teams",
      "5. Collaborate",
      "5.1 Solicitud de apertura de espacios",
      "5.2 Aprobación y creación de sitios en Collaborate",
      "5.3 Seguridad de Collaborate",
      "5.3.1 Cuestiones generales",
      "5.3.2 Accesos",
      "5.3.3 Tipos de permisos",
      "6. Mantenimiento y cierre de los espacios",
      "6.1 Con carácter general para Collaborate y Teams",
      "6.2 Con carácter específico para Collaborate",
      "7. Histórico de versiones",
      "8. Anexos Pl-24"
    ],
    "source_file": "PI-24. Política sobre herramientas colaborativas - Plataformas Garrigues Collaborate y Microsoft Teams.PDF",
    "provenance": "PDF_EXTRAIDO"
  },
  {
    "policy_code": "PI-25",
    "title": "Política sobre utilización de la tarjeta de crédito corporativa",
    "normative_tier": "POLITICA",
    "edicion": "Edición 01, marzo 2015",
    "effective_date": "2015-03-01",
    "current_version": 1,
    "summary": "Esta política tiene por objeto establecer los principios y las reglas de utilización, por parte de aquellas personas que sean titulares de la misma, de la tarjeta de crédito corporativa del Despacho.",
    "content_outline": [
      "1. Objeto",
      "2. Tarjeta de crédito corporativa: finalidad y obligaciones de su titular",
      "3. Imputación y liquidación de los gastos pagados con la tarjeta",
      "4. No utilización de la tarjeta para la reserva y adquisición de billetes de viaje"
    ],
    "source_file": "PI-25. Política sobre utilización de la tarjeta de crédito corporativa.pdf",
    "provenance": "PDF_EXTRAIDO"
  },
  {
    "policy_code": "PI-26",
    "title": "Política sobre seguridad de la información",
    "normative_tier": "POLITICA",
    "edicion": "Edición 04, junio 2025",
    "effective_date": "2025-06-01",
    "current_version": 4,
    "summary": "Este documento tiene como objeto recoger la Política de Seguridad de la Información del Grupo Garrigues, en la que se especifican los compromisos asumidos por la Dirección en relación al Sistema de Gestión de la Seguridad de la Información aplicado a los sistemas de información que dan soporte a los servicios de Asesoramiento Jurídico y Fiscal, Asesoramiento en Transacciones y en Procedimientos administrativos y/o judiciales, y servicios de Consultoría prestados por las empresas del Grupo Garrigues a sus clientes, definiendo el marco organizativo y ejecutivo que garantice la confidencialidad, integridad y disponibilidad del sistema de información. La aprobación de la citada Política se enmarca en el proceso de implantación del Sistema de Gestión de la Seguridad de la Información de Garrigues, con el que se persigue garantizar que nuestros Sistemas de Información están siendo gestionados con la seguridad requerida, utilizando para ello las mejores prácticas internacionales conforme el estándar ISO/IEC 27001 y Esquema Nacional de Seguridad (ENS). El Objetivo de la Política de Seguridad de los Sistemas de Información es doble:  Por un lado, consiste en definir el marco de referencia que permita salvaguardar las características de seguridad de los activos que dan soporte a los procesos del Grupo Garrigues. Y ello, en base a los resultados del análisis de riesgos realizado, a los requisitos estratégicos del negocio alineados con los requisitos de seguridad, así como a los requisitos legales y contractuales. Como exige el marco de referencia anteriormente mencionado, esta Política de Seguridad sirve para establecer los principios fundamentales de seguridad de los Sistemas de Información que se desarrollan en las normas, procedimientos, instrucciones técnicas, registros u otros documentos necesarios para especificar el uso de la información, de los sistemas y de los activos que los soportan.  Por otro, la Política de Seguridad de la Información de Garrigues tiene como objetivo establecer las medidas de seguridad de naturaleza organizativa, física y lógica que se consideran adecuadas para salvaguardar las características de seguridad de los activos mencionados, partiendo del presupuesto de que la seguridad debe ser concebida como un proceso integral transversal (que comprende todos los elementos técnicos, humanos, materiales y organizativos relacionados con los sistemas de información y comunicaciones), y no debe entenderse como un gasto en la gestión, sino como una inversión en evitar impactos negativos sobre el negocio.",
    "content_outline": [
      "1. Introducción",
      "2. Objetivos",
      "3. Marco legal y regulatorio",
      "4. Alcance",
      "5. Principios fundamentales de la Política de Seguridad",
      "6. Responsabilidades",
      "7. Usuarios",
      "8. Prevención",
      "9. Detección",
      "10. Respuesta",
      "11. Recuperación",
      "12. Notificación de incidentes",
      "13. Terceras partes",
      "14. Aprobación y divulgación de la política de seguridad",
      "15. Revisión de la Política de Seguridad",
      "16. Referencias",
      "17. Histórico de versiones"
    ],
    "source_file": "PI-26. Política sobre seguridad de la información.pdf",
    "provenance": "PDF_EXTRAIDO"
  },
  {
    "policy_code": "PI-27",
    "title": "Política sobre gestión de la documentación en papel",
    "normative_tier": "POLITICA",
    "edicion": "Edición 03, octubre 2018",
    "effective_date": "2018-10-01",
    "current_version": 3,
    "summary": "Esta Política tiene como objeto establecer los criterios y pautas de actuación aplicables en el Despacho en relación con la gestión de la documentación en soporte papel que se genera en el desarrollo de nuestra actividad profesional. Tales criterios y pautas de actuación vienen determinados en gran medida por el hecho de que en esa documentación puede incluirse información confidencial y/o datos de carácter personal, lo que conlleva que debamos adoptar determinadas medidas dirigidas a garantizar esa confidencialidad y/o a cumplir con las obligaciones que resultan de lo dispuesto en el Reglamento (UE) 2016/679 del Parlamento Europeo y del Consejo, de 27 de abril de 2016, relativo a la protección de las personas físicas en lo que respecta al tratamiento de datos personales y a la libre circulación de estos datos y por el que se deroga la Directiva 95/46/CE (Reglamento general de protección de datos).",
    "content_outline": [
      "1. Objeto",
      "2. Política general: archivo de la información en soporte automatizado o electrónico",
      "3. Archivo de la información en soporte papel",
      "3.1. Carpetas de archivo",
      "3.2. Tipos de “archivos físicos” donde guardar la documentación en soporte papel",
      "4. Envío interno de documentación en soporte papel"
    ],
    "source_file": "PI-27. Política sobre gestión de la documentación en papel.pdf",
    "provenance": "PDF_EXTRAIDO"
  },
  {
    "policy_code": "PI-28",
    "title": "Política sobre proveedores",
    "normative_tier": "POLITICA",
    "edicion": "Edición 02, junio 2025",
    "effective_date": "2025-06-01",
    "current_version": 2,
    "summary": "GARRIGUES está firmemente comprometido con el estricto cumplimiento de la legalidad y de los máximos estándares éticos y de transparencia, tanto en la prestación de sus servicios profesionales, como en el resto de sus ámbitos de actuación. En su Código Ético, GARRIGUES establece los valores y principios que conforman las señas de identidad del Despacho, así como las normas y pautas de conducta exigibles a los miembros de la entidad, a clientes y a terceros con los que se relaciona. El objeto de esta Política es desarrollar los valores, principios y pautas de actuación aplicables al proceso de contratación de proveedores de bienes y servicios, bien directamente por parte de GARRIGUES, bien por nuestros clientes, pero mediando alguna recomendación o sugerencia de algún miembro del Despacho.",
    "content_outline": [
      "1. Objeto",
      "2. Criterios aplicables a la contratación de proveedores por parte de Garrigues",
      "3. Criterios aplicables a la recomendación de proveedores a clientes",
      "4. Histórico de versiones",
      "5. Anexos"
    ],
    "source_file": "PI-28. Política sobre proveedores.pdf",
    "provenance": "PDF_EXTRAIDO"
  },
  {
    "policy_code": "PI-29",
    "title": "Política sobre el tratamiento de información privilegiada y la elaboración de las listas de iniciados",
    "normative_tier": "POLITICA",
    "edicion": "Edición 01, junio 2021",
    "effective_date": "2021-06-01",
    "current_version": 1,
    "summary": "En un Despacho como el nuestro resulta esencial el cumplimiento, por todos, de las obligaciones que nos aplican en relación con el tratamiento de Información Privilegiada. Por ello, se ha considerado conveniente documentar en esta Política los criterios aplicables en la materia y, en particular, a la gestión de las listas de Iniciados, que todos debemos cumplir y respetar. La presente Política se ha redactado con base en la normativa vigente en la Unión Europea, pero resulta aplicable, con los debidos ajustes, en las distintas jurisdicciones en que opera GARRIGUES.",
    "content_outline": [
      "1. Objeto y alcance",
      "2. Definiciones",
      "3. Criterios aplicables en materia de información privilegiada",
      "4. La lista de iniciados",
      "5. Relaciones con las autoridades competentes",
      "6. Adaptación a las normativas de otros países",
      "7. Histórico de versiones",
      "8. Anexos"
    ],
    "source_file": "PI-29. Política sobre el tratamiento de información privilegiada y la elaboración de las listas de iniciados.pdf",
    "provenance": "PDF_EXTRAIDO"
  },
  {
    "policy_code": "PI-30",
    "title": "Política de uso de sistemas de inteligencia artificial generativa",
    "normative_tier": "POLITICA",
    "edicion": "Edición 02, Julio de 2025",
    "effective_date": "2025-07-01",
    "current_version": 2,
    "summary": "Esta Política tiene como objeto garantizar en Garrigues el uso legal, ético, responsable, seguro y eficaz de la IA Generativa (en adelante, IA o IA Generativa) por parte de todos los integrantes del Despacho. Su propósito es fomentar el uso responsable de esta tecnología, asegurando que su uso apoya, pero no reemplaza, el juicio experto de nuestros profesionales. La IA se debe utilizar siguiendo el más estricto cumplimiento de las normas generales y deontológicas aplicables a la profesión de abogado y/o economista en cada una de las jurisdicciones donde actúa el Despacho y de los principios de seguridad, confidencialidad e integridad de la información y protección de los intereses de los clientes, consagrados en la Política interna PI-11 sobre la utilización de los recursos informáticos de Garrigues, de la que esta Política es complementaria. Considerando los continuos avances de la IA, esta Política se revisará y ajustará, según sea necesario, para mantenerla alineada con un uso seguro y de calidad de la tecnología, así como para garantizar la calidad, la seguridad y el cumplimiento de la normativa vigente.",
    "content_outline": [
      "1. Objeto y alcance de esta Política",
      "2. Algunos riesgos inherentes al uso de la IA Generativa",
      "3. Normas de uso",
      "4. Obligaciones de transparencia",
      "5. Restricciones impuestas por clientes",
      "6. Comité de IA",
      "7. Régimen sancionador",
      "8. Glosario de términos útiles",
      "9. Histórico de versiones"
    ],
    "source_file": "PI-30. Política de uso de sistemas de inteligencia artificial generativa.pdf",
    "provenance": "PDF_EXTRAIDO"
  },
  {
    "policy_code": "PI-31",
    "title": "Política Sistema Interno de Información (SII) de Garrigues",
    "normative_tier": "POLITICA",
    "edicion": null,
    "effective_date": null,
    "current_version": 1,
    "summary": "La Ley 2/2023, de 20 de febrero, reguladora de la protección de las personas que informen sobre infracciones normativas y de lucha contra la corrupción (en adelante, “Ley de protección del informante”), por la que se incorpora al Derecho español la Directiva (UE) 2019/1937 del Parlamento Europeo y del Consejo, de 23 de octubre de 2019, exige a empresas como Garrigues disponer de un Sistema Interno de Información (en adelante, “SII”) en los términos previstos en la misma. El establecimiento de un SII tiene como principales objetivos proteger a las personas que en un contexto laboral o profesional detecten infracciones penales o administrativas graves o muy graves y las comuniquen mediante los mecanismos regulados al efecto, así como fortalecer y fomentar la cultura de información como mecanismo para prevenir y detectar conductas irregulares. Esta Política tiene por objeto recoger los principios generales que inspiran el SII de J&A Garrigues, S.L.P., Garrigues Portugal, S.L.P. y/o cualquiera otra de las sociedades del Grupo Garrigues (en adelante, “Garrigues” o la “Firma”), así como otras cuestiones previstas en la citada Ley de protección del informante, como el canal o cauce habilitado para la recepción de las comunicaciones relativas a incumplimientos, el procedimiento que deberá seguirse para la tramitación de esas comunicaciones, el Responsable del SII o las medidas de protección y garantías establecidas a favor de los informantes, que solo serán aplicables a las comunicaciones a que se refiere dicha Ley. Para las sociedades del Grupo a las que no sea aplicable la Ley de protección del informante la aplicación de esta Política se hará respetando la normativa que en cada caso resulte aplicable.",
    "content_outline": [
      "1. Objeto",
      "2. Ámbito de aplicación",
      "3. Sistema Interno de Información",
      "4. Responsable del Sistema Interno de Información",
      "5. Medidas de protección y garantías",
      "6. Libro-registro de informaciones",
      "7. Protección de datos personales",
      "8. Histórico de versiones",
      "9. Anexo"
    ],
    "source_file": "PI-31. Política Sistema Interno de Información (SII) de Garrigues.pdf",
    "provenance": "PDF_EXTRAIDO"
  },
  {
    "policy_code": "PI-32",
    "title": "Política de Calidad de Garrigues",
    "normative_tier": "POLITICA",
    "edicion": "Edición 01, junio 2024",
    "effective_date": "2024-06-01",
    "current_version": 1,
    "summary": "J&A Garrigues, S.L.P. y todas las sociedades del Grupo (en adelante, “Garrigues”, el “Despacho” la “Firma” o el “Grupo”) tienen un firme compromiso con la prestación de servicios profesionales de máxima calidad, con el fin de que el cliente obtenga en todo momento la solución más adecuada y eficaz en el asunto encomendado. Esta Política desarrolla lo dispuesto en el artículo 6 del Código Ético de la Firma y tiene como objeto recoger los principios, normas y pautas de actuación en que se materializa ese firme compromiso de Garrigues con la calidad, que todos sus miembros deben respetar en el desarrollo de su respectiva actividad profesional.",
    "content_outline": [
      "1. Objeto y ámbito de aplicación",
      "2. Política de calidad",
      "2.1. Principios básicos de calidad",
      "2.2. Normas y pautas de actuación en materia de calidad",
      "3. Histórico de versiones"
    ],
    "source_file": "PI-32. Política de Calidad de Garrigues.pdf",
    "provenance": "PDF_EXTRAIDO"
  },
  {
    "policy_code": "CE-2023",
    "title": "Código Ético",
    "normative_tier": "POLITICA",
    "edicion": "Edición 04, noviembre 2023",
    "effective_date": "2023-11-01",
    "current_version": 4,
    "summary": "Este documento recoge el código ético (el “Código Ético”) de J&A Garrigues, S.L.P., GARRIGUES Portugal, S.L.P. y/o cualquiera otra de las sociedades del Grupo Garrigues (en adelante, “Garrigues”, el “Despacho”, la “Firma” el “Grupo”) y fue aprobado por su Órgano de Administración el 12 de junio de 2013, previo informe del Comité de Práctica Profesional, conforme a lo establecido en el artículo 10.4 de sus estatutos sociales. El Código Ético contiene los valores y principios que inspiran las señas de identidad del Despacho, así como las normas y pautas de conducta que les son exigibles a los miembros de Garrigues en sus relaciones tanto con la propia Firma y el resto de miembros como con clientes y terceros en general. El Código Ético se ha elaborado teniendo en cuenta los principios de responsabilidad social asumidos por el Despacho para su seguimiento por la Firma y por todas y cada una de las personas que la integran. El conjunto de estos valores, principios, normas y pautas de conducta constituye el modelo ético de comportamiento que debe inspirar y presidir, en todo momento, la actuación de los miembros del Despacho, dirigido a impulsar el comportamiento ético y responsable de todos ellos, y recoge el compromiso de Garrigues con los principios de la ética empresarial y la transparencia en todos sus ámbitos de actuación. Este Código Ético forma parte del Sistema normativo interno de Garrigues, que es el conjunto de políticas, procedimientos, programas, reglamentos, códigos y normas aprobadas por los órganos competentes de la Firma, de carácter interno y obligado cumplimiento para todos los miembros de Garrigues, que incluyen: (i) el Código Ético; (ii) la Normativa interna sobre prevención del blanqueo de capitales y de la financiación del terrorismo; (iii) el Programa para la prevención de delitos; (iv) las Normas profesionales; y (v) las Políticas internas. El Sistema normativo interno estará disponible en la intranet corporativa de Garrigues y queda incorporado por referencia. Sin perjuicio de cualesquiera otras responsabilidades en las que se hubiera podido incurrir, la vulneración de lo dispuesto en este Código Ético o en las demás disposiciones del Sistema normativo interno del Despacho se sancionará, por parte de Garrigues, con arreglo a la normativa aplicable. En el caso de profesionales con relación laboral, tal vulneración se considerará constitutiva de infracción laboral, resultando aplicable la sanción que proceda conforme a la normativa laboral vigente en el país donde el/la profesional preste servicios o haya sido contratado (según proceda). Cuando quien incurra en dicha vulneración sea un socio, será aplicable el régimen disciplinario previsto en el Código de Conducta del Socio. Para el resto de regímenes o relaciones que pudieran existir, se estará a lo pactado en cada caso en el correspondiente documento contractual en que dicha relación se hubiera materializado.",
    "content_outline": [
      "I. Introducción",
      "Artículo 1.- Finalidad",
      "Artículo 2.- Ámbito de aplicación",
      "Artículo 3.- Aceptación y cumplimiento",
      "II. Valores y principios",
      "Artículo 4.- Valores irrenunciables y principios deontológicos fundamentales",
      "Artículo 5.- Compromiso de servicio al cliente",
      "Artículo 6.- Compromiso con la calidad",
      "Artículo 7.- Compromiso con el Despacho y sus miembros",
      "Artículo 8.- Compromiso de actuación ética",
      "Artículo 9.- Integridad",
      "Artículo 10.- Lealtad",
      "Artículo 11.- Independencia",
      "Artículo 12.- Formación permanente",
      "Artículo 13.- Dignidad y respeto",
      "Artículo 14.- Secreto profesional",
      "III. Adhesión al pacto mundial de las Naciones Unidas y contribución a la agenda 2030 para el desarrollo sostenible",
      "Artículo 15.- Adhesión al pacto mundial",
      "IV. Conducta profesional",
      "Artículo 16.- Cumplimiento de la legalidad y de las políticas y normas internas",
      "Artículo 17.- Respeto a los derechos humanos",
      "Artículo 18.- Prevalencia de los intereses del Despacho",
      "Artículo 19.- Tratamiento de la información",
      "Artículo 20.- Conflictos de intereses",
      "Artículo 21.- Regalos e invitaciones",
      "Artículo 22.- Uso apropiado de los recursos del Despacho",
      "Artículo 23.- Oportunidades de negocio",
      "Artículo 24.- Actividades externas",
      "Artículo 25.- Pertenencia a partidos, asociaciones, fundaciones o instituciones con fines públicos",
      "Artículo 26.- Actuaciones pro bono",
      "Artículo 27.- Actividades docentes",
      "Artículo 28.- Redes sociales, blogs y otros medios de comunicaciones sociales",
      "V. Relación con el entorno",
      "Artículo 29.- Grupos de interés",
      "Artículo 30.- Clientes",
      "Artículo 31.- Personal",
      "Artículo 32.- Socios",
      "Artículo 33.- Alianzas",
      "Artículo 34.- Entidades",
      "Artículo 35.- Autoridades, organismos reguladores y administraciones públicas",
      "Artículo 36.- Sociedad",
      "VI. Canal Interno de Información",
      "Artículo 37.- El Canal Interno de Información",
      "Artículo 38.- Comunicaciones al Canal Interno de Información",
      "Artículo 39.- Principios informadores del Canal Interno de Información",
      "Artículo 40.- Responsable del SII de Garrigues",
      "VII. Disposiciones varias",
      "Artículo 41.- Difusión",
      "Artículo 42.- Seguimiento",
      "Artículo 43.- Aplicación",
      "Artículo 44.- Actualización"
    ],
    "source_file": "Codigo-Etico-2023-ES.pdf",
    "provenance": "PDF_EXTRAIDO"
  },
  {
    "policy_code": "PPD-01",
    "title": "Manual del Sistema de Gestión de Riesgos Penales",
    "normative_tier": "NORMA",
    "edicion": "Edición 03, mayo 2018",
    "effective_date": "2018-05-01",
    "current_version": 3,
    "summary": "La finalidad del PPD de Garrigues se centra en definir y establecer las medidas de vigilancia y control idóneas para prevenir los delitos que pudieran cometerse con los medios o bajo la cobertura del Despacho y en su beneficio directo o indirecto. El Programa permitirá a Garrigues: Prevenir la comisión de delitos en su seno Mejorar sus opciones de defensa en los procedimientos penales que eventualmente pudieran incoarse a resultas de hechos presuntamente delictivos cometidos en nombre o por cuenta del Despacho mediante: La acreditación del cumplimiento de los deberes de supervisión, vigilancia y control; La concurrencia de condiciones que permitan la apreciación de una circunstancia eximente o atenuante de responsabilidad criminal Promocionar prácticas lícitas, transparentes y honestas en el mercado (ética empresarial), favoreciendo su imagen externa y reputación y, en definitiva, una cultura de cumplimiento.",
    "content_outline": [
      "1. Introducción. Contexto normativo",
      "2. Finalidad y principios que inspiran el PPD de Garrigues",
      "2.1 Finalidad",
      "2.2 Principios que inspiran el PPD de Garrigues",
      "3. Descripción general y objeto del PPD de Garrigues",
      "4. Identificación, análisis y evaluación de riesgos",
      "4.1 Mapa de riesgos penales",
      "4.2 Plan de acción",
      "5. Medidas preventivas",
      "5.1 Medidas de carácter general para la Firma",
      "5.2 Medidas de carácter específico para departamentos, de práctica e internos, o sociedades del Grupo",
      "6. Modelo de gestión de recursos financieros del PPD",
      "7. Formación, sensibilización y comunicación",
      "8. Supervisión y seguimiento del programa",
      "8.1 Órgano de supervisión",
      "8.2 Sistema disciplinario",
      "8.3 Control de documentos",
      "8.4 Herramienta de soporte",
      "9. Auditoría interna",
      "10. Control de versiones"
    ],
    "source_file": "PPD-01. Manual del Sistema de Gestión de Riesgos Penales.md",
    "provenance": "PDF_EXTRAIDO"
  },
  {
    "policy_code": "PPD-02",
    "title": "Modelo Organizativo del Programa de Prevención de Delitos",
    "normative_tier": "NORMA",
    "edicion": null,
    "effective_date": null,
    "current_version": 1,
    "summary": null,
    "content_outline": [],
    "source_file": null,
    "provenance": "CITADO_NO_INCORPORADO"
  },
  {
    "policy_code": "PBC-FT-10",
    "title": "Manual de Prevención del Blanqueo de Capitales y de la Financiación del Terrorismo",
    "normative_tier": "NORMA",
    "edicion": "Edición 10, noviembre de 2025",
    "effective_date": "2025-11-01",
    "current_version": 10,
    "summary": "El objeto de este Manual es establecer el conjunto de políticas y procedimientos que han de observarse en GARRIGUES en atención a su condición de sujeto obligado por la Ley 10/2010, de 18 [sic en el documento fuente: la Ley 10/2010 es de 28 de abril] de abril, de prevención del blanqueo de capitales y de la financiación del terrorismo. La citada Ley 10/2010 establece que sus disposiciones (y, por ende, el régimen de obligaciones que en ella se contiene) son de aplicación, entre otros, a los siguientes sujetos obligados y con el ámbito objetivo (por tipo de actuación o de asunto profesional) que se indica a continuación: (i) Los asesores fiscales (conforme a lo previsto en la letra “m” del artículo 2.1. de la citada Ley, según el cual son sujetos obligados “los auditores de cuentas, contables externos, asesores fiscales y cualquier otra persona que se comprometa a prestar de manera directa o a través de otras personas relacionadas, ayuda material, asistencia o asesoramiento en cuestiones fiscales como actividad empresarial o profesional principal”). (ii) Los abogados, u otros profesionales independientes, cuando (según indica la letra “ñ” de la Ley 10/2010) participen en:  La concepción, realización o asesoramiento de operaciones por cuenta de clientes relativas a la compraventa de bienes inmuebles o entidades comerciales.  La gestión de fondos, valores u otros activos.  La apertura o gestión de cuentas corrientes, cuentas de ahorros o cuentas de valores.  La organización de las aportaciones necesarias para la creación, el funcionamiento o la gestión de empresas.  La creación, el funcionamiento o la gestión de fideicomisos (trusts), sociedades o estructuras análogas.  cuando actúen, por cuenta de clientes, en cualquier operación financiera o inmobiliaria. (iii) Las personas que con carácter profesional, cuando (según indica la letra “o” del artículo 2.1 de la Ley 10/2010) con arreglo a la normativa específica que en cada caso sea aplicable presten los siguientes servicios por cuenta de terceros: ejercer funciones de dirección o de secretarios no consejeros de consejo de administración o de asesoría externa de una sociedad, socio de una asociación o funciones similares en relación con otras personas jurídicas o disponer que otra persona ejerza dichas funciones. En caso de duda sobre si determinados servicios están, o no, sujetos a la normativa de prevención del blanqueo de capitales y la financiación del terrorismo, podrá consultarse el listado que se encuentra disponible en nuestra Intranet de servicios que se prestan por las sociedades del grupo GARRIGUES incluidas en el ámbito subjetivo de este Manual y el criterio de clasificación general aplicable en el Despacho, conforme al criterio conservador que venimos considerando en línea con la política general de aplicar las medidas de diligencia debida previstas en este Manual aun cuando, por el tipo de servicio, no estemos en el ámbito objetivo de la Ley 10/2010. Dicho listado se adjunta, asimismo, a este Manual como Anexo 0.",
    "content_outline": [
      "1. Introducción",
      "1.1 Aprobación del Manual y sucesivas actualizaciones",
      "1.2 Marco legal aplicable",
      "2. Definición del Blanqueo de Capitales y de la Financiación del terrorismo",
      "3. Ámbito de aplicación",
      "3.1 Ámbito de aplicación objetivo",
      "3.2 Ámbito de aplicación subjetivo: destinatarios del Manual",
      "4. Obligaciones y procedimientos de control interno. Análisis interno de riesgo",
      "5. Política de admisión de nuevos clientes. Estratificación de clientes en función del riesgo",
      "5.1 Clientes que no pueden ser admitidos",
      "5.2 Estratificación de clientes en función del riesgo",
      "5.2.1 Clientes de riesgo estándar",
      "5.2.2 Clientes de riesgo inferior al riesgo promedio",
      "5.2.3 Clientes de riesgo superior al riesgo promedio (sujetos a autorización)",
      "5.3 Procedimiento formal de admisión de nuevos clientes o asuntos y sistema de archivo de la documentación e información recabada",
      "6. Medidas de diligencia debida",
      "6.1 Principios básicos y reglas generales",
      "6.2 Medidas normales de diligencia debida",
      "6.2.1 Identificación formal y comprobación de la identidad del cliente",
      "6.2.2 Identificación del titular real y de la estructura de propiedad o control",
      "6.2.3 Propósito e índole de la relación de negocios",
      "6.2.4 Seguimiento continuo de la relación de negocios",
      "6.2.5 Aplicación por terceros de las medidas de diligencia debida",
      "6.3 Medidas simplificadas de diligencia debida",
      "6.3.1 Identificación del cliente",
      "6.3.2 Conocimiento de la actividad profesional o empresarial del cliente",
      "6.3.3 Seguimiento continuo de la relación de negocio",
      "6.4 Medidas reforzadas de diligencia debida",
      "6.4.1 Comprobación del titular real",
      "6.4.2 Conocimiento de la actividad profesional o empresarial del cliente",
      "6.4.3 Origen de los fondos",
      "6.4.4 Otras medidas adicionales",
      "6.4.5 Autorización directiva",
      "6.4.6 Seguimiento continuo de la relación de negocio",
      "6.4.7 Requisitos en las relaciones de negocio y operaciones no presenciales",
      "7. Obligaciones de información",
      "7.1 Procedimiento para la detección de hechos u operaciones sujetos a examen especial",
      "7.1.1 Alertas informatizadas",
      "7.1.2 Detección y comunicación interna de operaciones de riesgo por los profesionales",
      "7.2 Procedimiento de examen especial",
      "7.3 Abstención de ejecución",
      "7.4 Prohibición de revelación",
      "7.5 Colaboración con la Comisión de Prevención del Blanqueo de Capitales e Infracciones Monetarias y con sus órganos de apoyo",
      "7.6 Comunicación de infracciones al SEPBLAC",
      "7.7 Conservación de documentos",
      "8. Medidas de control interno",
      "8.1 Órganos de control interno de GARRIGUES",
      "8.1.1 Órgano de administración",
      "8.1.2 Representante de GARRIGUES ante el SEPBLAC",
      "8.1.3 Comité de Análisis y Control Interno (CACI)",
      "8.1.4 Unidad Técnica para el Tratamiento y Análisis de la Información",
      "8.2 Medidas de control interno a nivel de grupo",
      "8.3 Procedimiento interno de comunicación de potenciales incumplimientos",
      "8.4 Examen de experto externo",
      "8.5 Medidas de difusión del presente Manual y acciones formativas",
      "8.6 Establecimiento de procedimientos o medidas para garantizar altos estándares éticos en la contratación",
      "8.7 Procedimiento de verificación periódica de la adecuación y eficacia de las medidas de control interno",
      "8.8 Medidas aplicables para verificar el cumplimiento de los procedimientos de control interno",
      "9. Disponibilidad, revisión y actualización del Manual",
      "10. Tratamiento de datos derivado del cumplimiento de las obligaciones establecidas en la Ley 10/2010",
      "11. Histórico de versiones",
      "12. Anexos"
    ],
    "source_file": "Manual PBC_FT v.10 noviembre 2025.pdf",
    "provenance": "PDF_EXTRAIDO"
  },
  {
    "policy_code": "PPD-CAT",
    "title": "Catálogo ejemplificativo de situaciones susceptibles de generar riesgos penales",
    "normative_tier": "DOCUMENTO",
    "edicion": null,
    "effective_date": null,
    "current_version": 1,
    "summary": "El presente documento recopila, en un único Catálogo ejemplificativo, las referidas situaciones identificadas por los responsables de los distintos Departamentos de práctica1 , con el fin de servir de orientación a todos los profesionales de Garrigues y facilitarles la identificación de situaciones susceptibles de generar riesgos penales en las distintas áreas en las que el Despacho desarrolla su actividad. Es importante señalar que este Catálogo es meramente ejemplificativo (en tanto incluye un listado de situaciones que, como mera hipótesis, pudieran plantearse), sin que, por tanto, constituya una lista cerrada que enumere todas las posibles situaciones susceptibles de generar riesgos penales, ni implique que todos los supuestos incluidos en la misma hayan de estar (necesariamente y en todos los casos) vinculados con una conducta delictiva.",
    "content_outline": [],
    "source_file": "Catálogo ejemplificativo de situaciones susceptibles de generar riesgos penales Dentro de los elementos de ejecución de la prevención del Programa de Prevención de Delitos (en adelante, “PPD”) de Garrigues, los responsables de Depart.md",
    "provenance": "PDF_EXTRAIDO"
  },
  {
    "policy_code": "CCS",
    "title": "Código de Conducta del Socio",
    "normative_tier": "POLITICA",
    "edicion": null,
    "effective_date": null,
    "current_version": 1,
    "summary": null,
    "content_outline": [],
    "source_file": null,
    "provenance": "CITADO_NO_INCORPORADO"
  },
  {
    "policy_code": "LGTBI-01",
    "title": "Medidas para la igualdad de las personas LGTBI y protocolo",
    "normative_tier": "PROCEDIMIENTO",
    "edicion": null,
    "effective_date": null,
    "current_version": 1,
    "summary": "En aplicación de las políticas de responsabilidad corporativa y principios éticos y de conducta, J&A Garrigues, S.L.P (en adelante, Garrigues) mantiene un compromiso permanente con el respeto y promoción de los derechos humanos reconocidos internacionalmente en el ámbito de influencia de las empresas, promoviendo un entorno laboral seguro y saludable, caracterizado por la igualdad de oportunidades y la no discriminación, el fomento de la diversidad, la gestión del talento y la conciliación de la vida profesional y personal. Tal y como estable el artículo 37 del Código Ético, Garrigues no permite, ni tolera, la discriminación por razón de raza, color, nacionalidad, origen social, edad, sexo, estado civil, orientación sexual, ideología, opiniones políticas, religión o cualquier otra condición personal, física o social de sus miembros, y promueve la igualdad de oportunidades. En particular, Garrigues promueve la igualdad y el respeto a las personas LGTBI y rechaza cualquier manifestación de acoso, abuso de autoridad, violencia o cualesquiera otras conductas que generen un entorno de trabajo intimidatorio u ofensivo para los derechos personales de sus miembros. Garrigues considera indispensable garantizar un entorno laboral en el que se apliquen los más altos estándares de respeto, buscando de tal manera consolidar las políticas de igualdad, diversidad y salud en el trabajo lo que requiere (i) insistir en el rechazo categórico de toda manifestación de acoso por razón de orientación e identidad sexual, expresión de género o características sexuales de las personas trabajadoras LGTBI y (ii) mejorar de manera continua sus procedimientos para prevenir, detectar y resolver dichas manifestaciones del acoso. En este sentido, este protocolo tiene por objetivo principal establecer las bases para la prevención, detección y actuación frente a situaciones de acoso por razón de orientación e identidad sexual, expresión de género o características sexuales que se puedan producir en Garrigues, realizando un análisis objetivo de las conductas relacionadas con dichos tipos de acoso.",
    "content_outline": [
      "1. Antecedentes y compromiso de Garrigues",
      "2. Ámbito de aplicación personal y territorial",
      "3. Entrada en vigor y duración",
      "4. Principios rectores",
      "5. Objetivos de las medidas para la consecución de la igualdad y no discriminación LGTBI",
      "6. Características de las medidas para la consecución de la igualdad y no discriminación LGTBI",
      "7. Áreas de actuación, objetivos y medidas concretas",
      "8. Medios y recursos para su puesta en marcha",
      "9. Seguimiento de la implantación de las medidas para la Igualdad de las personas LGTBI",
      "10. Procedimiento de modificación y revisión",
      "11. Protocolo de actuación para la atención del acoso o la violencia contra las personas LGTBI",
      "12. Protección de datos personales Anexo 1 Anexo 2"
    ],
    "source_file": "Medidas_para_la_igualdad_de_las_personas_LGTBI_y_protocolo.pdf",
    "provenance": "PDF_EXTRAIDO"
  }
];
