-- Migration 000012 Part 3b — Rule pack versions 1-5

-- 1. APROBACION_CUENTAS v1.0.0
INSERT INTO rule_pack_versions (pack_id, version, payload, is_active) VALUES (
  'APROBACION_CUENTAS', '1.0.0',
  '{"id":"APROBACION_CUENTAS","materia":"APROBACION_CUENTAS","clase":"ORDINARIA","organoTipo":"JUNTA_GENERAL","modosAdopcionPermitidos":["MEETING","UNIVERSAL"],"convocatoria":{"antelacionDias":{"SA":{"valor":15,"fuente":"LEY","referencia":"art. 176.1 LSC"},"SL":{"valor":15,"fuente":"LEY","referencia":"art. 176.1 LSC"}},"canales":{"SA":["BORME","WEB_INSCRITA","PUBLICACION_ESTATUTOS"],"SL":["COMUNICACION_INDIVIDUAL_ESCRITA"]},"contenidoMinimo":["Fecha hora y lugar","Orden del día con indicación de asuntos","Cargo o nombre de quien convoca"],"documentosObligatorios":[{"id":"cuentas_anuales","nombre":"Cuentas anuales formuladas","condicion":"SIEMPRE"},{"id":"informe_gestion","nombre":"Informe de gestión","condicion":"SIEMPRE"},{"id":"informe_auditoria","nombre":"Informe de auditoría","condicion":"SI_AUDITORIA_OBLIGATORIA"},{"id":"propuesta_aplicacion_resultado","nombre":"Propuesta de aplicación del resultado","condicion":"SIEMPRE"}]},"constitucion":{"quorum":{"SA_1a":{"valor":0.25,"fuente":"LEY","referencia":"art. 193.1 LSC"},"SA_2a":{"valor":0,"fuente":"LEY","referencia":"art. 193.1 LSC"},"SL":{"valor":0,"fuente":"LEY","referencia":"art. 198 LSC"},"CONSEJO":{"valor":"mayoria_miembros","fuente":"LEY","referencia":"art. 247.1 LSC"}}},"votacion":{"mayoria":{"SA":{"formula":"favor > contra","fuente":"LEY","referencia":"art. 201.1 LSC"},"SL":{"formula":"favor > mitad_capital_con_voto","fuente":"LEY","referencia":"art. 198 LSC"},"CONSEJO":{"formula":"favor > presentes_mitad","fuente":"LEY","referencia":"art. 248.1 LSC"}},"abstenciones":"no_cuentan","votoCalidadPermitido":false},"documentacion":{"obligatoria":[{"id":"cuentas_anuales","nombre":"Cuentas anuales firmadas por todos los administradores"},{"id":"informe_gestion","nombre":"Informe de gestión del ejercicio"},{"id":"informe_auditoria","nombre":"Informe de auditoría (si obligatoria)","condicion":"SI_AUDITORIA"}],"ventanaDisponibilidad":{"dias":15,"fuente":"LEY"}},"acta":{"tipoActaPorModo":{"MEETING":"ACTA_JUNTA","UNIVERSAL":"ACTA_JUNTA"},"contenidoMinimo":{"sesion":["Fecha y lugar","Lista de asistentes","Orden del día","Votaciones y resultados","Acuerdos adoptados"],"consignacion":[],"acuerdoEscrito":[]},"requiereTranscripcionLibroActas":true,"requiereConformidadConjunta":false},"plazosMateriales":{"inscripcion":null,"publicacion":[],"oposicion_acreedores":null},"postAcuerdo":{"inscribible":false,"instrumentoRequerido":"NINGUNO","publicacionRequerida":false}}'::jsonb,
  true
) ON CONFLICT (pack_id, version) DO UPDATE SET payload = EXCLUDED.payload, is_active = true;

-- 2. DISTRIBUCION_DIVIDENDOS v1.0.0
INSERT INTO rule_pack_versions (pack_id, version, payload, is_active) VALUES (
  'DISTRIBUCION_DIVIDENDOS', '1.0.0',
  '{"id":"DISTRIBUCION_DIVIDENDOS","materia":"DISTRIBUCION_DIVIDENDOS","clase":"ORDINARIA","organoTipo":"JUNTA_GENERAL","modosAdopcionPermitidos":["MEETING","UNIVERSAL"],"convocatoria":{"antelacionDias":{"SA":{"valor":15,"fuente":"LEY","referencia":"art. 176.1 LSC"},"SL":{"valor":15,"fuente":"LEY"}},"canales":{"SA":["BORME","WEB_INSCRITA","PUBLICACION_ESTATUTOS"],"SL":["COMUNICACION_INDIVIDUAL_ESCRITA"]},"contenidoMinimo":["Fecha hora y lugar","Orden del día","Propuesta de distribución"],"documentosObligatorios":[{"id":"propuesta_distribucion","nombre":"Propuesta de distribución de dividendos","condicion":"SIEMPRE"},{"id":"informe_liquidez","nombre":"Informe de liquidez (art. 348 LSC)","condicion":"SI_SL"}]},"constitucion":{"quorum":{"SA_1a":{"valor":0.25,"fuente":"LEY","referencia":"art. 193.1 LSC"},"SA_2a":{"valor":0,"fuente":"LEY"},"SL":{"valor":0,"fuente":"LEY"},"CONSEJO":{"valor":"mayoria_miembros","fuente":"LEY","referencia":"art. 247.1 LSC"}}},"votacion":{"mayoria":{"SA":{"formula":"favor > contra","fuente":"LEY","referencia":"art. 201.1 LSC"},"SL":{"formula":"favor > mitad_capital_con_voto","fuente":"LEY","referencia":"art. 198 LSC"},"CONSEJO":{"formula":"favor > presentes_mitad","fuente":"LEY","referencia":"art. 248.1 LSC"}},"abstenciones":"no_cuentan","votoCalidadPermitido":false},"documentacion":{"obligatoria":[{"id":"propuesta_distribucion","nombre":"Propuesta de distribución de dividendos"},{"id":"cuentas_aprobadas","nombre":"Cuentas anuales ya aprobadas (condición previa)"}],"ventanaDisponibilidad":{"dias":15,"fuente":"LEY"}},"acta":{"tipoActaPorModo":{"MEETING":"ACTA_JUNTA","UNIVERSAL":"ACTA_JUNTA"},"requiereTranscripcionLibroActas":true,"requiereConformidadConjunta":false},"plazosMateriales":{},"postAcuerdo":{"inscribible":false,"instrumentoRequerido":"NINGUNO","publicacionRequerida":false}}'::jsonb,
  true
) ON CONFLICT (pack_id, version) DO UPDATE SET payload = EXCLUDED.payload, is_active = true;

-- 3. NOMBRAMIENTO_CONSEJERO v1.0.0
INSERT INTO rule_pack_versions (pack_id, version, payload, is_active) VALUES (
  'NOMBRAMIENTO_CONSEJERO', '1.0.0',
  '{"id":"NOMBRAMIENTO_CONSEJERO","materia":"NOMBRAMIENTO_CONSEJERO","clase":"ORDINARIA","organoTipo":"JUNTA_GENERAL","modosAdopcionPermitidos":["MEETING","UNIVERSAL"],"convocatoria":{"antelacionDias":{"SA":{"valor":15,"fuente":"LEY","referencia":"art. 176.1 LSC"},"SL":{"valor":15,"fuente":"LEY"}},"canales":{"SA":["BORME","WEB_INSCRITA","PUBLICACION_ESTATUTOS"],"SL":["COMUNICACION_INDIVIDUAL_ESCRITA"]},"contenidoMinimo":["Fecha hora y lugar","Orden del día con identificación del candidato","Categoría propuesta del consejero"],"documentosObligatorios":[{"id":"cv_candidato","nombre":"Currículum vitae del candidato","condicion":"SIEMPRE"},{"id":"informe_comision_nombramientos","nombre":"Informe de la Comisión de Nombramientos","condicion":"SI_COTIZADA"}]},"constitucion":{"quorum":{"SA_1a":{"valor":0.25,"fuente":"LEY","referencia":"art. 193.1 LSC"},"SA_2a":{"valor":0,"fuente":"LEY"},"SL":{"valor":0,"fuente":"LEY"},"CONSEJO":{"valor":"mayoria_miembros","fuente":"LEY","referencia":"art. 247.1 LSC"}}},"votacion":{"mayoria":{"SA":{"formula":"favor > contra","fuente":"LEY","referencia":"art. 201.1 LSC"},"SL":{"formula":"favor > mitad_capital_con_voto","fuente":"LEY","referencia":"art. 198 LSC"},"CONSEJO":{"formula":"favor > presentes_mitad","fuente":"LEY","referencia":"art. 247.1 LSC"}},"abstenciones":"no_cuentan","votoCalidadPermitido":false},"documentacion":{"obligatoria":[{"id":"cv_candidato","nombre":"CV del candidato"},{"id":"declaracion_idoneidad","nombre":"Declaración de idoneidad y aceptación del cargo"}],"ventanaDisponibilidad":{"dias":15,"fuente":"LEY"}},"acta":{"tipoActaPorModo":{"MEETING":"ACTA_JUNTA","UNIVERSAL":"ACTA_JUNTA"},"requiereTranscripcionLibroActas":true,"requiereConformidadConjunta":false},"plazosMateriales":{"inscripcion":{"plazo_dias":30,"fuente":"LEY","referencia":"art. 17 RRM"}},"postAcuerdo":{"inscribible":true,"instrumentoRequerido":"ESCRITURA","publicacionRequerida":false,"plazoInscripcion":{"dias":30,"fuente":"LEY","referencia":"art. 17 RRM"}}}'::jsonb,
  true
) ON CONFLICT (pack_id, version) DO UPDATE SET payload = EXCLUDED.payload, is_active = true;

-- 4. CESE_CONSEJERO v1.0.0
INSERT INTO rule_pack_versions (pack_id, version, payload, is_active) VALUES (
  'CESE_CONSEJERO', '1.0.0',
  '{"id":"CESE_CONSEJERO","materia":"CESE_CONSEJERO","clase":"ORDINARIA","organoTipo":"JUNTA_GENERAL","modosAdopcionPermitidos":["MEETING","UNIVERSAL"],"convocatoria":{"antelacionDias":{"SA":{"valor":15,"fuente":"LEY","referencia":"art. 176.1 LSC"},"SL":{"valor":15,"fuente":"LEY"}},"canales":{"SA":["BORME","WEB_INSCRITA","PUBLICACION_ESTATUTOS"],"SL":["COMUNICACION_INDIVIDUAL_ESCRITA"]},"contenidoMinimo":["Fecha hora y lugar","Orden del día identificando al consejero afectado"],"documentosObligatorios":[]},"constitucion":{"quorum":{"SA_1a":{"valor":0.25,"fuente":"LEY","referencia":"art. 193.1 LSC"},"SA_2a":{"valor":0,"fuente":"LEY"},"SL":{"valor":0,"fuente":"LEY"},"CONSEJO":{"valor":"mayoria_miembros","fuente":"LEY","referencia":"art. 247.1 LSC"}}},"votacion":{"mayoria":{"SA":{"formula":"favor > contra","fuente":"LEY","referencia":"art. 223.1 LSC — libre separación"},"SL":{"formula":"favor > mitad_capital_con_voto","fuente":"LEY","referencia":"art. 223.1 LSC"},"CONSEJO":{"formula":"favor > presentes_mitad","fuente":"LEY","referencia":"art. 247.1 LSC"}},"abstenciones":"no_cuentan","votoCalidadPermitido":false},"documentacion":{"obligatoria":[],"ventanaDisponibilidad":{"dias":15,"fuente":"LEY"}},"acta":{"tipoActaPorModo":{"MEETING":"ACTA_JUNTA","UNIVERSAL":"ACTA_JUNTA"},"requiereTranscripcionLibroActas":true,"requiereConformidadConjunta":false},"plazosMateriales":{"inscripcion":{"plazo_dias":30,"fuente":"LEY","referencia":"art. 17 RRM"}},"postAcuerdo":{"inscribible":true,"instrumentoRequerido":"ESCRITURA","publicacionRequerida":false,"plazoInscripcion":{"dias":30,"fuente":"LEY","referencia":"art. 17 RRM"}}}'::jsonb,
  true
) ON CONFLICT (pack_id, version) DO UPDATE SET payload = EXCLUDED.payload, is_active = true;

-- 5. DELEGACION_FACULTADES v1.0.0
INSERT INTO rule_pack_versions (pack_id, version, payload, is_active) VALUES (
  'DELEGACION_FACULTADES', '1.0.0',
  '{"id":"DELEGACION_FACULTADES","materia":"DELEGACION_FACULTADES","clase":"ORDINARIA","organoTipo":"CONSEJO","modosAdopcionPermitidos":["MEETING"],"convocatoria":{"antelacionDias":{"SA":{"valor":0,"fuente":"LEY","referencia":"art. 246.1 LSC"},"SL":{"valor":0,"fuente":"LEY"}},"canales":{"SA":["CONVOCATORIA_CONSEJO"],"SL":["CONVOCATORIA_CONSEJO"]},"contenidoMinimo":["Fecha hora y lugar","Materias a deliberar"],"documentosObligatorios":[{"id":"borrador_delegacion","nombre":"Borrador del acuerdo de delegación","condicion":"SIEMPRE"}]},"constitucion":{"quorum":{"CONSEJO":{"valor":"mayoria_miembros","fuente":"LEY","referencia":"art. 247.1 LSC"}}},"votacion":{"mayoria":{"SA":{"formula":"favor > presentes_mitad","fuente":"LEY","referencia":"art. 247.1 LSC"},"SL":{"formula":"favor > presentes_mitad","fuente":"LEY"},"CONSEJO":{"formula":"favor > presentes_mitad","fuente":"LEY","referencia":"art. 247.1 LSC"}},"abstenciones":"no_cuentan","votoCalidadPermitido":true},"documentacion":{"obligatoria":[{"id":"listado_facultades","nombre":"Listado completo de facultades delegadas"},{"id":"exclusion_249bis","nombre":"Verificación de exclusión de materias indelegables art. 249 bis LSC"}],"ventanaDisponibilidad":{"dias":0,"fuente":"LEY"}},"acta":{"tipoActaPorModo":{"MEETING":"ACTA_CONSEJO"},"requiereTranscripcionLibroActas":true,"requiereConformidadConjunta":false},"plazosMateriales":{"inscripcion":{"plazo_dias":30,"fuente":"LEY","referencia":"art. 17 RRM"}},"postAcuerdo":{"inscribible":true,"instrumentoRequerido":"ESCRITURA","publicacionRequerida":false,"plazoInscripcion":{"dias":30,"fuente":"LEY","referencia":"art. 249.3 LSC"}}}'::jsonb,
  true
) ON CONFLICT (pack_id, version) DO UPDATE SET payload = EXCLUDED.payload, is_active = true;
