-- Migration 000017 Part 2 — v1.1.0 updates for 5 existing packs

INSERT INTO rule_pack_versions (pack_id, version, payload, is_active) VALUES (
  'DELEGACION_FACULTADES', '1.1.0',
  '{"id":"DELEGACION_FACULTADES","materia":"DELEGACION_FACULTADES","clase":"ORDINARIA","organoTipo":"CONSEJO","modosAdopcionPermitidos":["MEETING","NO_SESSION"],"convocatoria":{"antelacionDias":{"SA":{"valor":0,"fuente":"LEY","referencia":"art. 246.1 LSC"},"SL":{"valor":0,"fuente":"LEY"}},"canales":{"SA":["CONVOCATORIA_CONSEJO"],"SL":["CONVOCATORIA_CONSEJO"]},"contenidoMinimo":["Fecha hora y lugar","Materias a deliberar","Identificación del delegado y alcance"],"documentosObligatorios":[{"id":"borrador_delegacion","nombre":"Borrador del acuerdo de delegación","condicion":"SIEMPRE"},{"id":"verificacion_249bis","nombre":"Verificación de exclusión de materias indelegables art. 249 bis LSC","condicion":"SIEMPRE"}]},"constitucion":{"quorum":{"CONSEJO":{"valor":"mayoria_miembros","fuente":"LEY","referencia":"art. 247.1 LSC"}}},"votacion":{"mayoria":{"SA":{"formula":"favor > total_miembros / 2","fuente":"LEY","referencia":"art. 247.2 LSC"},"SL":{"formula":"favor > total_miembros / 2","fuente":"LEY"},"CONSEJO":{"formula":"favor > total_miembros / 2","fuente":"LEY","referencia":"art. 247.2 LSC"}},"abstenciones":"no_cuentan","votoCalidadPermitido":true},"documentacion":{"obligatoria":[{"id":"listado_facultades","nombre":"Listado completo de facultades delegadas"},{"id":"exclusion_249bis","nombre":"Verificación de exclusión art. 249 bis LSC"}],"ventanaDisponibilidad":{"dias":0,"fuente":"LEY"}},"acta":{"tipoActaPorModo":{"MEETING":"ACTA_CONSEJO","NO_SESSION":"ACTA_ACUERDO_ESCRITO"},"requiereTranscripcionLibroActas":true,"requiereConformidadConjunta":false},"plazosMateriales":{"inscripcion":{"plazo_dias":30,"fuente":"LEY","referencia":"art. 17 RRM"}},"postAcuerdo":{"inscribible":true,"instrumentoRequerido":"ESCRITURA","plazoInscripcionDias":30,"publicacionRequerida":false}}'::jsonb,
  true
) ON CONFLICT (pack_id, version) DO UPDATE SET payload = EXCLUDED.payload, is_active = true;

INSERT INTO rule_pack_versions (pack_id, version, payload, is_active) VALUES (
  'OPERACION_VINCULADA', '1.1.0',
  '{"id":"OPERACION_VINCULADA","materia":"OPERACION_VINCULADA","clase":"ORDINARIA","organoTipo":"CONSEJO","modosAdopcionPermitidos":["MEETING","NO_SESSION"],"convocatoria":{"antelacionDias":{"SA":{"valor":0,"fuente":"LEY"},"SL":{"valor":0,"fuente":"LEY"}},"canales":{"SA":["CONVOCATORIA_CONSEJO"],"SL":["CONVOCATORIA_CONSEJO"]},"contenidoMinimo":["Identificación parte vinculada y naturaleza del vínculo","Condiciones económicas","Declaración de abstención"],"documentosObligatorios":[{"id":"informe_condiciones_mercado","nombre":"Informe de condiciones de mercado","condicion":"SIEMPRE"},{"id":"informe_comision_auditoria","nombre":"Informe favorable Comisión Auditoría (cotizadas)","condicion":"SI_COTIZADA"}]},"constitucion":{"quorum":{"CONSEJO":{"valor":"mayoria_miembros","fuente":"LEY","referencia":"art. 247.1 LSC"}}},"votacion":{"mayoria":{"SA":{"formula":"favor > total_miembros / 2","fuente":"LEY"},"SL":{"formula":"favor > total_miembros / 2","fuente":"LEY"},"CONSEJO":{"formula":"favor > total_miembros / 2","fuente":"LEY","referencia":"art. 228.e LSC"}},"abstenciones":"cuentan_como_contra","nota_abstenciones":"Abstenciones de consejeros vinculados computan como contra (arts. 228-229 LSC)","votoCalidadPermitido":false},"documentacion":{"obligatoria":[{"id":"informe_valoracion","nombre":"Informe de valoración"},{"id":"declaracion_vinculacion","nombre":"Declaración de la parte vinculada"}],"ventanaDisponibilidad":{"dias":0,"fuente":"LEY"}},"acta":{"tipoActaPorModo":{"MEETING":"ACTA_CONSEJO","NO_SESSION":"ACTA_ACUERDO_ESCRITO"},"requiereTranscripcionLibroActas":true,"requiereConformidadConjunta":false},"plazosMateriales":{},"postAcuerdo":{"inscribible":false,"instrumentoRequerido":"NINGUNO","plazoInscripcionDias":0,"publicacionRequerida":false}}'::jsonb,
  true
) ON CONFLICT (pack_id, version) DO UPDATE SET payload = EXCLUDED.payload, is_active = true;

INSERT INTO rule_pack_versions (pack_id, version, payload, is_active) VALUES (
  'NOMBRAMIENTO_AUDITOR', '1.1.0',
  '{"id":"NOMBRAMIENTO_AUDITOR","materia":"NOMBRAMIENTO_AUDITOR","clase":"ORDINARIA","organoTipo":"JUNTA_GENERAL","modosAdopcionPermitidos":["MEETING","UNIVERSAL"],"convocatoria":{"antelacionDias":{"SA":{"valor":15,"fuente":"LEY","referencia":"art. 176.1 LSC"},"SL":{"valor":15,"fuente":"LEY"}},"canales":{"SA":["BORME","WEB_INSCRITA"],"SL":["COMUNICACION_INDIVIDUAL_ESCRITA"]},"contenidoMinimo":["Fecha hora y lugar","Identificación del auditor o firma auditora (nombre + ROAC)","Duración mínimo 3 años (art. 264.1 LSC)"],"documentosObligatorios":[{"id":"propuesta_comision_auditoria","nombre":"Propuesta motivada Comisión Auditoría","condicion":"SI_COTIZADA"},{"id":"declaracion_independencia","nombre":"Declaración independencia del auditor","condicion":"SIEMPRE"}]},"constitucion":{"quorum":{"SA_1a":{"valor":0.25,"fuente":"LEY","referencia":"art. 193.1 LSC"},"SA_2a":{"valor":0,"fuente":"LEY"},"SL":{"valor":0,"fuente":"LEY"},"CONSEJO":{"valor":"mayoria_miembros","fuente":"LEY"}}},"votacion":{"mayoria":{"SA":{"formula":"favor > 0.5 * capital_presente","fuente":"LEY","referencia":"art. 201.1 LSC"},"SL":{"formula":"favor > mitad_capital_con_voto","fuente":"LEY","referencia":"art. 198 LSC"},"CONSEJO":{"formula":"favor > presentes_mitad","fuente":"LEY"}},"abstenciones":"no_cuentan","votoCalidadPermitido":false},"documentacion":{"obligatoria":[{"id":"propuesta_nombramiento","nombre":"Propuesta de nombramiento con duración"},{"id":"declaracion_independencia_auditor","nombre":"Declaración independencia (art. 21 LAC)"}],"ventanaDisponibilidad":{"dias":15,"fuente":"LEY"}},"acta":{"tipoActaPorModo":{"MEETING":"ACTA_JUNTA","UNIVERSAL":"ACTA_JUNTA"},"requiereTranscripcionLibroActas":true,"requiereConformidadConjunta":false},"plazosMateriales":{"inscripcion":{"plazo_dias":30,"fuente":"LEY","referencia":"art. 17 RRM"}},"postAcuerdo":{"inscribible":true,"instrumentoRequerido":"NINGUNO","plazoInscripcionDias":30,"publicacionRequerida":false}}'::jsonb,
  true
) ON CONFLICT (pack_id, version) DO UPDATE SET payload = EXCLUDED.payload, is_active = true;

INSERT INTO rule_pack_versions (pack_id, version, payload, is_active) VALUES (
  'AUTORIZACION_GARANTIA', '1.1.0',
  '{"id":"AUTORIZACION_GARANTIA","materia":"AUTORIZACION_GARANTIA","clase":"ORDINARIA","organoTipo":"CONSEJO","modosAdopcionPermitidos":["MEETING","NO_SESSION"],"nota":"Para garantías cuyo importe NO supera el 25% activos — competencia del Consejo (art. 249 bis + 160.f LSC).","convocatoria":{"antelacionDias":{"SA":{"valor":0,"fuente":"LEY"},"SL":{"valor":0,"fuente":"LEY"}},"canales":{"SA":["CONVOCATORIA_CONSEJO"],"SL":["CONVOCATORIA_CONSEJO"]},"contenidoMinimo":["Naturaleza y cuantía de la garantía","Beneficiario","Análisis de riesgo"],"documentosObligatorios":[{"id":"descripcion_garantia","nombre":"Descripción de la garantía","condicion":"SIEMPRE"},{"id":"verificacion_umbral_160f","nombre":"Verificación umbral 25% activos (art. 160.f LSC)","condicion":"SIEMPRE"}]},"constitucion":{"quorum":{"CONSEJO":{"valor":"mayoria_miembros","fuente":"LEY","referencia":"art. 247.1 LSC"}}},"votacion":{"mayoria":{"SA":{"formula":"favor > total_miembros / 2","fuente":"LEY"},"SL":{"formula":"favor > total_miembros / 2","fuente":"LEY"},"CONSEJO":{"formula":"favor > total_miembros / 2","fuente":"LEY"}},"abstenciones":"no_cuentan","votoCalidadPermitido":true},"documentacion":{"obligatoria":[{"id":"descripcion_garantia","nombre":"Descripción de la garantía y análisis"},{"id":"calculo_umbral","nombre":"Cálculo del porcentaje sobre activos"}],"ventanaDisponibilidad":{"dias":0,"fuente":"LEY"}},"acta":{"tipoActaPorModo":{"MEETING":"ACTA_CONSEJO","NO_SESSION":"ACTA_ACUERDO_ESCRITO"},"requiereTranscripcionLibroActas":true,"requiereConformidadConjunta":false},"plazosMateriales":{},"postAcuerdo":{"inscribible":false,"instrumentoRequerido":"NINGUNO","plazoInscripcionDias":0,"publicacionRequerida":false}}'::jsonb,
  true
) ON CONFLICT (pack_id, version) DO UPDATE SET payload = EXCLUDED.payload, is_active = true;

INSERT INTO rule_pack_versions (pack_id, version, payload, is_active) VALUES (
  'RATIFICACION_ACTOS', '1.1.0',
  '{"id":"RATIFICACION_ACTOS","materia":"RATIFICACION_ACTOS","clase":"ORDINARIA","organoTipo":"CONSEJO","modosAdopcionPermitidos":["MEETING","NO_SESSION"],"convocatoria":{"antelacionDias":{"SA":{"valor":0,"fuente":"LEY"},"SL":{"valor":0,"fuente":"LEY"}},"canales":{"SA":["CONVOCATORIA_CONSEJO"],"SL":["CONVOCATORIA_CONSEJO"]},"contenidoMinimo":["Fecha hora y lugar","Descripción de los actos a ratificar","Justificación de la urgencia"],"documentosObligatorios":[{"id":"copia_acto_contrato","nombre":"Copia del acto o contrato a ratificar","condicion":"SIEMPRE"}]},"constitucion":{"quorum":{"CONSEJO":{"valor":"mayoria_miembros","fuente":"LEY","referencia":"art. 247.1 LSC"}}},"votacion":{"mayoria":{"SA":{"formula":"favor > total_miembros / 2","fuente":"LEY"},"SL":{"formula":"favor > total_miembros / 2","fuente":"LEY"},"CONSEJO":{"formula":"favor > total_miembros / 2","fuente":"LEY"}},"abstenciones":"no_cuentan","votoCalidadPermitido":true},"documentacion":{"obligatoria":[{"id":"copia_acto","nombre":"Copia del acto ratificado"},{"id":"informe_justificacion","nombre":"Informe sobre urgencia y circunstancias"}],"ventanaDisponibilidad":{"dias":0,"fuente":"LEY"}},"acta":{"tipoActaPorModo":{"MEETING":"ACTA_CONSEJO","NO_SESSION":"ACTA_ACUERDO_ESCRITO"},"requiereTranscripcionLibroActas":true,"requiereConformidadConjunta":false},"plazosMateriales":{},"postAcuerdo":{"inscribible":false,"instrumentoRequerido":"NINGUNO","plazoInscripcionDias":0,"publicacionRequerida":false}}'::jsonb,
  true
) ON CONFLICT (pack_id, version) DO UPDATE SET payload = EXCLUDED.payload, is_active = true;
