-- Migration 000012 Part 3d — Rule pack versions 10-13

-- 10. NOMBRAMIENTO_AUDITOR v1.0.0
INSERT INTO rule_pack_versions (pack_id, version, payload, is_active) VALUES (
  'NOMBRAMIENTO_AUDITOR', '1.0.0',
  '{"id":"NOMBRAMIENTO_AUDITOR","materia":"NOMBRAMIENTO_AUDITOR","clase":"ORDINARIA","organoTipo":"JUNTA_GENERAL","modosAdopcionPermitidos":["MEETING","UNIVERSAL"],"convocatoria":{"antelacionDias":{"SA":{"valor":15,"fuente":"LEY","referencia":"art. 176.1 LSC"},"SL":{"valor":15,"fuente":"LEY"}},"canales":{"SA":["BORME","WEB_INSCRITA"],"SL":["COMUNICACION_INDIVIDUAL_ESCRITA"]},"contenidoMinimo":["Fecha hora y lugar","Identificación del auditor o firma propuesta","Duración del contrato"],"documentosObligatorios":[{"id":"propuesta_auditoria","nombre":"Propuesta de la Comisión de Auditoría (cotizadas)","condicion":"SI_COTIZADA"}]},"constitucion":{"quorum":{"SA_1a":{"valor":0.25,"fuente":"LEY","referencia":"art. 193.1 LSC"},"SA_2a":{"valor":0,"fuente":"LEY"},"SL":{"valor":0,"fuente":"LEY"},"CONSEJO":{"valor":"mayoria_miembros","fuente":"LEY","referencia":"art. 247.1 LSC"}}},"votacion":{"mayoria":{"SA":{"formula":"favor > contra","fuente":"LEY","referencia":"art. 201.1 LSC"},"SL":{"formula":"favor > mitad_capital_con_voto","fuente":"LEY","referencia":"art. 198 LSC"},"CONSEJO":{"formula":"favor > presentes_mitad","fuente":"LEY","referencia":"art. 247.1 LSC"}},"abstenciones":"no_cuentan","votoCalidadPermitido":false},"documentacion":{"obligatoria":[{"id":"propuesta_nombramiento","nombre":"Propuesta de nombramiento con duración y condiciones"}],"ventanaDisponibilidad":{"dias":15,"fuente":"LEY"}},"acta":{"tipoActaPorModo":{"MEETING":"ACTA_JUNTA","UNIVERSAL":"ACTA_JUNTA"},"requiereTranscripcionLibroActas":true,"requiereConformidadConjunta":false},"plazosMateriales":{"inscripcion":{"plazo_dias":30,"fuente":"LEY","referencia":"art. 17 RRM"}},"postAcuerdo":{"inscribible":true,"instrumentoRequerido":"NINGUNO","publicacionRequerida":false,"plazoInscripcion":{"dias":30,"fuente":"LEY","referencia":"art. 17 RRM"}}}'::jsonb,
  true
) ON CONFLICT (pack_id, version) DO UPDATE SET payload = EXCLUDED.payload, is_active = true;

-- 11. APROBACION_PLAN_NEGOCIO v1.0.0
INSERT INTO rule_pack_versions (pack_id, version, payload, is_active) VALUES (
  'APROBACION_PLAN_NEGOCIO', '1.0.0',
  '{"id":"APROBACION_PLAN_NEGOCIO","materia":"APROBACION_PLAN_NEGOCIO","clase":"ORDINARIA","organoTipo":"CONSEJO","modosAdopcionPermitidos":["MEETING"],"convocatoria":{"antelacionDias":{"SA":{"valor":0,"fuente":"LEY"},"SL":{"valor":0,"fuente":"LEY"}},"canales":{"SA":["CONVOCATORIA_CONSEJO"],"SL":["CONVOCATORIA_CONSEJO"]},"contenidoMinimo":["Fecha hora y lugar","Presentación del plan de negocio"],"documentosObligatorios":[{"id":"plan_negocio","nombre":"Plan de negocio o estratégico del ejercicio","condicion":"SIEMPRE"}]},"constitucion":{"quorum":{"CONSEJO":{"valor":"mayoria_miembros","fuente":"LEY","referencia":"art. 247.1 LSC"}}},"votacion":{"mayoria":{"SA":{"formula":"favor > presentes_mitad","fuente":"LEY","referencia":"art. 247.1 LSC"},"SL":{"formula":"favor > presentes_mitad","fuente":"LEY"},"CONSEJO":{"formula":"favor > presentes_mitad","fuente":"LEY","referencia":"art. 247.1 LSC"}},"abstenciones":"no_cuentan","votoCalidadPermitido":true},"documentacion":{"obligatoria":[{"id":"plan_negocio_doc","nombre":"Documento del plan de negocio aprobado"}],"ventanaDisponibilidad":{"dias":0,"fuente":"LEY"}},"acta":{"tipoActaPorModo":{"MEETING":"ACTA_CONSEJO"},"requiereTranscripcionLibroActas":true,"requiereConformidadConjunta":false},"plazosMateriales":{},"postAcuerdo":{"inscribible":false,"instrumentoRequerido":"NINGUNO","publicacionRequerida":false}}'::jsonb,
  true
) ON CONFLICT (pack_id, version) DO UPDATE SET payload = EXCLUDED.payload, is_active = true;

-- 12. AUTORIZACION_GARANTIA v1.0.0
INSERT INTO rule_pack_versions (pack_id, version, payload, is_active) VALUES (
  'AUTORIZACION_GARANTIA', '1.0.0',
  '{"id":"AUTORIZACION_GARANTIA","materia":"AUTORIZACION_GARANTIA","clase":"ORDINARIA","organoTipo":"JUNTA_GENERAL","modosAdopcionPermitidos":["MEETING","UNIVERSAL"],"convocatoria":{"antelacionDias":{"SA":{"valor":15,"fuente":"LEY","referencia":"art. 176.1 LSC — si >25% activo: competencia JGA art. 160.f LSC"},"SL":{"valor":15,"fuente":"LEY"}},"canales":{"SA":["BORME","WEB_INSCRITA"],"SL":["COMUNICACION_INDIVIDUAL_ESCRITA"]},"contenidoMinimo":["Fecha hora y lugar","Naturaleza y cuantía de la garantía","Beneficiario y operación garantizada"],"documentosObligatorios":[{"id":"descripcion_garantia","nombre":"Descripción de la garantía y evaluación del riesgo","condicion":"SIEMPRE"}]},"constitucion":{"quorum":{"SA_1a":{"valor":0.25,"fuente":"LEY","referencia":"art. 193.1 LSC"},"SA_2a":{"valor":0,"fuente":"LEY"},"SL":{"valor":0,"fuente":"LEY"},"CONSEJO":{"valor":"mayoria_miembros","fuente":"LEY","referencia":"art. 247.1 LSC"}}},"votacion":{"mayoria":{"SA":{"formula":"favor > contra","fuente":"LEY","referencia":"art. 201.1 LSC"},"SL":{"formula":"favor > mitad_capital_con_voto","fuente":"LEY","referencia":"art. 198 LSC"},"CONSEJO":{"formula":"favor > presentes_mitad","fuente":"LEY"}},"abstenciones":"no_cuentan","votoCalidadPermitido":false},"documentacion":{"obligatoria":[{"id":"descripcion_garantia","nombre":"Descripción de la garantía y análisis de riesgo"}],"ventanaDisponibilidad":{"dias":15,"fuente":"LEY"}},"acta":{"tipoActaPorModo":{"MEETING":"ACTA_JUNTA","UNIVERSAL":"ACTA_JUNTA"},"requiereTranscripcionLibroActas":true,"requiereConformidadConjunta":false},"plazosMateriales":{},"postAcuerdo":{"inscribible":false,"instrumentoRequerido":"NINGUNO","publicacionRequerida":false}}'::jsonb,
  true
) ON CONFLICT (pack_id, version) DO UPDATE SET payload = EXCLUDED.payload, is_active = true;

-- 13. RATIFICACION_ACTOS v1.0.0
INSERT INTO rule_pack_versions (pack_id, version, payload, is_active) VALUES (
  'RATIFICACION_ACTOS', '1.0.0',
  '{"id":"RATIFICACION_ACTOS","materia":"RATIFICACION_ACTOS","clase":"ORDINARIA","organoTipo":"CONSEJO","modosAdopcionPermitidos":["MEETING"],"convocatoria":{"antelacionDias":{"SA":{"valor":0,"fuente":"LEY"},"SL":{"valor":0,"fuente":"LEY"}},"canales":{"SA":["CONVOCATORIA_CONSEJO"],"SL":["CONVOCATORIA_CONSEJO"]},"contenidoMinimo":["Fecha hora y lugar","Descripción de los actos o contratos a ratificar","Justificación de la urgencia"],"documentosObligatorios":[{"id":"copia_acto_contrato","nombre":"Copia del acto o contrato a ratificar","condicion":"SIEMPRE"}]},"constitucion":{"quorum":{"CONSEJO":{"valor":"mayoria_miembros","fuente":"LEY","referencia":"art. 247.1 LSC"}}},"votacion":{"mayoria":{"SA":{"formula":"favor > presentes_mitad","fuente":"LEY","referencia":"art. 247.1 LSC"},"SL":{"formula":"favor > presentes_mitad","fuente":"LEY"},"CONSEJO":{"formula":"favor > presentes_mitad","fuente":"LEY","referencia":"art. 247.1 LSC"}},"abstenciones":"no_cuentan","votoCalidadPermitido":true},"documentacion":{"obligatoria":[{"id":"copia_acto","nombre":"Copia del acto o contrato ratificado"},{"id":"informe_justificacion","nombre":"Informe sobre urgencia y circunstancias del acto previo"}],"ventanaDisponibilidad":{"dias":0,"fuente":"LEY"}},"acta":{"tipoActaPorModo":{"MEETING":"ACTA_CONSEJO"},"requiereTranscripcionLibroActas":true,"requiereConformidadConjunta":false},"plazosMateriales":{},"postAcuerdo":{"inscribible":false,"instrumentoRequerido":"NINGUNO","publicacionRequerida":false}}'::jsonb,
  true
) ON CONFLICT (pack_id, version) DO UPDATE SET payload = EXCLUDED.payload, is_active = true;
