-- Migration 000012 Part 3c — Rule pack versions 6-9

-- 6. MODIFICACION_ESTATUTOS v1.0.0
INSERT INTO rule_pack_versions (pack_id, version, payload, is_active) VALUES (
  'MODIFICACION_ESTATUTOS', '1.0.0',
  '{"id":"MODIFICACION_ESTATUTOS","materia":"MODIFICACION_ESTATUTOS","clase":"ESTATUTARIA","organoTipo":"JUNTA_GENERAL","modosAdopcionPermitidos":["MEETING","UNIVERSAL"],"convocatoria":{"antelacionDias":{"SA":{"valor":15,"fuente":"LEY","referencia":"art. 176.1 LSC"},"SL":{"valor":15,"fuente":"LEY"}},"canales":{"SA":["BORME","WEB_INSCRITA"],"SL":["COMUNICACION_INDIVIDUAL_ESCRITA"]},"contenidoMinimo":["Fecha hora y lugar","Propuesta de texto íntegro de la modificación","Texto actual y texto propuesto"],"documentosObligatorios":[{"id":"propuesta_modificacion","nombre":"Texto íntegro de la propuesta de modificación","condicion":"SIEMPRE"},{"id":"informe_admin","nombre":"Informe del órgano de administración sobre la modificación","condicion":"SIEMPRE"}]},"constitucion":{"quorum":{"SA_1a":{"valor":0.50,"fuente":"LEY","referencia":"art. 194.1 LSC"},"SA_2a":{"valor":0.25,"fuente":"LEY","referencia":"art. 194.1 LSC"},"SL":{"valor":0,"fuente":"LEY","referencia":"art. 198 LSC"},"CONSEJO":{"valor":"mayoria_miembros","fuente":"LEY","referencia":"art. 247.1 LSC"}}},"votacion":{"mayoria":{"SA":{"formula":"favor >= 2/3_emitidos","fuente":"LEY","referencia":"art. 194.1 LSC"},"SL":{"formula":"favor >= 2/3_capital_con_voto","fuente":"LEY","referencia":"art. 199 LSC"},"CONSEJO":{"formula":"favor > presentes_mitad","fuente":"LEY","referencia":"art. 247.1 LSC"}},"abstenciones":"no_cuentan","votoCalidadPermitido":false},"documentacion":{"obligatoria":[{"id":"propuesta_modificacion","nombre":"Propuesta íntegra de modificación"},{"id":"informe_admin_justificacion","nombre":"Informe justificativo de la modificación"}],"ventanaDisponibilidad":{"dias":15,"fuente":"LEY"}},"acta":{"tipoActaPorModo":{"MEETING":"ACTA_JUNTA","UNIVERSAL":"ACTA_JUNTA"},"requiereTranscripcionLibroActas":true,"requiereConformidadConjunta":false},"plazosMateriales":{"inscripcion":{"plazo_dias":60,"fuente":"LEY","referencia":"art. 19 RRM"},"publicacion":["BORME"]},"postAcuerdo":{"inscribible":true,"instrumentoRequerido":"ESCRITURA","publicacionRequerida":true,"plazoInscripcion":{"dias":60,"fuente":"LEY","referencia":"art. 19 RRM"}}}'::jsonb,
  true
) ON CONFLICT (pack_id, version) DO UPDATE SET payload = EXCLUDED.payload, is_active = true;

-- 7. AUMENTO_CAPITAL v1.0.0
INSERT INTO rule_pack_versions (pack_id, version, payload, is_active) VALUES (
  'AUMENTO_CAPITAL', '1.0.0',
  '{"id":"AUMENTO_CAPITAL","materia":"AUMENTO_CAPITAL","clase":"ESTATUTARIA","organoTipo":"JUNTA_GENERAL","modosAdopcionPermitidos":["MEETING","UNIVERSAL"],"convocatoria":{"antelacionDias":{"SA":{"valor":15,"fuente":"LEY","referencia":"art. 176.1 LSC"},"SL":{"valor":15,"fuente":"LEY"}},"canales":{"SA":["BORME","WEB_INSCRITA"],"SL":["COMUNICACION_INDIVIDUAL_ESCRITA"]},"contenidoMinimo":["Fecha hora y lugar","Importe del aumento y forma de realización","Información sobre derecho de suscripción preferente"],"documentosObligatorios":[{"id":"propuesta_aumento","nombre":"Propuesta de acuerdo de aumento de capital","condicion":"SIEMPRE"},{"id":"informe_admin","nombre":"Informe del órgano de administración (art. 296 LSC)","condicion":"SIEMPRE"}]},"constitucion":{"quorum":{"SA_1a":{"valor":0.50,"fuente":"LEY","referencia":"art. 194.1 LSC"},"SA_2a":{"valor":0.25,"fuente":"LEY"},"SL":{"valor":0,"fuente":"LEY"},"CONSEJO":{"valor":"mayoria_miembros","fuente":"LEY","referencia":"art. 247.1 LSC"}}},"votacion":{"mayoria":{"SA":{"formula":"favor >= 2/3_emitidos","fuente":"LEY","referencia":"art. 194.1 LSC"},"SL":{"formula":"favor >= 2/3_capital_con_voto","fuente":"LEY","referencia":"art. 199 LSC"},"CONSEJO":{"formula":"favor > presentes_mitad","fuente":"LEY"}},"abstenciones":"no_cuentan","votoCalidadPermitido":false},"documentacion":{"obligatoria":[{"id":"propuesta_aumento","nombre":"Propuesta íntegra de aumento de capital"},{"id":"informe_auditoria_aportaciones","nombre":"Informe auditor si aportación no dineraria","condicion":"SI_NO_DINERARIO"}],"ventanaDisponibilidad":{"dias":15,"fuente":"LEY"}},"acta":{"tipoActaPorModo":{"MEETING":"ACTA_JUNTA","UNIVERSAL":"ACTA_JUNTA"},"requiereTranscripcionLibroActas":true,"requiereConformidadConjunta":false},"plazosMateriales":{"inscripcion":{"plazo_dias":60,"fuente":"LEY","referencia":"art. 19 RRM"},"publicacion":["BORME"]},"postAcuerdo":{"inscribible":true,"instrumentoRequerido":"ESCRITURA","publicacionRequerida":true,"plazoInscripcion":{"dias":60,"fuente":"LEY","referencia":"art. 19 RRM"}}}'::jsonb,
  true
) ON CONFLICT (pack_id, version) DO UPDATE SET payload = EXCLUDED.payload, is_active = true;

-- 8. REDUCCION_CAPITAL v1.0.0
INSERT INTO rule_pack_versions (pack_id, version, payload, is_active) VALUES (
  'REDUCCION_CAPITAL', '1.0.0',
  '{"id":"REDUCCION_CAPITAL","materia":"REDUCCION_CAPITAL","clase":"ESTATUTARIA","organoTipo":"JUNTA_GENERAL","modosAdopcionPermitidos":["MEETING","UNIVERSAL"],"convocatoria":{"antelacionDias":{"SA":{"valor":15,"fuente":"LEY","referencia":"art. 176.1 LSC"},"SL":{"valor":15,"fuente":"LEY"}},"canales":{"SA":["BORME","WEB_INSCRITA"],"SL":["COMUNICACION_INDIVIDUAL_ESCRITA"]},"contenidoMinimo":["Fecha hora y lugar","Finalidad de la reducción","Procedimiento y efectos para socios y acreedores"],"documentosObligatorios":[{"id":"propuesta_reduccion","nombre":"Propuesta de acuerdo de reducción de capital","condicion":"SIEMPRE"},{"id":"balance_intermediario","nombre":"Balance intermedio si no hay cuentas recientes","condicion":"SEGÚN_CASO"}]},"constitucion":{"quorum":{"SA_1a":{"valor":0.50,"fuente":"LEY","referencia":"art. 194.1 LSC"},"SA_2a":{"valor":0.25,"fuente":"LEY"},"SL":{"valor":0,"fuente":"LEY"},"CONSEJO":{"valor":"mayoria_miembros","fuente":"LEY","referencia":"art. 247.1 LSC"}}},"votacion":{"mayoria":{"SA":{"formula":"favor >= 2/3_emitidos","fuente":"LEY","referencia":"art. 194.1 LSC"},"SL":{"formula":"favor >= 2/3_capital_con_voto","fuente":"LEY","referencia":"art. 199 LSC"},"CONSEJO":{"formula":"favor > presentes_mitad","fuente":"LEY"}},"abstenciones":"no_cuentan","votoCalidadPermitido":false},"documentacion":{"obligatoria":[{"id":"propuesta_reduccion","nombre":"Propuesta íntegra de reducción"},{"id":"informe_oposicion_acreedores","nombre":"Publicación BORME para oposición acreedores (art. 319 LSC)","condicion":"SI_DEVOLUCION_APORTACIONES"}],"ventanaDisponibilidad":{"dias":15,"fuente":"LEY"}},"acta":{"tipoActaPorModo":{"MEETING":"ACTA_JUNTA","UNIVERSAL":"ACTA_JUNTA"},"requiereTranscripcionLibroActas":true,"requiereConformidadConjunta":false},"plazosMateriales":{"inscripcion":{"plazo_dias":60,"fuente":"LEY","referencia":"art. 19 RRM"},"publicacion":["BORME"],"oposicion_acreedores":{"plazo_dias":30,"fuente":"LEY","referencia":"art. 319 LSC"}},"postAcuerdo":{"inscribible":true,"instrumentoRequerido":"ESCRITURA","publicacionRequerida":true,"plazoInscripcion":{"dias":60,"fuente":"LEY","referencia":"art. 19 RRM"}}}'::jsonb,
  true
) ON CONFLICT (pack_id, version) DO UPDATE SET payload = EXCLUDED.payload, is_active = true;

-- 9. OPERACION_VINCULADA v1.0.0
INSERT INTO rule_pack_versions (pack_id, version, payload, is_active) VALUES (
  'OPERACION_VINCULADA', '1.0.0',
  '{"id":"OPERACION_VINCULADA","materia":"OPERACION_VINCULADA","clase":"ORDINARIA","organoTipo":"CONSEJO","modosAdopcionPermitidos":["MEETING"],"convocatoria":{"antelacionDias":{"SA":{"valor":0,"fuente":"LEY"},"SL":{"valor":0,"fuente":"LEY"}},"canales":{"SA":["CONVOCATORIA_CONSEJO"],"SL":["CONVOCATORIA_CONSEJO"]},"contenidoMinimo":["Identificación de la parte vinculada","Naturaleza y condiciones económicas","Beneficios y riesgos para la sociedad"],"documentosObligatorios":[{"id":"informe_condiciones_mercado","nombre":"Informe de condiciones de mercado","condicion":"SIEMPRE"},{"id":"informe_comision_auditoria","nombre":"Informe favorable Comisión Auditoría (cotizadas)","condicion":"SI_COTIZADA"}]},"constitucion":{"quorum":{"CONSEJO":{"valor":"mayoria_miembros","fuente":"LEY","referencia":"art. 247.1 LSC"}}},"votacion":{"mayoria":{"SA":{"formula":"favor > presentes_mitad_no_vinculados","fuente":"LEY","referencia":"art. 228.e LSC"},"SL":{"formula":"favor > presentes_mitad_no_vinculados","fuente":"LEY"},"CONSEJO":{"formula":"favor > presentes_mitad_no_vinculados","fuente":"LEY","referencia":"art. 228.e LSC"}},"abstenciones":"cuentan_como_contra","votoCalidadPermitido":false},"documentacion":{"obligatoria":[{"id":"informe_valoracion","nombre":"Informe de valoración"},{"id":"declaracion_vinculacion","nombre":"Declaración de la parte vinculada"}],"ventanaDisponibilidad":{"dias":0,"fuente":"LEY"}},"acta":{"tipoActaPorModo":{"MEETING":"ACTA_CONSEJO"},"requiereTranscripcionLibroActas":true,"requiereConformidadConjunta":false},"plazosMateriales":{},"postAcuerdo":{"inscribible":false,"instrumentoRequerido":"NINGUNO","publicacionRequerida":false}}'::jsonb,
  true
) ON CONFLICT (pack_id, version) DO UPDATE SET payload = EXCLUDED.payload, is_active = true;
