-- Migration 000017 Part 1 — 7 new rule_packs + COOPTACION + DIVIDENDO_A_CUENTA

INSERT INTO rule_packs (id, tenant_id, descripcion, materia, organo_tipo)
VALUES
  ('COOPTACION',                 '00000000-0000-0000-0000-000000000001', 'Cooptación de Consejeros (SA art. 244 LSC)',       'COOPTACION',                 'CONSEJO'),
  ('DIVIDENDO_A_CUENTA',         '00000000-0000-0000-0000-000000000001', 'Dividendo a Cuenta (art. 277 LSC)',               'DIVIDENDO_A_CUENTA',         'CONSEJO'),
  ('EJECUCION_AUMENTO_DELEGADO', '00000000-0000-0000-0000-000000000001', 'Ejecución de Aumento de Capital Delegado',        'EJECUCION_AUMENTO_DELEGADO', 'CONSEJO'),
  ('TRASLADO_DOMICILIO_NACIONAL','00000000-0000-0000-0000-000000000001', 'Traslado de Domicilio Social (España)',           'TRASLADO_DOMICILIO_NACIONAL','CONSEJO'),
  ('CUENTAS_CONSOLIDADAS',       '00000000-0000-0000-0000-000000000001', 'Formulación de Cuentas Consolidadas',             'CUENTAS_CONSOLIDADAS',       'CONSEJO'),
  ('INFORME_GESTION',            '00000000-0000-0000-0000-000000000001', 'Formulación del Informe de Gestión',              'INFORME_GESTION',            'CONSEJO'),
  ('APROBACION_PRESUPUESTO',     '00000000-0000-0000-0000-000000000001', 'Aprobación del Presupuesto Anual',                'APROBACION_PRESUPUESTO',     'CONSEJO')
ON CONFLICT (id) DO UPDATE SET
  descripcion = EXCLUDED.descripcion,
  organo_tipo = EXCLUDED.organo_tipo;

-- COOPTACION v1.0.0
INSERT INTO rule_pack_versions (pack_id, version, payload, is_active) VALUES (
  'COOPTACION', '1.0.0',
  '{"id":"COOPTACION","materia":"COOPTACION","clase":"ORDINARIA","organoTipo":"CONSEJO","modosAdopcionPermitidos":["MEETING","NO_SESSION"],"restriccionTipoSocial":["SA"],"nota":"Cooptación exclusiva de SA (art. 244 LSC).","convocatoria":{"antelacionDias":{"SA":{"valor":0,"fuente":"LEY","referencia":"Convocatoria Consejo"},"SL":{"valor":0,"fuente":"LEY","referencia":"NO APLICA"}},"canales":{"SA":["CONVOCATORIA_CONSEJO"],"SL":[]},"contenidoMinimo":["Identificación del candidato","Acreditación de vacante","Duración provisional"],"documentosObligatorios":[{"id":"cv_candidato","nombre":"CV y declaración de idoneidad","condicion":"SIEMPRE"},{"id":"justificacion_vacante","nombre":"Documentación acreditativa de la vacante","condicion":"SIEMPRE"}]},"constitucion":{"quorum":{"SA_1a":{"valor":0.5,"fuente":"LEY","referencia":"art. 247 LSC"},"SA_2a":{"valor":0,"fuente":"LEY"},"SL":{"valor":0,"fuente":"LEY"},"CONSEJO":{"valor":"mayoria_miembros","fuente":"LEY","referencia":"art. 247.1 LSC"}}},"votacion":{"mayoria":{"SA":{"formula":"favor > total_miembros / 2","fuente":"LEY","referencia":"art. 247.2 LSC"},"SL":{"formula":"NO_APLICA","fuente":"LEY"},"CONSEJO":{"formula":"favor > total_miembros / 2","fuente":"LEY","referencia":"art. 247.2 LSC"}},"abstenciones":"no_cuentan","votoCalidadPermitido":true},"documentacion":{"obligatoria":[{"id":"cv_candidato","nombre":"CV del consejero cooptado"},{"id":"declaracion_idoneidad","nombre":"Declaración de idoneidad"}],"ventanaDisponibilidad":{"dias":0,"fuente":"LEY"}},"acta":{"tipoActaPorModo":{"MEETING":"ACTA_CONSEJO","NO_SESSION":"ACTA_ACUERDO_ESCRITO"},"contenidoMinimo":{"sesion":["Fecha y lugar","Consejeros asistentes","Acreditación de vacante","Candidato propuesto","Resultado votación"],"consignacion":[],"acuerdoEscrito":["Identidad consejero cooptado","Causa de vacante","Duración provisional"]},"requiereTranscripcionLibroActas":true,"requiereConformidadConjunta":false},"plazosMateriales":{"ratificacion_jga":{"nota":"El cooptado debe ser ratificado en la primera JGA ordinaria posterior (art. 244 LSC)","fuente":"LEY","referencia":"art. 244 LSC"}},"postAcuerdo":{"inscribible":false,"instrumentoRequerido":"NINGUNO","plazoInscripcionDias":0,"publicacionRequerida":false}}'::jsonb,
  true
) ON CONFLICT (pack_id, version) DO UPDATE SET payload = EXCLUDED.payload, is_active = true;

-- DIVIDENDO_A_CUENTA v1.0.0
INSERT INTO rule_pack_versions (pack_id, version, payload, is_active) VALUES (
  'DIVIDENDO_A_CUENTA', '1.0.0',
  '{"id":"DIVIDENDO_A_CUENTA","materia":"DIVIDENDO_A_CUENTA","clase":"ORDINARIA","organoTipo":"CONSEJO","modosAdopcionPermitidos":["MEETING","NO_SESSION"],"convocatoria":{"antelacionDias":{"SA":{"valor":0,"fuente":"LEY","referencia":"Convocatoria Consejo"},"SL":{"valor":0,"fuente":"LEY","referencia":"Convocatoria Consejo"}},"canales":{"SA":["CONVOCATORIA_CONSEJO"],"SL":["CONVOCATORIA_CONSEJO"]},"contenidoMinimo":["Fecha hora y lugar","Cuantía del dividendo","Referencia al estado contable"],"documentosObligatorios":[{"id":"estado_contable","nombre":"Estado contable de liquidez (art. 277.2 LSC)","condicion":"SIEMPRE"},{"id":"propuesta_dividendo","nombre":"Propuesta de distribución de dividendo a cuenta","condicion":"SIEMPRE"}]},"constitucion":{"quorum":{"SA_1a":{"valor":0.5,"fuente":"LEY","referencia":"art. 247 LSC"},"SA_2a":{"valor":0,"fuente":"LEY"},"SL":{"valor":0,"fuente":"LEY"},"CONSEJO":{"valor":"mayoria_miembros","fuente":"LEY","referencia":"art. 247.1 LSC"}}},"votacion":{"mayoria":{"SA":{"formula":"favor > total_miembros / 2","fuente":"LEY","referencia":"art. 247.2 LSC"},"SL":{"formula":"favor > total_miembros / 2","fuente":"LEY","referencia":"art. 247.2 LSC"},"CONSEJO":{"formula":"favor > total_miembros / 2","fuente":"LEY","referencia":"art. 247.2 LSC"}},"abstenciones":"no_cuentan","votoCalidadPermitido":true},"reglaEspecifica":{"requiereEstadoContable":true,"plazoEstadoContableDias":3,"referencia":"art. 277 LSC"},"documentacion":{"obligatoria":[{"id":"estado_contable_liquidez","nombre":"Estado contable de liquidez (art. 277.2 LSC)"},{"id":"informe_auditor_estado","nombre":"Informe del auditor sobre el estado contable","condicion":"SI_AUDITORIA"}],"ventanaDisponibilidad":{"dias":0,"fuente":"LEY"}},"acta":{"tipoActaPorModo":{"MEETING":"ACTA_CONSEJO","NO_SESSION":"ACTA_ACUERDO_ESCRITO"},"contenidoMinimo":{"sesion":["Fecha y lugar","Consejeros asistentes","Cuantía del dividendo","Referencia al estado contable","Resultado votación"],"consignacion":[],"acuerdoEscrito":["Cuantía y fecha de pago","Referencia al estado contable"]},"requiereTranscripcionLibroActas":true,"requiereConformidadConjunta":false},"plazosMateriales":{},"postAcuerdo":{"inscribible":false,"instrumentoRequerido":"NINGUNO","plazoInscripcionDias":0,"publicacionRequerida":false}}'::jsonb,
  true
) ON CONFLICT (pack_id, version) DO UPDATE SET payload = EXCLUDED.payload, is_active = true;

-- EJECUCION_AUMENTO_DELEGADO v1.0.0
INSERT INTO rule_pack_versions (pack_id, version, payload, is_active) VALUES (
  'EJECUCION_AUMENTO_DELEGADO', '1.0.0',
  '{"id":"EJECUCION_AUMENTO_DELEGADO","materia":"EJECUCION_AUMENTO_DELEGADO","clase":"ESTRUCTURAL","organoTipo":"CONSEJO","modosAdopcionPermitidos":["MEETING","NO_SESSION"],"convocatoria":{"antelacionDias":{"SA":{"valor":0,"fuente":"LEY"},"SL":{"valor":0,"fuente":"LEY"}},"canales":{"SA":["CONVOCATORIA_CONSEJO"],"SL":["CONVOCATORIA_CONSEJO"]},"contenidoMinimo":["Referencia al acuerdo de delegación JGA","Importe concreto del aumento","Modalidad","Plazo suscripción preferente"],"documentosObligatorios":[{"id":"acuerdo_delegacion_jga","nombre":"Acuerdo JGA delegante (art. 297 LSC)","condicion":"SIEMPRE"},{"id":"informe_admin_ampliacion","nombre":"Informe del órgano sobre la emisión","condicion":"SI_COTIZADA"},{"id":"informe_auditor_aportaciones","nombre":"Informe auditor sobre aportaciones no dinerarias","condicion":"SI_NO_DINERARIO"}]},"constitucion":{"quorum":{"CONSEJO":{"valor":"mayoria_miembros","fuente":"LEY","referencia":"art. 247.1 LSC"}}},"votacion":{"mayoria":{"CONSEJO":{"formula":"favor > total_miembros / 2","fuente":"LEY","referencia":"art. 247.2 LSC"}},"abstenciones":"no_cuentan","votoCalidadPermitido":false},"documentacion":{"obligatoria":[{"id":"acuerdo_jga_delegacion","nombre":"Certificación del acuerdo JGA delegante"},{"id":"proyecto_escritura","nombre":"Proyecto de escritura de ampliación"}],"ventanaDisponibilidad":{"dias":0,"fuente":"LEY"}},"acta":{"tipoActaPorModo":{"MEETING":"ACTA_CONSEJO","NO_SESSION":"ACTA_ACUERDO_ESCRITO"},"contenidoMinimo":{"sesion":["Fecha y lugar","Consejeros asistentes","Referencia al acuerdo delegante","Importe del aumento","Resultado votación"],"consignacion":[],"acuerdoEscrito":["Importe del aumento","Modalidad","Referencia al acuerdo delegante"]},"requiereTranscripcionLibroActas":true,"requiereConformidadConjunta":false},"plazosMateriales":{"inscripcion":{"plazo_dias":30,"fuente":"LEY","referencia":"art. 315 LSC"},"publicacion":["BORME"]},"postAcuerdo":{"inscribible":true,"instrumentoRequerido":"ESCRITURA","plazoInscripcionDias":30,"publicacionRequerida":true}}'::jsonb,
  true
) ON CONFLICT (pack_id, version) DO UPDATE SET payload = EXCLUDED.payload, is_active = true;

-- TRASLADO_DOMICILIO_NACIONAL v1.0.0
INSERT INTO rule_pack_versions (pack_id, version, payload, is_active) VALUES (
  'TRASLADO_DOMICILIO_NACIONAL', '1.0.0',
  '{"id":"TRASLADO_DOMICILIO_NACIONAL","materia":"TRASLADO_DOMICILIO_NACIONAL","clase":"ORDINARIA","organoTipo":"CONSEJO","modosAdopcionPermitidos":["MEETING","NO_SESSION"],"nota":"Traslado dentro de España — competencia del Consejo (art. 285.1 LSC).","convocatoria":{"antelacionDias":{"SA":{"valor":0,"fuente":"LEY"},"SL":{"valor":0,"fuente":"LEY"}},"canales":{"SA":["CONVOCATORIA_CONSEJO"],"SL":["CONVOCATORIA_CONSEJO"]},"contenidoMinimo":["Fecha hora y lugar","Nuevo domicilio propuesto","Justificación del traslado"],"documentosObligatorios":[{"id":"certificacion_nuevo_domicilio","nombre":"Certificación del nuevo domicilio","condicion":"SIEMPRE"}]},"constitucion":{"quorum":{"CONSEJO":{"valor":"mayoria_miembros","fuente":"LEY","referencia":"art. 247.1 LSC"}}},"votacion":{"mayoria":{"CONSEJO":{"formula":"favor > total_miembros / 2","fuente":"LEY","referencia":"art. 247.2 LSC"}},"abstenciones":"no_cuentan","votoCalidadPermitido":true},"documentacion":{"obligatoria":[{"id":"certificacion_domicilio","nombre":"Título o certificación del nuevo domicilio"},{"id":"notificacion_hacienda","nombre":"Notificación a AEAT y registros administrativos"}],"ventanaDisponibilidad":{"dias":0,"fuente":"LEY"}},"acta":{"tipoActaPorModo":{"MEETING":"ACTA_CONSEJO","NO_SESSION":"ACTA_ACUERDO_ESCRITO"},"contenidoMinimo":{"sesion":["Fecha y lugar","Consejeros asistentes","Nuevo domicilio acordado","Resultado votación"],"consignacion":[],"acuerdoEscrito":["Nuevo domicilio social completo","Fecha efectiva del cambio"]},"requiereTranscripcionLibroActas":true,"requiereConformidadConjunta":false},"plazosMateriales":{"inscripcion":{"plazo_dias":30,"fuente":"LEY","referencia":"art. 285.1 LSC"},"publicacion":["BORME"]},"postAcuerdo":{"inscribible":true,"instrumentoRequerido":"ESCRITURA","plazoInscripcionDias":30,"publicacionRequerida":true}}'::jsonb,
  true
) ON CONFLICT (pack_id, version) DO UPDATE SET payload = EXCLUDED.payload, is_active = true;

-- CUENTAS_CONSOLIDADAS v1.0.0
INSERT INTO rule_pack_versions (pack_id, version, payload, is_active) VALUES (
  'CUENTAS_CONSOLIDADAS', '1.0.0',
  '{"id":"CUENTAS_CONSOLIDADAS","materia":"CUENTAS_CONSOLIDADAS","clase":"ORDINARIA","organoTipo":"CONSEJO","modosAdopcionPermitidos":["MEETING","NO_SESSION"],"convocatoria":{"antelacionDias":{"SA":{"valor":0,"fuente":"LEY"},"SL":{"valor":0,"fuente":"LEY"}},"canales":{"SA":["CONVOCATORIA_CONSEJO"],"SL":["CONVOCATORIA_CONSEJO"]},"contenidoMinimo":["Fecha hora y lugar","Cuentas consolidadas del grupo","Informe de auditoría del grupo"],"documentosObligatorios":[{"id":"cuentas_consolidadas_borrador","nombre":"Borrador cuentas anuales consolidadas","condicion":"SIEMPRE"},{"id":"informe_auditoria_grupo","nombre":"Informe de auditoría del grupo","condicion":"SI_OBLIGACION_AUDITAR"}]},"constitucion":{"quorum":{"CONSEJO":{"valor":"mayoria_miembros","fuente":"LEY","referencia":"art. 247.1 LSC"}}},"votacion":{"mayoria":{"CONSEJO":{"formula":"favor > total_miembros / 2","fuente":"LEY","referencia":"art. 247.2 LSC"}},"abstenciones":"no_cuentan","votoCalidadPermitido":true},"documentacion":{"obligatoria":[{"id":"cuentas_consolidadas_firmadas","nombre":"Cuentas consolidadas firmadas por todos los administradores"},{"id":"informe_gestion_consolidado","nombre":"Informe de gestión consolidado del grupo"}],"ventanaDisponibilidad":{"dias":0,"fuente":"LEY"},"plazoFormulacion":{"meses":3,"fuente":"LEY","referencia":"art. 253 LSC"}},"acta":{"tipoActaPorModo":{"MEETING":"ACTA_CONSEJO","NO_SESSION":"ACTA_ACUERDO_ESCRITO"},"requiereTranscripcionLibroActas":true,"requiereConformidadConjunta":true},"plazosMateriales":{"deposito_rm":{"nota":"Depósito en RM dentro del mes siguiente a la aprobación JGA","fuente":"LEY","referencia":"art. 279 LSC"}},"postAcuerdo":{"inscribible":false,"instrumentoRequerido":"NINGUNO","plazoInscripcionDias":0,"publicacionRequerida":false}}'::jsonb,
  true
) ON CONFLICT (pack_id, version) DO UPDATE SET payload = EXCLUDED.payload, is_active = true;

-- INFORME_GESTION v1.0.0
INSERT INTO rule_pack_versions (pack_id, version, payload, is_active) VALUES (
  'INFORME_GESTION', '1.0.0',
  '{"id":"INFORME_GESTION","materia":"INFORME_GESTION","clase":"ORDINARIA","organoTipo":"CONSEJO","modosAdopcionPermitidos":["MEETING","NO_SESSION"],"convocatoria":{"antelacionDias":{"SA":{"valor":0,"fuente":"LEY"},"SL":{"valor":0,"fuente":"LEY"}},"canales":{"SA":["CONVOCATORIA_CONSEJO"],"SL":["CONVOCATORIA_CONSEJO"]},"contenidoMinimo":["Evolución y resultados del negocio","Descripción de riesgos e incertidumbres","Hechos posteriores al cierre"],"documentosObligatorios":[{"id":"borrador_informe_gestion","nombre":"Borrador del informe de gestión","condicion":"SIEMPRE"},{"id":"estado_informacion_no_financiera","nombre":"EINF (cotizadas >500 empleados)","condicion":"SI_OBLIGACION_EINF"}]},"constitucion":{"quorum":{"CONSEJO":{"valor":"mayoria_miembros","fuente":"LEY","referencia":"art. 247.1 LSC"}}},"votacion":{"mayoria":{"CONSEJO":{"formula":"favor > total_miembros / 2","fuente":"LEY"}},"abstenciones":"no_cuentan","votoCalidadPermitido":true},"documentacion":{"obligatoria":[{"id":"informe_gestion_firmado","nombre":"Informe de gestión firmado por todos los administradores (art. 253 LSC)"}],"ventanaDisponibilidad":{"dias":0,"fuente":"LEY"},"plazoFormulacion":{"meses":3,"fuente":"LEY","referencia":"art. 253 LSC"}},"acta":{"tipoActaPorModo":{"MEETING":"ACTA_CONSEJO","NO_SESSION":"ACTA_ACUERDO_ESCRITO"},"requiereTranscripcionLibroActas":true,"requiereConformidadConjunta":true},"plazosMateriales":{},"postAcuerdo":{"inscribible":false,"instrumentoRequerido":"NINGUNO","plazoInscripcionDias":0,"publicacionRequerida":false}}'::jsonb,
  true
) ON CONFLICT (pack_id, version) DO UPDATE SET payload = EXCLUDED.payload, is_active = true;

-- APROBACION_PRESUPUESTO v1.0.0
INSERT INTO rule_pack_versions (pack_id, version, payload, is_active) VALUES (
  'APROBACION_PRESUPUESTO', '1.0.0',
  '{"id":"APROBACION_PRESUPUESTO","materia":"APROBACION_PRESUPUESTO","clase":"ORDINARIA","organoTipo":"CONSEJO","modosAdopcionPermitidos":["MEETING","NO_SESSION"],"convocatoria":{"antelacionDias":{"SA":{"valor":0,"fuente":"LEY"},"SL":{"valor":0,"fuente":"LEY"}},"canales":{"SA":["CONVOCATORIA_CONSEJO"],"SL":["CONVOCATORIA_CONSEJO"]},"contenidoMinimo":["Fecha hora y lugar","Presupuesto anual","Cuadros de ingresos gastos e inversiones"],"documentosObligatorios":[{"id":"presupuesto_borrador","nombre":"Borrador del presupuesto anual","condicion":"SIEMPRE"}]},"constitucion":{"quorum":{"CONSEJO":{"valor":"mayoria_miembros","fuente":"LEY","referencia":"art. 247.1 LSC"}}},"votacion":{"mayoria":{"CONSEJO":{"formula":"favor > total_miembros / 2","fuente":"LEY"}},"abstenciones":"no_cuentan","votoCalidadPermitido":true},"documentacion":{"obligatoria":[{"id":"presupuesto_aprobado","nombre":"Presupuesto anual aprobado en formato definitivo"}],"ventanaDisponibilidad":{"dias":0,"fuente":"LEY"}},"acta":{"tipoActaPorModo":{"MEETING":"ACTA_CONSEJO","NO_SESSION":"ACTA_ACUERDO_ESCRITO"},"requiereTranscripcionLibroActas":true,"requiereConformidadConjunta":false},"plazosMateriales":{},"postAcuerdo":{"inscribible":false,"instrumentoRequerido":"NINGUNO","plazoInscripcionDias":0,"publicacionRequerida":false}}'::jsonb,
  true
) ON CONFLICT (pack_id, version) DO UPDATE SET payload = EXCLUDED.payload, is_active = true;
