-- ITEM-054 — 15 rule packs aprobados Garrigues/Comité Legal (parámetros LSC verificados BOE).
-- Corrige errores de seed del handoff: LIQUIDACION/disolución no es UNANIMIDAD (art. 368 →
-- requisitos de modificación estatutaria); estatutarias = reforzada (201.2 SA / 199.a SL).
-- Forward-only, idempotente. Cada pack: rule_packs (id=materia) + rule_pack_versions 1.0.0 ACTIVE.

INSERT INTO public.rule_packs (id, tenant_id, materia, organo_tipo, descripcion)
SELECT 'AMPLIACION_OBJETO_SOCIAL', '00000000-0000-0000-0000-000000000001'::uuid, 'AMPLIACION_OBJETO_SOCIAL', 'JUNTA_GENERAL', 'Garrigues/Comité Legal — AMPLIACION_OBJETO_SOCIAL'
WHERE NOT EXISTS (SELECT 1 FROM public.rule_packs WHERE id='AMPLIACION_OBJETO_SOCIAL');

INSERT INTO public.rule_pack_versions (pack_id, version, payload, is_active, status, effective_from)
SELECT 'AMPLIACION_OBJETO_SOCIAL', '1.0.0', '{"id": "AMPLIACION_OBJETO_SOCIAL", "materia": "AMPLIACION_OBJETO_SOCIAL", "clase": "ESTATUTARIA", "organoTipo": "JUNTA_GENERAL", "modosAdopcionPermitidos": ["MEETING", "UNIVERSAL"], "acta": {"tipoActaPorModo": {"MEETING": "ACTA_JUNTA", "UNIVERSAL": "ACTA_JUNTA"}, "requiereConformidadConjunta": false, "requiereTranscripcionLibroActas": true}, "votacion": {"mayoria": {"SA": {"fuente": "LEY", "formula": "reforzada art. 201.2 LSC", "referencia": "art. 201.2 LSC — 2/3 capital presente (tramo 25-50% en 2ª conv.); art. 285 LSC; derecho de separación art. 346.1.a si sustitución"}, "SL": {"fuente": "LEY", "formula": "favor > 1/2_capital_total_con_voto", "referencia": "art. 199.a LSC"}, "CONSEJO": {"fuente": "LEY", "formula": "favor > presentes_mitad", "referencia": "art. 247.1 LSC"}}, "abstenciones": "no_cuentan", "votoCalidadPermitido": false}, "constitucion": {"quorum": {"SL": {"valor": 0, "fuente": "LEY", "referencia": "art. 198 LSC"}, "SA_1a": {"valor": 0.5, "fuente": "LEY", "referencia": "art. 194.1 LSC"}, "SA_2a": {"valor": 0.25, "fuente": "LEY", "referencia": "art. 194.1 LSC"}, "CONSEJO": {"valor": "mayoria_miembros", "fuente": "LEY", "referencia": "art. 247.1 LSC"}}}, "convocatoria": {"canales": {"SA": ["BORME", "WEB_INSCRITA"], "SL": ["COMUNICACION_INDIVIDUAL_ESCRITA"]}, "antelacionDias": {"SA": {"valor": 30, "fuente": "LEY", "referencia": "art. 176.1 LSC"}, "SL": {"valor": 15, "fuente": "LEY", "referencia": "art. 176.1 LSC"}}, "contenidoMinimo": ["Fecha hora y lugar", "Texto íntegro de la propuesta", "Texto actual y propuesto"], "documentosObligatorios": [{"id": "propuesta", "nombre": "Texto íntegro de la propuesta (ampliación de objeto social)", "condicion": "SIEMPRE"}, {"id": "informe_admin", "nombre": "Informe del órgano de administración", "condicion": "SIEMPRE"}]}, "documentacion": {"obligatoria": [{"id": "propuesta", "nombre": "Propuesta íntegra"}, {"id": "informe_admin_justificacion", "nombre": "Informe justificativo"}, {"id": "derecho_informacion_287", "nombre": "Derecho de información art. 287 LSC", "condicion": "SIEMPRE"}], "ventanaDisponibilidad": {"dias": 15, "fuente": "LEY"}}, "postAcuerdo": {"inscribible": true, "instrumentoRequerido": "ESCRITURA", "publicacionRequerida": true, "plazoInscripcion": {"dias": 30, "fuente": "LEY", "referencia": "art. 83 RRM (1 mes)"}}, "plazosMateriales": {"inscripcion": {"plazo_dias": 30, "fuente": "LEY", "referencia": "art. 83 RRM"}, "publicacion": ["BORME"]}}'::jsonb, true, 'ACTIVE', CURRENT_DATE
WHERE NOT EXISTS (SELECT 1 FROM public.rule_pack_versions WHERE pack_id='AMPLIACION_OBJETO_SOCIAL' AND is_active=true);

INSERT INTO public.rule_packs (id, tenant_id, materia, organo_tipo, descripcion)
SELECT 'CAMBIO_DENOMINACION_SOCIAL', '00000000-0000-0000-0000-000000000001'::uuid, 'CAMBIO_DENOMINACION_SOCIAL', 'JUNTA_GENERAL', 'Garrigues/Comité Legal — CAMBIO_DENOMINACION_SOCIAL'
WHERE NOT EXISTS (SELECT 1 FROM public.rule_packs WHERE id='CAMBIO_DENOMINACION_SOCIAL');

INSERT INTO public.rule_pack_versions (pack_id, version, payload, is_active, status, effective_from)
SELECT 'CAMBIO_DENOMINACION_SOCIAL', '1.0.0', '{"id": "CAMBIO_DENOMINACION_SOCIAL", "materia": "CAMBIO_DENOMINACION_SOCIAL", "clase": "ESTATUTARIA", "organoTipo": "JUNTA_GENERAL", "modosAdopcionPermitidos": ["MEETING", "UNIVERSAL"], "acta": {"tipoActaPorModo": {"MEETING": "ACTA_JUNTA", "UNIVERSAL": "ACTA_JUNTA"}, "requiereConformidadConjunta": false, "requiereTranscripcionLibroActas": true}, "votacion": {"mayoria": {"SA": {"fuente": "LEY", "formula": "reforzada art. 201.2 LSC", "referencia": "art. 201.2 LSC — 2/3 capital presente (tramo 25-50% en 2ª conv.); art. 285 LSC"}, "SL": {"fuente": "LEY", "formula": "favor > 1/2_capital_total_con_voto", "referencia": "art. 199.a LSC"}, "CONSEJO": {"fuente": "LEY", "formula": "favor > presentes_mitad", "referencia": "art. 247.1 LSC"}}, "abstenciones": "no_cuentan", "votoCalidadPermitido": false}, "constitucion": {"quorum": {"SL": {"valor": 0, "fuente": "LEY", "referencia": "art. 198 LSC"}, "SA_1a": {"valor": 0.5, "fuente": "LEY", "referencia": "art. 194.1 LSC"}, "SA_2a": {"valor": 0.25, "fuente": "LEY", "referencia": "art. 194.1 LSC"}, "CONSEJO": {"valor": "mayoria_miembros", "fuente": "LEY", "referencia": "art. 247.1 LSC"}}}, "convocatoria": {"canales": {"SA": ["BORME", "WEB_INSCRITA"], "SL": ["COMUNICACION_INDIVIDUAL_ESCRITA"]}, "antelacionDias": {"SA": {"valor": 30, "fuente": "LEY", "referencia": "art. 176.1 LSC"}, "SL": {"valor": 15, "fuente": "LEY", "referencia": "art. 176.1 LSC"}}, "contenidoMinimo": ["Fecha hora y lugar", "Texto íntegro de la propuesta", "Texto actual y propuesto"], "documentosObligatorios": [{"id": "propuesta", "nombre": "Texto íntegro de la propuesta (cambio de denominación)", "condicion": "SIEMPRE"}, {"id": "informe_admin", "nombre": "Informe del órgano de administración", "condicion": "SIEMPRE"}]}, "documentacion": {"obligatoria": [{"id": "propuesta", "nombre": "Propuesta íntegra"}, {"id": "informe_admin_justificacion", "nombre": "Informe justificativo"}, {"id": "derecho_informacion_287", "nombre": "Derecho de información art. 287 LSC", "condicion": "SIEMPRE"}], "ventanaDisponibilidad": {"dias": 15, "fuente": "LEY"}}, "postAcuerdo": {"inscribible": true, "instrumentoRequerido": "ESCRITURA", "publicacionRequerida": true, "plazoInscripcion": {"dias": 30, "fuente": "LEY", "referencia": "art. 83 RRM (1 mes)"}}, "plazosMateriales": {"inscripcion": {"plazo_dias": 30, "fuente": "LEY", "referencia": "art. 83 RRM"}, "publicacion": ["BORME"]}}'::jsonb, true, 'ACTIVE', CURRENT_DATE
WHERE NOT EXISTS (SELECT 1 FROM public.rule_pack_versions WHERE pack_id='CAMBIO_DENOMINACION_SOCIAL' AND is_active=true);

INSERT INTO public.rule_packs (id, tenant_id, materia, organo_tipo, descripcion)
SELECT 'CAMBIO_DOMICILIO_SOCIAL', '00000000-0000-0000-0000-000000000001'::uuid, 'CAMBIO_DOMICILIO_SOCIAL', 'JUNTA_GENERAL', 'Garrigues/Comité Legal — CAMBIO_DOMICILIO_SOCIAL'
WHERE NOT EXISTS (SELECT 1 FROM public.rule_packs WHERE id='CAMBIO_DOMICILIO_SOCIAL');

INSERT INTO public.rule_pack_versions (pack_id, version, payload, is_active, status, effective_from)
SELECT 'CAMBIO_DOMICILIO_SOCIAL', '1.0.0', '{"id": "CAMBIO_DOMICILIO_SOCIAL", "materia": "CAMBIO_DOMICILIO_SOCIAL", "clase": "ESTATUTARIA", "organoTipo": "JUNTA_GENERAL", "modosAdopcionPermitidos": ["MEETING", "UNIVERSAL"], "acta": {"tipoActaPorModo": {"MEETING": "ACTA_JUNTA", "UNIVERSAL": "ACTA_JUNTA"}, "requiereConformidadConjunta": false, "requiereTranscripcionLibroActas": true}, "votacion": {"mayoria": {"SA": {"fuente": "LEY", "formula": "reforzada art. 201.2 LSC", "referencia": "art. 201.2 LSC — 2/3 capital presente (tramo 25-50% en 2ª conv.); art. 285.2 LSC (competencia del órgano de admin. salvo disposición estatutaria)"}, "SL": {"fuente": "LEY", "formula": "favor > 1/2_capital_total_con_voto", "referencia": "art. 199.a LSC"}, "CONSEJO": {"fuente": "LEY", "formula": "favor > presentes_mitad", "referencia": "art. 247.1 LSC"}}, "abstenciones": "no_cuentan", "votoCalidadPermitido": false}, "constitucion": {"quorum": {"SL": {"valor": 0, "fuente": "LEY", "referencia": "art. 198 LSC"}, "SA_1a": {"valor": 0.5, "fuente": "LEY", "referencia": "art. 194.1 LSC"}, "SA_2a": {"valor": 0.25, "fuente": "LEY", "referencia": "art. 194.1 LSC"}, "CONSEJO": {"valor": "mayoria_miembros", "fuente": "LEY", "referencia": "art. 247.1 LSC"}}}, "convocatoria": {"canales": {"SA": ["BORME", "WEB_INSCRITA"], "SL": ["COMUNICACION_INDIVIDUAL_ESCRITA"]}, "antelacionDias": {"SA": {"valor": 30, "fuente": "LEY", "referencia": "art. 176.1 LSC"}, "SL": {"valor": 15, "fuente": "LEY", "referencia": "art. 176.1 LSC"}}, "contenidoMinimo": ["Fecha hora y lugar", "Texto íntegro de la propuesta", "Texto actual y propuesto"], "documentosObligatorios": [{"id": "propuesta", "nombre": "Texto íntegro de la propuesta (cambio de domicilio)", "condicion": "SIEMPRE"}, {"id": "informe_admin", "nombre": "Informe del órgano de administración", "condicion": "SIEMPRE"}]}, "documentacion": {"obligatoria": [{"id": "propuesta", "nombre": "Propuesta íntegra"}, {"id": "informe_admin_justificacion", "nombre": "Informe justificativo"}, {"id": "derecho_informacion_287", "nombre": "Derecho de información art. 287 LSC", "condicion": "SIEMPRE"}], "ventanaDisponibilidad": {"dias": 15, "fuente": "LEY"}}, "postAcuerdo": {"inscribible": true, "instrumentoRequerido": "ESCRITURA", "publicacionRequerida": true, "plazoInscripcion": {"dias": 30, "fuente": "LEY", "referencia": "art. 83 RRM (1 mes)"}}, "plazosMateriales": {"inscripcion": {"plazo_dias": 30, "fuente": "LEY", "referencia": "art. 83 RRM"}, "publicacion": ["BORME"]}}'::jsonb, true, 'ACTIVE', CURRENT_DATE
WHERE NOT EXISTS (SELECT 1 FROM public.rule_pack_versions WHERE pack_id='CAMBIO_DOMICILIO_SOCIAL' AND is_active=true);

INSERT INTO public.rule_packs (id, tenant_id, materia, organo_tipo, descripcion)
SELECT 'DELEGACION_CAPITAL', '00000000-0000-0000-0000-000000000001'::uuid, 'DELEGACION_CAPITAL', 'JUNTA_GENERAL', 'Garrigues/Comité Legal — DELEGACION_CAPITAL'
WHERE NOT EXISTS (SELECT 1 FROM public.rule_packs WHERE id='DELEGACION_CAPITAL');

INSERT INTO public.rule_pack_versions (pack_id, version, payload, is_active, status, effective_from)
SELECT 'DELEGACION_CAPITAL', '1.0.0', '{"id": "DELEGACION_CAPITAL", "materia": "DELEGACION_CAPITAL", "clase": "ESTATUTARIA", "organoTipo": "JUNTA_GENERAL", "modosAdopcionPermitidos": ["MEETING", "UNIVERSAL"], "acta": {"tipoActaPorModo": {"MEETING": "ACTA_JUNTA", "UNIVERSAL": "ACTA_JUNTA"}, "requiereConformidadConjunta": false, "requiereTranscripcionLibroActas": true}, "votacion": {"mayoria": {"SA": {"fuente": "LEY", "formula": "reforzada art. 201.2 LSC", "referencia": "art. 201.2 LSC — 2/3 capital presente (tramo 25-50% en 2ª conv.); art. 297 LSC"}, "SL": {"fuente": "LEY", "formula": "favor > 1/2_capital_total_con_voto", "referencia": "art. 199.a LSC"}, "CONSEJO": {"fuente": "LEY", "formula": "favor > presentes_mitad", "referencia": "art. 247.1 LSC"}}, "abstenciones": "no_cuentan", "votoCalidadPermitido": false}, "constitucion": {"quorum": {"SL": {"valor": 0, "fuente": "LEY", "referencia": "art. 198 LSC"}, "SA_1a": {"valor": 0.5, "fuente": "LEY", "referencia": "art. 194.1 LSC"}, "SA_2a": {"valor": 0.25, "fuente": "LEY", "referencia": "art. 194.1 LSC"}, "CONSEJO": {"valor": "mayoria_miembros", "fuente": "LEY", "referencia": "art. 247.1 LSC"}}}, "convocatoria": {"canales": {"SA": ["BORME", "WEB_INSCRITA"], "SL": ["COMUNICACION_INDIVIDUAL_ESCRITA"]}, "antelacionDias": {"SA": {"valor": 30, "fuente": "LEY", "referencia": "art. 176.1 LSC"}, "SL": {"valor": 15, "fuente": "LEY", "referencia": "art. 176.1 LSC"}}, "contenidoMinimo": ["Fecha hora y lugar", "Texto íntegro de la propuesta", "Texto actual y propuesto"], "documentosObligatorios": [{"id": "propuesta", "nombre": "Texto íntegro de la propuesta (delegación para aumentar capital)", "condicion": "SIEMPRE"}, {"id": "informe_admin", "nombre": "Informe del órgano de administración", "condicion": "SIEMPRE"}]}, "documentacion": {"obligatoria": [{"id": "propuesta", "nombre": "Propuesta íntegra"}, {"id": "informe_admin_justificacion", "nombre": "Informe justificativo"}, {"id": "derecho_informacion_287", "nombre": "Derecho de información art. 287 LSC", "condicion": "SIEMPRE"}], "ventanaDisponibilidad": {"dias": 15, "fuente": "LEY"}}, "postAcuerdo": {"inscribible": true, "instrumentoRequerido": "ESCRITURA", "publicacionRequerida": true, "plazoInscripcion": {"dias": 30, "fuente": "LEY", "referencia": "art. 83 RRM (1 mes)"}}, "plazosMateriales": {"inscripcion": {"plazo_dias": 30, "fuente": "LEY", "referencia": "art. 83 RRM"}, "publicacion": ["BORME"]}}'::jsonb, true, 'ACTIVE', CURRENT_DATE
WHERE NOT EXISTS (SELECT 1 FROM public.rule_pack_versions WHERE pack_id='DELEGACION_CAPITAL' AND is_active=true);

INSERT INTO public.rule_packs (id, tenant_id, materia, organo_tipo, descripcion)
SELECT 'EMISION_DEUDA_CONVERTIBLE', '00000000-0000-0000-0000-000000000001'::uuid, 'EMISION_DEUDA_CONVERTIBLE', 'JUNTA_GENERAL', 'Garrigues/Comité Legal — EMISION_DEUDA_CONVERTIBLE'
WHERE NOT EXISTS (SELECT 1 FROM public.rule_packs WHERE id='EMISION_DEUDA_CONVERTIBLE');

INSERT INTO public.rule_pack_versions (pack_id, version, payload, is_active, status, effective_from)
SELECT 'EMISION_DEUDA_CONVERTIBLE', '1.0.0', '{"id": "EMISION_DEUDA_CONVERTIBLE", "materia": "EMISION_DEUDA_CONVERTIBLE", "clase": "ESTATUTARIA", "organoTipo": "JUNTA_GENERAL", "modosAdopcionPermitidos": ["MEETING", "UNIVERSAL"], "acta": {"tipoActaPorModo": {"MEETING": "ACTA_JUNTA", "UNIVERSAL": "ACTA_JUNTA"}, "requiereConformidadConjunta": false, "requiereTranscripcionLibroActas": true}, "votacion": {"mayoria": {"SA": {"fuente": "LEY", "formula": "reforzada art. 201.2 LSC", "referencia": "art. 201.2 LSC — 2/3 capital presente (tramo 25-50% en 2ª conv.); arts. 401-418 LSC; informe de administradores y auditor"}, "SL": {"fuente": "LEY", "formula": "favor > 1/2_capital_total_con_voto", "referencia": "art. 199.a LSC"}, "CONSEJO": {"fuente": "LEY", "formula": "favor > presentes_mitad", "referencia": "art. 247.1 LSC"}}, "abstenciones": "no_cuentan", "votoCalidadPermitido": false}, "constitucion": {"quorum": {"SL": {"valor": 0, "fuente": "LEY", "referencia": "art. 198 LSC"}, "SA_1a": {"valor": 0.5, "fuente": "LEY", "referencia": "art. 194.1 LSC"}, "SA_2a": {"valor": 0.25, "fuente": "LEY", "referencia": "art. 194.1 LSC"}, "CONSEJO": {"valor": "mayoria_miembros", "fuente": "LEY", "referencia": "art. 247.1 LSC"}}}, "convocatoria": {"canales": {"SA": ["BORME", "WEB_INSCRITA"], "SL": ["COMUNICACION_INDIVIDUAL_ESCRITA"]}, "antelacionDias": {"SA": {"valor": 30, "fuente": "LEY", "referencia": "art. 176.1 LSC"}, "SL": {"valor": 15, "fuente": "LEY", "referencia": "art. 176.1 LSC"}}, "contenidoMinimo": ["Fecha hora y lugar", "Texto íntegro de la propuesta", "Texto actual y propuesto"], "documentosObligatorios": [{"id": "propuesta", "nombre": "Texto íntegro de la propuesta (emisión de obligaciones convertibles)", "condicion": "SIEMPRE"}, {"id": "informe_admin", "nombre": "Informe del órgano de administración", "condicion": "SIEMPRE"}]}, "documentacion": {"obligatoria": [{"id": "propuesta", "nombre": "Propuesta íntegra"}, {"id": "informe_admin_justificacion", "nombre": "Informe justificativo"}, {"id": "derecho_informacion_287", "nombre": "Derecho de información art. 287 LSC", "condicion": "SIEMPRE"}], "ventanaDisponibilidad": {"dias": 15, "fuente": "LEY"}}, "postAcuerdo": {"inscribible": true, "instrumentoRequerido": "ESCRITURA", "publicacionRequerida": true, "plazoInscripcion": {"dias": 30, "fuente": "LEY", "referencia": "art. 83 RRM (1 mes)"}}, "plazosMateriales": {"inscripcion": {"plazo_dias": 30, "fuente": "LEY", "referencia": "art. 83 RRM"}, "publicacion": ["BORME"]}}'::jsonb, true, 'ACTIVE', CURRENT_DATE
WHERE NOT EXISTS (SELECT 1 FROM public.rule_pack_versions WHERE pack_id='EMISION_DEUDA_CONVERTIBLE' AND is_active=true);

INSERT INTO public.rule_packs (id, tenant_id, materia, organo_tipo, descripcion)
SELECT 'EXCLUSION_DERECHO_SUSCRIPCION_PREFERENTE', '00000000-0000-0000-0000-000000000001'::uuid, 'EXCLUSION_DERECHO_SUSCRIPCION_PREFERENTE', 'JUNTA_GENERAL', 'Garrigues/Comité Legal — EXCLUSION_DERECHO_SUSCRIPCION_PREFERENTE'
WHERE NOT EXISTS (SELECT 1 FROM public.rule_packs WHERE id='EXCLUSION_DERECHO_SUSCRIPCION_PREFERENTE');

INSERT INTO public.rule_pack_versions (pack_id, version, payload, is_active, status, effective_from)
SELECT 'EXCLUSION_DERECHO_SUSCRIPCION_PREFERENTE', '1.0.0', '{"id": "EXCLUSION_DERECHO_SUSCRIPCION_PREFERENTE", "materia": "EXCLUSION_DERECHO_SUSCRIPCION_PREFERENTE", "clase": "ESTATUTARIA", "organoTipo": "JUNTA_GENERAL", "modosAdopcionPermitidos": ["MEETING", "UNIVERSAL"], "acta": {"tipoActaPorModo": {"MEETING": "ACTA_JUNTA", "UNIVERSAL": "ACTA_JUNTA"}, "requiereConformidadConjunta": false, "requiereTranscripcionLibroActas": true}, "votacion": {"mayoria": {"SA": {"fuente": "LEY", "formula": "reforzada art. 201.2 LSC", "referencia": "art. 201.2 LSC — 2/3 capital presente (tramo 25-50% en 2ª conv.); art. 308 LSC; informe + valor razonable"}, "SL": {"fuente": "LEY", "formula": "favor > 1/2_capital_total_con_voto", "referencia": "art. 199.a LSC"}, "CONSEJO": {"fuente": "LEY", "formula": "favor > presentes_mitad", "referencia": "art. 247.1 LSC"}}, "abstenciones": "no_cuentan", "votoCalidadPermitido": false}, "constitucion": {"quorum": {"SL": {"valor": 0, "fuente": "LEY", "referencia": "art. 198 LSC"}, "SA_1a": {"valor": 0.5, "fuente": "LEY", "referencia": "art. 194.1 LSC"}, "SA_2a": {"valor": 0.25, "fuente": "LEY", "referencia": "art. 194.1 LSC"}, "CONSEJO": {"valor": "mayoria_miembros", "fuente": "LEY", "referencia": "art. 247.1 LSC"}}}, "convocatoria": {"canales": {"SA": ["BORME", "WEB_INSCRITA"], "SL": ["COMUNICACION_INDIVIDUAL_ESCRITA"]}, "antelacionDias": {"SA": {"valor": 30, "fuente": "LEY", "referencia": "art. 176.1 LSC"}, "SL": {"valor": 15, "fuente": "LEY", "referencia": "art. 176.1 LSC"}}, "contenidoMinimo": ["Fecha hora y lugar", "Texto íntegro de la propuesta", "Texto actual y propuesto"], "documentosObligatorios": [{"id": "propuesta", "nombre": "Texto íntegro de la propuesta (exclusión del derecho de suscripción preferente)", "condicion": "SIEMPRE"}, {"id": "informe_admin", "nombre": "Informe del órgano de administración", "condicion": "SIEMPRE"}]}, "documentacion": {"obligatoria": [{"id": "propuesta", "nombre": "Propuesta íntegra"}, {"id": "informe_admin_justificacion", "nombre": "Informe justificativo"}, {"id": "derecho_informacion_287", "nombre": "Derecho de información art. 287 LSC", "condicion": "SIEMPRE"}], "ventanaDisponibilidad": {"dias": 15, "fuente": "LEY"}}, "postAcuerdo": {"inscribible": true, "instrumentoRequerido": "ESCRITURA", "publicacionRequerida": true, "plazoInscripcion": {"dias": 30, "fuente": "LEY", "referencia": "art. 83 RRM (1 mes)"}}, "plazosMateriales": {"inscripcion": {"plazo_dias": 30, "fuente": "LEY", "referencia": "art. 83 RRM"}, "publicacion": ["BORME"]}}'::jsonb, true, 'ACTIVE', CURRENT_DATE
WHERE NOT EXISTS (SELECT 1 FROM public.rule_pack_versions WHERE pack_id='EXCLUSION_DERECHO_SUSCRIPCION_PREFERENTE' AND is_active=true);

INSERT INTO public.rule_packs (id, tenant_id, materia, organo_tipo, descripcion)
SELECT 'PRORROGA_SOCIEDAD', '00000000-0000-0000-0000-000000000001'::uuid, 'PRORROGA_SOCIEDAD', 'JUNTA_GENERAL', 'Garrigues/Comité Legal — PRORROGA_SOCIEDAD'
WHERE NOT EXISTS (SELECT 1 FROM public.rule_packs WHERE id='PRORROGA_SOCIEDAD');

INSERT INTO public.rule_pack_versions (pack_id, version, payload, is_active, status, effective_from)
SELECT 'PRORROGA_SOCIEDAD', '1.0.0', '{"id": "PRORROGA_SOCIEDAD", "materia": "PRORROGA_SOCIEDAD", "clase": "ESTATUTARIA", "organoTipo": "JUNTA_GENERAL", "modosAdopcionPermitidos": ["MEETING", "UNIVERSAL"], "acta": {"tipoActaPorModo": {"MEETING": "ACTA_JUNTA", "UNIVERSAL": "ACTA_JUNTA"}, "requiereConformidadConjunta": false, "requiereTranscripcionLibroActas": true}, "votacion": {"mayoria": {"SA": {"fuente": "LEY", "formula": "reforzada art. 201.2 LSC", "referencia": "art. 201.2 LSC — 2/3 capital presente (tramo 25-50% en 2ª conv.); art. 285 LSC; derecho de separación si procede"}, "SL": {"fuente": "LEY", "formula": "favor > 1/2_capital_total_con_voto", "referencia": "art. 199.a LSC"}, "CONSEJO": {"fuente": "LEY", "formula": "favor > presentes_mitad", "referencia": "art. 247.1 LSC"}}, "abstenciones": "no_cuentan", "votoCalidadPermitido": false}, "constitucion": {"quorum": {"SL": {"valor": 0, "fuente": "LEY", "referencia": "art. 198 LSC"}, "SA_1a": {"valor": 0.5, "fuente": "LEY", "referencia": "art. 194.1 LSC"}, "SA_2a": {"valor": 0.25, "fuente": "LEY", "referencia": "art. 194.1 LSC"}, "CONSEJO": {"valor": "mayoria_miembros", "fuente": "LEY", "referencia": "art. 247.1 LSC"}}}, "convocatoria": {"canales": {"SA": ["BORME", "WEB_INSCRITA"], "SL": ["COMUNICACION_INDIVIDUAL_ESCRITA"]}, "antelacionDias": {"SA": {"valor": 30, "fuente": "LEY", "referencia": "art. 176.1 LSC"}, "SL": {"valor": 15, "fuente": "LEY", "referencia": "art. 176.1 LSC"}}, "contenidoMinimo": ["Fecha hora y lugar", "Texto íntegro de la propuesta", "Texto actual y propuesto"], "documentosObligatorios": [{"id": "propuesta", "nombre": "Texto íntegro de la propuesta (prórroga de la duración)", "condicion": "SIEMPRE"}, {"id": "informe_admin", "nombre": "Informe del órgano de administración", "condicion": "SIEMPRE"}]}, "documentacion": {"obligatoria": [{"id": "propuesta", "nombre": "Propuesta íntegra"}, {"id": "informe_admin_justificacion", "nombre": "Informe justificativo"}, {"id": "derecho_informacion_287", "nombre": "Derecho de información art. 287 LSC", "condicion": "SIEMPRE"}], "ventanaDisponibilidad": {"dias": 15, "fuente": "LEY"}}, "postAcuerdo": {"inscribible": true, "instrumentoRequerido": "ESCRITURA", "publicacionRequerida": true, "plazoInscripcion": {"dias": 30, "fuente": "LEY", "referencia": "art. 83 RRM (1 mes)"}}, "plazosMateriales": {"inscripcion": {"plazo_dias": 30, "fuente": "LEY", "referencia": "art. 83 RRM"}, "publicacion": ["BORME"]}}'::jsonb, true, 'ACTIVE', CURRENT_DATE
WHERE NOT EXISTS (SELECT 1 FROM public.rule_pack_versions WHERE pack_id='PRORROGA_SOCIEDAD' AND is_active=true);

INSERT INTO public.rule_packs (id, tenant_id, materia, organo_tipo, descripcion)
SELECT 'AMPLIACION_CAPITAL', '00000000-0000-0000-0000-000000000001'::uuid, 'AMPLIACION_CAPITAL', 'JUNTA_GENERAL', 'Garrigues/Comité Legal — AMPLIACION_CAPITAL'
WHERE NOT EXISTS (SELECT 1 FROM public.rule_packs WHERE id='AMPLIACION_CAPITAL');

INSERT INTO public.rule_pack_versions (pack_id, version, payload, is_active, status, effective_from)
SELECT 'AMPLIACION_CAPITAL', '1.0.0', '{"id": "AMPLIACION_CAPITAL", "materia": "AMPLIACION_CAPITAL", "clase": "ESTATUTARIA", "organoTipo": "JUNTA_GENERAL", "modosAdopcionPermitidos": ["MEETING", "UNIVERSAL"], "acta": {"tipoActaPorModo": {"MEETING": "ACTA_JUNTA", "UNIVERSAL": "ACTA_JUNTA"}, "requiereConformidadConjunta": false, "requiereTranscripcionLibroActas": true}, "votacion": {"mayoria": {"SA": {"fuente": "LEY", "formula": "reforzada art. 201.2 LSC", "referencia": "art. 201.2 LSC — 2/3 capital presente (tramo 25-50% en 2ª conv.); arts. 295-316 LSC"}, "SL": {"fuente": "LEY", "formula": "favor > 1/2_capital_total_con_voto", "referencia": "art. 199.a LSC"}, "CONSEJO": {"fuente": "LEY", "formula": "favor > presentes_mitad", "referencia": "art. 247.1 LSC"}}, "abstenciones": "no_cuentan", "votoCalidadPermitido": false}, "constitucion": {"quorum": {"SL": {"valor": 0, "fuente": "LEY", "referencia": "art. 198 LSC"}, "SA_1a": {"valor": 0.5, "fuente": "LEY", "referencia": "art. 194.1 LSC"}, "SA_2a": {"valor": 0.25, "fuente": "LEY", "referencia": "art. 194.1 LSC"}, "CONSEJO": {"valor": "mayoria_miembros", "fuente": "LEY", "referencia": "art. 247.1 LSC"}}}, "convocatoria": {"canales": {"SA": ["BORME", "WEB_INSCRITA"], "SL": ["COMUNICACION_INDIVIDUAL_ESCRITA"]}, "antelacionDias": {"SA": {"valor": 30, "fuente": "LEY", "referencia": "art. 176.1 LSC"}, "SL": {"valor": 15, "fuente": "LEY", "referencia": "art. 176.1 LSC"}}, "contenidoMinimo": ["Fecha hora y lugar", "Texto íntegro de la propuesta", "Texto actual y propuesto"], "documentosObligatorios": [{"id": "propuesta", "nombre": "Texto íntegro de la propuesta (aumento de capital social)", "condicion": "SIEMPRE"}, {"id": "informe_admin", "nombre": "Informe del órgano de administración", "condicion": "SIEMPRE"}]}, "documentacion": {"obligatoria": [{"id": "propuesta", "nombre": "Propuesta íntegra"}, {"id": "informe_admin_justificacion", "nombre": "Informe justificativo"}, {"id": "derecho_informacion_287", "nombre": "Derecho de información art. 287 LSC", "condicion": "SIEMPRE"}], "ventanaDisponibilidad": {"dias": 15, "fuente": "LEY"}}, "postAcuerdo": {"inscribible": true, "instrumentoRequerido": "ESCRITURA", "publicacionRequerida": true, "plazoInscripcion": {"dias": 30, "fuente": "LEY", "referencia": "art. 83 RRM (1 mes)"}}, "plazosMateriales": {"inscripcion": {"plazo_dias": 30, "fuente": "LEY", "referencia": "art. 83 RRM"}, "publicacion": ["BORME"]}}'::jsonb, true, 'ACTIVE', CURRENT_DATE
WHERE NOT EXISTS (SELECT 1 FROM public.rule_pack_versions WHERE pack_id='AMPLIACION_CAPITAL' AND is_active=true);

INSERT INTO public.rule_packs (id, tenant_id, materia, organo_tipo, descripcion)
SELECT 'MOD_ESTATUTOS', '00000000-0000-0000-0000-000000000001'::uuid, 'MOD_ESTATUTOS', 'JUNTA_GENERAL', 'Garrigues/Comité Legal — MOD_ESTATUTOS'
WHERE NOT EXISTS (SELECT 1 FROM public.rule_packs WHERE id='MOD_ESTATUTOS');

INSERT INTO public.rule_pack_versions (pack_id, version, payload, is_active, status, effective_from)
SELECT 'MOD_ESTATUTOS', '1.0.0', '{"id": "MOD_ESTATUTOS", "materia": "MOD_ESTATUTOS", "clase": "ESTATUTARIA", "organoTipo": "JUNTA_GENERAL", "modosAdopcionPermitidos": ["MEETING", "UNIVERSAL"], "acta": {"tipoActaPorModo": {"MEETING": "ACTA_JUNTA", "UNIVERSAL": "ACTA_JUNTA"}, "requiereConformidadConjunta": false, "requiereTranscripcionLibroActas": true}, "votacion": {"mayoria": {"SA": {"fuente": "LEY", "formula": "reforzada art. 201.2 LSC", "referencia": "art. 201.2 LSC — 2/3 capital presente (tramo 25-50% en 2ª conv.); art. 285 LSC"}, "SL": {"fuente": "LEY", "formula": "favor > 1/2_capital_total_con_voto", "referencia": "art. 199.a LSC"}, "CONSEJO": {"fuente": "LEY", "formula": "favor > presentes_mitad", "referencia": "art. 247.1 LSC"}}, "abstenciones": "no_cuentan", "votoCalidadPermitido": false}, "constitucion": {"quorum": {"SL": {"valor": 0, "fuente": "LEY", "referencia": "art. 198 LSC"}, "SA_1a": {"valor": 0.5, "fuente": "LEY", "referencia": "art. 194.1 LSC"}, "SA_2a": {"valor": 0.25, "fuente": "LEY", "referencia": "art. 194.1 LSC"}, "CONSEJO": {"valor": "mayoria_miembros", "fuente": "LEY", "referencia": "art. 247.1 LSC"}}}, "convocatoria": {"canales": {"SA": ["BORME", "WEB_INSCRITA"], "SL": ["COMUNICACION_INDIVIDUAL_ESCRITA"]}, "antelacionDias": {"SA": {"valor": 30, "fuente": "LEY", "referencia": "art. 176.1 LSC"}, "SL": {"valor": 15, "fuente": "LEY", "referencia": "art. 176.1 LSC"}}, "contenidoMinimo": ["Fecha hora y lugar", "Texto íntegro de la propuesta", "Texto actual y propuesto"], "documentosObligatorios": [{"id": "propuesta", "nombre": "Texto íntegro de la propuesta (modificación de estatutos (alias))", "condicion": "SIEMPRE"}, {"id": "informe_admin", "nombre": "Informe del órgano de administración", "condicion": "SIEMPRE"}]}, "documentacion": {"obligatoria": [{"id": "propuesta", "nombre": "Propuesta íntegra"}, {"id": "informe_admin_justificacion", "nombre": "Informe justificativo"}, {"id": "derecho_informacion_287", "nombre": "Derecho de información art. 287 LSC", "condicion": "SIEMPRE"}], "ventanaDisponibilidad": {"dias": 15, "fuente": "LEY"}}, "postAcuerdo": {"inscribible": true, "instrumentoRequerido": "ESCRITURA", "publicacionRequerida": true, "plazoInscripcion": {"dias": 30, "fuente": "LEY", "referencia": "art. 83 RRM (1 mes)"}}, "plazosMateriales": {"inscripcion": {"plazo_dias": 30, "fuente": "LEY", "referencia": "art. 83 RRM"}, "publicacion": ["BORME"]}}'::jsonb, true, 'ACTIVE', CURRENT_DATE
WHERE NOT EXISTS (SELECT 1 FROM public.rule_pack_versions WHERE pack_id='MOD_ESTATUTOS' AND is_active=true);

INSERT INTO public.rule_packs (id, tenant_id, materia, organo_tipo, descripcion)
SELECT 'LIQUIDACION', '00000000-0000-0000-0000-000000000001'::uuid, 'LIQUIDACION', 'JUNTA_GENERAL', 'Garrigues/Comité Legal — LIQUIDACION'
WHERE NOT EXISTS (SELECT 1 FROM public.rule_packs WHERE id='LIQUIDACION');

INSERT INTO public.rule_pack_versions (pack_id, version, payload, is_active, status, effective_from)
SELECT 'LIQUIDACION', '1.0.0', '{"id": "LIQUIDACION", "materia": "LIQUIDACION", "clase": "ESTRUCTURAL", "organoTipo": "JUNTA_GENERAL", "modosAdopcionPermitidos": ["MEETING", "UNIVERSAL"], "acta": {"tipoActaPorModo": {"MEETING": "ACTA_JUNTA", "UNIVERSAL": "ACTA_JUNTA"}, "requiereConformidadConjunta": false, "requiereTranscripcionLibroActas": true}, "votacion": {"mayoria": {"SA": {"fuente": "LEY", "formula": "reforzada art. 201.2 LSC", "referencia": "art. 201.2 LSC — 2/3 capital presente (tramo 25-50% en 2ª conv.); art. 368 LSC (requisitos de modificación estatutaria) + arts. 360-400 LSC"}, "SL": {"fuente": "LEY", "formula": "favor > 1/2_capital_total_con_voto", "referencia": "art. 199.a LSC"}, "CONSEJO": {"fuente": "LEY", "formula": "favor > presentes_mitad", "referencia": "art. 247.1 LSC"}}, "abstenciones": "no_cuentan", "votoCalidadPermitido": false}, "constitucion": {"quorum": {"SL": {"valor": 0, "fuente": "LEY", "referencia": "art. 198 LSC"}, "SA_1a": {"valor": 0.5, "fuente": "LEY", "referencia": "art. 194.1 LSC"}, "SA_2a": {"valor": 0.25, "fuente": "LEY", "referencia": "art. 194.1 LSC"}, "CONSEJO": {"valor": "mayoria_miembros", "fuente": "LEY", "referencia": "art. 247.1 LSC"}}}, "convocatoria": {"canales": {"SA": ["BORME", "WEB_INSCRITA"], "SL": ["COMUNICACION_INDIVIDUAL_ESCRITA"]}, "antelacionDias": {"SA": {"valor": 30, "fuente": "LEY", "referencia": "art. 176.1 LSC"}, "SL": {"valor": 15, "fuente": "LEY", "referencia": "art. 176.1 LSC"}}, "contenidoMinimo": ["Fecha hora y lugar", "Texto íntegro de la propuesta", "Texto actual y propuesto"], "documentosObligatorios": [{"id": "propuesta", "nombre": "Texto íntegro de la propuesta (disolución y apertura de liquidación)", "condicion": "SIEMPRE"}, {"id": "informe_admin", "nombre": "Informe del órgano de administración", "condicion": "SIEMPRE"}]}, "documentacion": {"obligatoria": [{"id": "propuesta", "nombre": "Propuesta íntegra"}, {"id": "informe_admin_justificacion", "nombre": "Informe justificativo"}, {"id": "derecho_informacion_287", "nombre": "Derecho de información art. 287 LSC", "condicion": "SIEMPRE"}], "ventanaDisponibilidad": {"dias": 15, "fuente": "LEY"}}, "postAcuerdo": {"inscribible": true, "instrumentoRequerido": "ESCRITURA", "publicacionRequerida": true, "plazoInscripcion": {"dias": 30, "fuente": "LEY", "referencia": "art. 83 RRM (1 mes)"}}, "plazosMateriales": {"inscripcion": {"plazo_dias": 30, "fuente": "LEY", "referencia": "art. 83 RRM"}, "publicacion": ["BORME"]}}'::jsonb, true, 'ACTIVE', CURRENT_DATE
WHERE NOT EXISTS (SELECT 1 FROM public.rule_pack_versions WHERE pack_id='LIQUIDACION' AND is_active=true);

INSERT INTO public.rule_packs (id, tenant_id, materia, organo_tipo, descripcion)
SELECT 'VENTA_ACTIVOS_ESENCIALES', '00000000-0000-0000-0000-000000000001'::uuid, 'VENTA_ACTIVOS_ESENCIALES', 'JUNTA_GENERAL', 'Garrigues/Comité Legal — VENTA_ACTIVOS_ESENCIALES'
WHERE NOT EXISTS (SELECT 1 FROM public.rule_packs WHERE id='VENTA_ACTIVOS_ESENCIALES');

INSERT INTO public.rule_pack_versions (pack_id, version, payload, is_active, status, effective_from)
SELECT 'VENTA_ACTIVOS_ESENCIALES', '1.0.0', '{"id": "VENTA_ACTIVOS_ESENCIALES", "materia": "VENTA_ACTIVOS_ESENCIALES", "clase": "ESTRUCTURAL", "organoTipo": "JUNTA_GENERAL", "modosAdopcionPermitidos": ["MEETING", "UNIVERSAL"], "acta": {"tipoActaPorModo": {"MEETING": "ACTA_JUNTA", "UNIVERSAL": "ACTA_JUNTA"}, "requiereConformidadConjunta": false, "requiereTranscripcionLibroActas": true}, "votacion": {"mayoria": {"SA": {"fuente": "LEY", "formula": "reforzada art. 201.2 LSC", "referencia": "art. 201.2 LSC — 2/3 capital presente (tramo 25-50% en 2ª conv.); art. 160.f LSC"}, "SL": {"fuente": "LEY", "formula": "favor > 1/2_capital_total_con_voto", "referencia": "art. 199.a LSC"}, "CONSEJO": {"fuente": "LEY", "formula": "favor > presentes_mitad", "referencia": "art. 247.1 LSC"}}, "abstenciones": "no_cuentan", "votoCalidadPermitido": false}, "constitucion": {"quorum": {"SL": {"valor": 0, "fuente": "LEY", "referencia": "art. 198 LSC"}, "SA_1a": {"valor": 0.5, "fuente": "LEY", "referencia": "art. 194.1 LSC"}, "SA_2a": {"valor": 0.25, "fuente": "LEY", "referencia": "art. 194.1 LSC"}, "CONSEJO": {"valor": "mayoria_miembros", "fuente": "LEY", "referencia": "art. 247.1 LSC"}}}, "convocatoria": {"canales": {"SA": ["BORME", "WEB_INSCRITA"], "SL": ["COMUNICACION_INDIVIDUAL_ESCRITA"]}, "antelacionDias": {"SA": {"valor": 30, "fuente": "LEY", "referencia": "art. 176.1 LSC"}, "SL": {"valor": 15, "fuente": "LEY", "referencia": "art. 176.1 LSC"}}, "contenidoMinimo": ["Fecha hora y lugar", "Texto íntegro de la propuesta", "Texto actual y propuesto"], "documentosObligatorios": [{"id": "propuesta", "nombre": "Texto íntegro de la propuesta (enajenación de activos esenciales)", "condicion": "SIEMPRE"}, {"id": "informe_admin", "nombre": "Informe del órgano de administración", "condicion": "SIEMPRE"}]}, "documentacion": {"obligatoria": [{"id": "propuesta", "nombre": "Propuesta íntegra"}, {"id": "informe_admin_justificacion", "nombre": "Informe justificativo"}, {"id": "derecho_informacion_287", "nombre": "Derecho de información art. 287 LSC", "condicion": "SIEMPRE"}], "ventanaDisponibilidad": {"dias": 15, "fuente": "LEY"}}, "postAcuerdo": {"inscribible": false, "instrumentoRequerido": "NINGUNO", "publicacionRequerida": false, "plazoInscripcion": {"dias": 30, "fuente": "LEY", "referencia": "art. 83 RRM (1 mes)"}}, "plazosMateriales": {"inscripcion": {"plazo_dias": 30, "fuente": "LEY", "referencia": "art. 83 RRM"}, "publicacion": []}}'::jsonb, true, 'ACTIVE', CURRENT_DATE
WHERE NOT EXISTS (SELECT 1 FROM public.rule_pack_versions WHERE pack_id='VENTA_ACTIVOS_ESENCIALES' AND is_active=true);

INSERT INTO public.rule_packs (id, tenant_id, materia, organo_tipo, descripcion)
SELECT 'ADQUISICION_PROPIA', '00000000-0000-0000-0000-000000000001'::uuid, 'ADQUISICION_PROPIA', 'JUNTA_GENERAL', 'Garrigues/Comité Legal — ADQUISICION_PROPIA'
WHERE NOT EXISTS (SELECT 1 FROM public.rule_packs WHERE id='ADQUISICION_PROPIA');

INSERT INTO public.rule_pack_versions (pack_id, version, payload, is_active, status, effective_from)
SELECT 'ADQUISICION_PROPIA', '1.0.0', '{"id": "ADQUISICION_PROPIA", "materia": "ADQUISICION_PROPIA", "clase": "ORDINARIA", "organoTipo": "JUNTA_GENERAL", "modosAdopcionPermitidos": ["MEETING", "UNIVERSAL", "NO_SESSION"], "acta": {"tipoActaPorModo": {"MEETING": "ACTA_JUNTA", "UNIVERSAL": "ACTA_JUNTA"}, "requiereConformidadConjunta": false, "requiereTranscripcionLibroActas": true}, "votacion": {"mayoria": {"SA": {"fuente": "LEY", "formula": "favor > contra", "referencia": "art. 201.1 LSC (mayoría ordinaria)"}, "SL": {"fuente": "LEY", "formula": "favor > 1/3_capital", "referencia": "art. 198 LSC"}, "CONSEJO": {"fuente": "LEY", "formula": "favor > presentes_mitad", "referencia": "art. 247.1 LSC"}}, "abstenciones": "no_cuentan", "votoCalidadPermitido": true}, "constitucion": {"quorum": {"SL": {"valor": 0, "fuente": "LEY", "referencia": "art. 198 LSC"}, "SA_1a": {"valor": 0.25, "fuente": "LEY", "referencia": "art. 193.1 LSC"}, "SA_2a": {"valor": 0, "fuente": "LEY", "referencia": "art. 193.2 LSC"}, "CONSEJO": {"valor": "mayoria_miembros", "fuente": "LEY", "referencia": "art. 247.1 LSC"}}}, "convocatoria": {"canales": {"SA": ["BORME", "WEB_INSCRITA"], "SL": ["COMUNICACION_INDIVIDUAL_ESCRITA"]}, "antelacionDias": {"SA": {"valor": 30, "fuente": "LEY", "referencia": "art. 176.1 LSC"}, "SL": {"valor": 15, "fuente": "LEY", "referencia": "art. 176.1 LSC"}}, "contenidoMinimo": ["Fecha hora y lugar", "Orden del día"], "documentosObligatorios": [{"id": "propuesta", "nombre": "Propuesta de acuerdo (autocartera)", "condicion": "SIEMPRE"}]}, "documentacion": {"obligatoria": [{"id": "propuesta", "nombre": "Propuesta de acuerdo", "condicion": "SIEMPRE"}], "ventanaDisponibilidad": {"dias": 0}}, "postAcuerdo": {"inscribible": false, "instrumentoRequerido": "NINGUNO", "publicacionRequerida": false, "plazoInscripcion": null, "referencia": "arts. 140-148 LSC"}, "plazosMateriales": {"inscripcion": {"plazo_dias": null, "fuente": "LEY"}, "publicacion": []}}'::jsonb, true, 'ACTIVE', CURRENT_DATE
WHERE NOT EXISTS (SELECT 1 FROM public.rule_pack_versions WHERE pack_id='ADQUISICION_PROPIA' AND is_active=true);

INSERT INTO public.rule_packs (id, tenant_id, materia, organo_tipo, descripcion)
SELECT 'NOMBRAMIENTO_CESE', '00000000-0000-0000-0000-000000000001'::uuid, 'NOMBRAMIENTO_CESE', 'JUNTA_GENERAL', 'Garrigues/Comité Legal — NOMBRAMIENTO_CESE'
WHERE NOT EXISTS (SELECT 1 FROM public.rule_packs WHERE id='NOMBRAMIENTO_CESE');

INSERT INTO public.rule_pack_versions (pack_id, version, payload, is_active, status, effective_from)
SELECT 'NOMBRAMIENTO_CESE', '1.0.0', '{"id": "NOMBRAMIENTO_CESE", "materia": "NOMBRAMIENTO_CESE", "clase": "ORDINARIA", "organoTipo": "JUNTA_GENERAL", "modosAdopcionPermitidos": ["MEETING", "UNIVERSAL", "NO_SESSION"], "acta": {"tipoActaPorModo": {"MEETING": "ACTA_JUNTA", "UNIVERSAL": "ACTA_JUNTA"}, "requiereConformidadConjunta": false, "requiereTranscripcionLibroActas": true}, "votacion": {"mayoria": {"SA": {"fuente": "LEY", "formula": "favor > contra", "referencia": "art. 201.1 LSC (mayoría ordinaria)"}, "SL": {"fuente": "LEY", "formula": "favor > 1/3_capital", "referencia": "art. 198 LSC"}, "CONSEJO": {"fuente": "LEY", "formula": "favor > presentes_mitad", "referencia": "art. 247.1 LSC"}}, "abstenciones": "no_cuentan", "votoCalidadPermitido": true}, "constitucion": {"quorum": {"SL": {"valor": 0, "fuente": "LEY", "referencia": "art. 198 LSC"}, "SA_1a": {"valor": 0.25, "fuente": "LEY", "referencia": "art. 193.1 LSC"}, "SA_2a": {"valor": 0, "fuente": "LEY", "referencia": "art. 193.2 LSC"}, "CONSEJO": {"valor": "mayoria_miembros", "fuente": "LEY", "referencia": "art. 247.1 LSC"}}}, "convocatoria": {"canales": {"SA": ["BORME", "WEB_INSCRITA"], "SL": ["COMUNICACION_INDIVIDUAL_ESCRITA"]}, "antelacionDias": {"SA": {"valor": 30, "fuente": "LEY", "referencia": "art. 176.1 LSC"}, "SL": {"valor": 15, "fuente": "LEY", "referencia": "art. 176.1 LSC"}}, "contenidoMinimo": ["Fecha hora y lugar", "Orden del día"], "documentosObligatorios": [{"id": "propuesta", "nombre": "Propuesta de acuerdo (nombramiento de consejero (alias deprecado))", "condicion": "SIEMPRE"}]}, "documentacion": {"obligatoria": [{"id": "propuesta", "nombre": "Propuesta de acuerdo", "condicion": "SIEMPRE"}], "ventanaDisponibilidad": {"dias": 0}}, "postAcuerdo": {"inscribible": true, "instrumentoRequerido": "NINGUNO", "publicacionRequerida": false, "plazoInscripcion": {"dias": 30, "fuente": "LEY", "referencia": "art. 83 RRM"}, "referencia": "art. 214 LSC"}, "plazosMateriales": {"inscripcion": {"plazo_dias": 30, "fuente": "LEY"}, "publicacion": []}}'::jsonb, true, 'ACTIVE', CURRENT_DATE
WHERE NOT EXISTS (SELECT 1 FROM public.rule_pack_versions WHERE pack_id='NOMBRAMIENTO_CESE' AND is_active=true);

INSERT INTO public.rule_packs (id, tenant_id, materia, organo_tipo, descripcion)
SELECT 'REMUNERACION_CONSEJEROS', '00000000-0000-0000-0000-000000000001'::uuid, 'REMUNERACION_CONSEJEROS', 'JUNTA_GENERAL', 'Garrigues/Comité Legal — REMUNERACION_CONSEJEROS'
WHERE NOT EXISTS (SELECT 1 FROM public.rule_packs WHERE id='REMUNERACION_CONSEJEROS');

INSERT INTO public.rule_pack_versions (pack_id, version, payload, is_active, status, effective_from)
SELECT 'REMUNERACION_CONSEJEROS', '1.0.0', '{"id": "REMUNERACION_CONSEJEROS", "materia": "REMUNERACION_CONSEJEROS", "clase": "ORDINARIA", "organoTipo": "JUNTA_GENERAL", "modosAdopcionPermitidos": ["MEETING", "UNIVERSAL", "NO_SESSION"], "acta": {"tipoActaPorModo": {"MEETING": "ACTA_JUNTA", "UNIVERSAL": "ACTA_JUNTA"}, "requiereConformidadConjunta": false, "requiereTranscripcionLibroActas": true}, "votacion": {"mayoria": {"SA": {"fuente": "LEY", "formula": "favor > contra", "referencia": "art. 201.1 LSC (mayoría ordinaria)"}, "SL": {"fuente": "LEY", "formula": "favor > 1/3_capital", "referencia": "art. 198 LSC"}, "CONSEJO": {"fuente": "LEY", "formula": "favor > presentes_mitad", "referencia": "art. 247.1 LSC"}}, "abstenciones": "no_cuentan", "votoCalidadPermitido": true}, "constitucion": {"quorum": {"SL": {"valor": 0, "fuente": "LEY", "referencia": "art. 198 LSC"}, "SA_1a": {"valor": 0.25, "fuente": "LEY", "referencia": "art. 193.1 LSC"}, "SA_2a": {"valor": 0, "fuente": "LEY", "referencia": "art. 193.2 LSC"}, "CONSEJO": {"valor": "mayoria_miembros", "fuente": "LEY", "referencia": "art. 247.1 LSC"}}}, "convocatoria": {"canales": {"SA": ["BORME", "WEB_INSCRITA"], "SL": ["COMUNICACION_INDIVIDUAL_ESCRITA"]}, "antelacionDias": {"SA": {"valor": 30, "fuente": "LEY", "referencia": "art. 176.1 LSC"}, "SL": {"valor": 15, "fuente": "LEY", "referencia": "art. 176.1 LSC"}}, "contenidoMinimo": ["Fecha hora y lugar", "Orden del día"], "documentosObligatorios": [{"id": "propuesta", "nombre": "Propuesta de acuerdo (política de remuneración de consejeros)", "condicion": "SIEMPRE"}]}, "documentacion": {"obligatoria": [{"id": "propuesta", "nombre": "Propuesta de acuerdo", "condicion": "SIEMPRE"}], "ventanaDisponibilidad": {"dias": 0}}, "postAcuerdo": {"inscribible": false, "instrumentoRequerido": "NINGUNO", "publicacionRequerida": false, "plazoInscripcion": null, "referencia": "art. 217 LSC (y 529 sexdecies para cotizada)"}, "plazosMateriales": {"inscripcion": {"plazo_dias": null, "fuente": "LEY"}, "publicacion": []}}'::jsonb, true, 'ACTIVE', CURRENT_DATE
WHERE NOT EXISTS (SELECT 1 FROM public.rule_pack_versions WHERE pack_id='REMUNERACION_CONSEJEROS' AND is_active=true);

DO $$
DECLARE v_missing integer;
BEGIN
  SELECT count(*) INTO v_missing FROM (VALUES ('AMPLIACION_OBJETO_SOCIAL'),('CAMBIO_DENOMINACION_SOCIAL'),('CAMBIO_DOMICILIO_SOCIAL'),('DELEGACION_CAPITAL'),('EMISION_DEUDA_CONVERTIBLE'),('EXCLUSION_DERECHO_SUSCRIPCION_PREFERENTE'),('PRORROGA_SOCIEDAD'),('AMPLIACION_CAPITAL'),('MOD_ESTATUTOS'),('LIQUIDACION'),('VENTA_ACTIVOS_ESENCIALES'),('ADQUISICION_PROPIA'),('NOMBRAMIENTO_CESE'),('REMUNERACION_CONSEJEROS')) AS t(m)
   WHERE NOT EXISTS (SELECT 1 FROM public.rule_packs rp JOIN public.rule_pack_versions v ON v.pack_id=rp.id AND v.is_active
                     WHERE rp.materia=t.m);
  IF v_missing <> 0 THEN RAISE EXCEPTION 'ITEM-054 verificación fallida: % materias sin pack activo', v_missing; END IF;
END $$;
